/*
 * port/rando/rando.h — in-process randomizer for Project Picori.
 *
 * Derived from the GPL-3.0 Minish Cap randomizer (MinishMaker,
 * minishmaker/randomizer). Distributed under the GPL-3.0 with attribution;
 * see THIRD-PARTY-LICENSES.md. Defines locations, items, logical connections,
 * and settings.
 */

#ifndef PORT_RANDO_RANDO_H
#define PORT_RANDO_RANDO_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    RANDO_OK = 0,
    RANDO_INACTIVE,
    RANDO_INTERNAL,
    RANDO_UNBEATABLE,
    RANDO_BAD_SETTINGS,
} RandoStatus;

#define RANDO_LOCATION_COUNT 228

typedef enum {
    RANDO_ITEM_POOL_NORMAL = 0,
    RANDO_ITEM_POOL_HARD,
    RANDO_ITEM_POOL_CHAOS,
    RANDO_ITEM_POOL_COUNT,
} RandoItemPoolDifficulty;

/* Legacy native-graph trick bits. Fresh parser seeds require glitchless
 * settings; future trick support must map these to the upstream .logic rules. */
#define RANDO_TRICK_OCARINA_GLITCH (1u << 0)      /* OG: Temple of Droplets entry without Flippers (needs Ocarina) */
#define RANDO_TRICK_CRENEL_CLIP (1u << 1)         /* Crenel Clip: reach Castor Wilds from Mt. Crenel (needs a Bottle) */
#define RANDO_TRICK_PORTAL_JUMP_STORAGE (1u << 2) /* PJS: reach Cloud Tops early without Roc's Cape (needs Ocarina) */
#define RANDO_TRICK_ALL (RANDO_TRICK_OCARINA_GLITCH | RANDO_TRICK_CRENEL_CLIP | RANDO_TRICK_PORTAL_JUMP_STORAGE)

/* Accessibility maps to upstream ACCESSIBILITY for fresh seeds. */
typedef enum {
    RANDO_ACCESS_GOAL = 0,      /* only the goal must be reachable (default) */
    RANDO_ACCESS_ALL_NONKEYS,   /* every enabled non-key check reachable */
    RANDO_ACCESS_ALL_LOCATIONS, /* every enabled check reachable */
    RANDO_ACCESS_COUNT,
} RandoAccessibility;

/* --- Per-dungeon dungeon-item identity -----------------------------------
 * The engine stores small keys / big keys / maps / compasses PER DUNGEON
 * (gSave.dungeonKeys[16] / gSave.dungeonItems[16], indexed by
 * gArea.dungeon_idx = area location - 23). A dungeon item collected outside
 * its home dungeon must credit its ORIGIN dungeon, not the current area —
 * the vanilla give path (itemUtils.c GiveItem cases 5/6) always credits the
 * current area, so shuffled dungeon items ride an origin tag in the item
 * SUBTYPE byte: 0x80 | origin_dungeon_idx. Vanilla gives use subtype 0, so
 * bit 7 doubles as the "rando origin present" sentinel. Kinstone subtypes
 * (0x70..0x75) never set bit 7.
 *
 * Inside the SOLVER ONLY (never in the item table or on the wire), a placed
 * dungeon item is tracked as a VIRTUAL item id so reachability distinguishes
 * e.g. Palace's big key from Deepwood's: real ids end at 0x75 and the drop
 * sentinels start at 0xFC, so 0x80..0xBF is free. */
#define RANDO_DUNGEON_ORIGIN_SUBTYPE(d) ((uint8_t)(0x80u | ((d) & 0x0Fu)))
#define RANDO_SUBTYPE_HAS_ORIGIN(s) (((s) & 0x80u) != 0)
#define RANDO_SUBTYPE_ORIGIN(s) ((unsigned)((s) & 0x0Fu))
#define RANDO_VITEM_BIG_KEY(d) (0x80u + ((d) & 0x0Fu)) /* 0x80..0x8F */
#define RANDO_VITEM_MAP(d) (0x90u + ((d) & 0x0Fu))     /* 0x90..0x9F */
#define RANDO_VITEM_COMPASS(d) (0xA0u + ((d) & 0x0Fu)) /* 0xA0..0xAF */

typedef struct RandomizerSettings {
    bool glitchless_logic;
    bool obscure_locations;
    bool shuffle_kinstones;
    bool shuffle_entrances; /* coupled dungeon-entrance shuffle (was hijacking shuffle_kinstones) */
    bool shuffle_dojos;
    bool open_world;
    RandoItemPoolDifficulty item_difficulty;
    uint32_t tricks;                  /* RANDO_TRICK_* bitmask; ignored when glitchless_logic is true */
    RandoAccessibility accessibility; /* verifier strength; RANDO_ACCESS_GOAL = historical */
    bool shuffle_dungeon_items;       /* big keys/maps/compasses join the pool (default off = pinned vanilla) */
    bool homewarp;
    bool start_sword;
    bool early_crests;
    bool instant_text;
    int tunic_color;
    int heart_color;
} RandomizerSettings;

typedef enum {
    RANDO_LOC_CATEGORY_CHEST = 0,
    RANDO_LOC_CATEGORY_DIG_SPOT,
    RANDO_LOC_CATEGORY_GROTTO,
    RANDO_LOC_CATEGORY_HEART_PIECE,
    RANDO_LOC_CATEGORY_DOJO,
    RANDO_LOC_CATEGORY_KEY_ITEM,
    RANDO_LOC_CATEGORY_ELEMENT,
    RANDO_LOC_CATEGORY_KINSTONE_FUSION,
} RandoLocationCategory;

typedef enum {
    RANDO_LOC_LINK_S_HOUSE_FLOOR_ITEM_1 = 0,
    RANDO_LOC_LINK_S_HOUSE_FLOOR_ITEM_2 = 1,
    RANDO_LOC_DEEPWOOD_SHRINE_1F_BLUE_WARP_HEART_PIECE = 2,
    RANDO_LOC_DEEPWOOD_SHRINE_1F_MADDERPILLAR_HEART_PIECE = 3,
    RANDO_LOC_DEEPWOOD_SHRINE_1F_EAST_MULLDOZER_FIGHT_ITEM = 4,
    RANDO_LOC_DEEPWOOD_SHRINE_BOSS_ITEM = 5,
    RANDO_LOC_DEEPWOOD_SHRINE_PRIZE = 6,
    RANDO_LOC_CAVE_OF_FLAMES_1F_ITEM_1 = 7,
    RANDO_LOC_CAVE_OF_FLAMES_1F_ITEM_2 = 8,
    RANDO_LOC_CAVE_OF_FLAMES_1F_ITEM_3 = 9,
    RANDO_LOC_CAVE_OF_FLAMES_1F_ITEM_4 = 10,
    RANDO_LOC_CAVE_OF_FLAMES_1F_ITEM_5 = 11,
    RANDO_LOC_CAVE_OF_FLAMES_B1_HEART_PIECE = 12,
    RANDO_LOC_CAVE_OF_FLAMES_BOSS_ITEM = 13,
    RANDO_LOC_CAVE_OF_FLAMES_PRIZE = 14,
    RANDO_LOC_FORTRESS_OF_WINDS_ENTRANCE_1F_RIGHT_ITEM = 15,
    RANDO_LOC_FORTRESS_OF_WINDS_ENTRANCE_1F_RIGHT_HEART_PIECE = 16,
    RANDO_LOC_FORTRESS_OF_WINDS_LEFT_2F_ITEM_1 = 17,
    RANDO_LOC_FORTRESS_OF_WINDS_LEFT_2F_ITEM_2 = 18,
    RANDO_LOC_FORTRESS_OF_WINDS_LEFT_2F_ITEM_3 = 19,
    RANDO_LOC_FORTRESS_OF_WINDS_LEFT_2F_ITEM_4 = 20,
    RANDO_LOC_FORTRESS_OF_WINDS_LEFT_2F_ITEM_5 = 21,
    RANDO_LOC_FORTRESS_OF_WINDS_LEFT_2F_ITEM_6 = 22,
    RANDO_LOC_FORTRESS_OF_WINDS_LEFT_2F_ITEM_7 = 23,
    RANDO_LOC_FORTRESS_OF_WINDS_BACK_RIGHT_DIG_ROOM_TOP_POT = 24,
    RANDO_LOC_FORTRESS_OF_WINDS_BACK_RIGHT_DIG_ROOM_BOTTOM_POT = 25,
    RANDO_LOC_FORTRESS_OF_WINDS_LEFT_3F_ITEM_DROP = 26,
    RANDO_LOC_FORTRESS_OF_WINDS_RIGHT_3F_ITEM_DROP = 27,
    RANDO_LOC_FORTRESS_OF_WINDS_BACK_RIGHT_STATUE_ITEM_DROP = 28,
    RANDO_LOC_FORTRESS_OF_WINDS_BACK_RIGHT_MINISH_ITEM_DROP = 29,
    RANDO_LOC_FORTRESS_OF_WINDS_BOSS_ITEM = 30,
    RANDO_LOC_FORTRESS_OF_WINDS_PRIZE = 31,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER_1 = 32,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER_2 = 33,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER_3 = 34,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER_4 = 35,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER_5 = 36,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER_6 = 37,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM_1 = 38,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM_2 = 39,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM_3 = 40,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM_4 = 41,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM_5 = 42,
    RANDO_LOC_TEMPLE_OF_DROPLETS_RIGHT_PATH_B1_POT = 43,
    RANDO_LOC_TEMPLE_OF_DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM_1 = 44,
    RANDO_LOC_TEMPLE_OF_DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM_2 = 45,
    RANDO_LOC_TEMPLE_OF_DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM_3 = 46,
    RANDO_LOC_TEMPLE_OF_DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM_4 = 47,
    RANDO_LOC_TEMPLE_OF_DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM_5 = 48,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER_1 = 49,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER_2 = 50,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER_3 = 51,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER_4 = 52,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER_5 = 53,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER_6 = 54,
    RANDO_LOC_TEMPLE_OF_DROPLETS_LEFT_PATH_B2_UNDERWATER_POT = 55,
    RANDO_LOC_TEMPLE_OF_DROPLETS_RIGHT_PATH_B2_MULLDOZERS_ITEM_DROP = 56,
    RANDO_LOC_TEMPLE_OF_DROPLETS_ENTRANCE_B2_WEST_ICEBLOCK = 57,
    RANDO_LOC_TEMPLE_OF_DROPLETS_ENTRANCE_B2_EAST_ICEBLOCK = 58,
    RANDO_LOC_TEMPLE_OF_DROPLETS_BOSS_ITEM = 59,
    RANDO_LOC_TEMPLE_OF_DROPLETS_PRIZE = 60,
    RANDO_LOC_ROYAL_CRYPT_LEFT_ITEM = 61,
    RANDO_LOC_ROYAL_CRYPT_RIGHT_ITEM = 62,
    RANDO_LOC_ROYAL_CRYPT_GIBDO_LEFT_ITEM = 63,
    RANDO_LOC_ROYAL_CRYPT_GIBDO_RIGHT_ITEM = 64,
    RANDO_LOC_ROYAL_CRYPT_PRIZE = 65,
    RANDO_LOC_PALACE_OF_WINDS_2ND_HALF_4F_HEART_PIECE = 66,
    RANDO_LOC_PALACE_OF_WINDS_1ST_HALF_2F_ITEM_1 = 67,
    RANDO_LOC_PALACE_OF_WINDS_1ST_HALF_2F_ITEM_2 = 68,
    RANDO_LOC_PALACE_OF_WINDS_1ST_HALF_2F_ITEM_3 = 69,
    RANDO_LOC_PALACE_OF_WINDS_1ST_HALF_2F_ITEM_4 = 70,
    RANDO_LOC_PALACE_OF_WINDS_1ST_HALF_2F_ITEM_5 = 71,
    RANDO_LOC_PALACE_OF_WINDS_1ST_HALF_3F_POT_PUZZLE_ITEM_DROP = 72,
    RANDO_LOC_PALACE_OF_WINDS_1ST_HALF_5F_BALL_AND_CHAIN_SOLDIERS_ITEM_DROP = 73,
    RANDO_LOC_PALACE_OF_WINDS_BOSS_ITEM = 74,
    RANDO_LOC_PALACE_OF_WINDS_PRIZE = 75,
    RANDO_LOC_DARK_HYRULE_CASTLE_B2_KING = 76,
    RANDO_LOC_HYRULE_TOWN_INN_BACKDOOR_HEART_PIECE = 77,
    RANDO_LOC_HYRULE_TOWN_MUSIC_HOUSE_HEART_PIECE = 78,
    RANDO_LOC_HYRULE_TOWN_SCHOOL_PATH_HEART_PIECE = 79,
    RANDO_LOC_HYRULE_TOWN_FOUNTAIN_HEART_PIECE = 80,
    RANDO_LOC_HYRULE_TOWN_UNDER_LIBRARY_UNDERWATER = 81,
    RANDO_LOC_HYRULE_TOWN_BELL_HEART_PIECE = 82,
    RANDO_LOC_HYRULE_TOWN_SHOP_80_ITEM = 83,
    RANDO_LOC_HYRULE_TOWN_SHOP_300_ITEM = 84,
    RANDO_LOC_HYRULE_TOWN_SHOP_600_ITEM = 85,
    RANDO_LOC_HYRULE_TOWN_SHOP_EXTRA_600_ITEM = 86,
    RANDO_LOC_HYRULE_TOWN_SHOP_BEHIND_COUNTER_ITEM = 87,
    RANDO_LOC_HYRULE_TOWN_JULLIETA_ITEM = 88,
    RANDO_LOC_HYRULE_TOWN_DR_LEFT_ATTIC_ITEM = 89,
    RANDO_LOC_HYRULE_TOWN_LIBRARY_YELLOW_MINISH_REWARD = 90,
    RANDO_LOC_HYRULE_TOWN_CAFE_LADY_REWARD = 91,
    RANDO_LOC_HYRULE_TOWN_CARLOV_REWARD = 92,
    RANDO_LOC_HYRULE_TOWN_SIMULATION_CHEST = 93,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_1_LEFT = 94,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_1_MIDDLE = 95,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_1_RIGHT = 96,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_2_LEFT = 97,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_2_MIDDLE = 98,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_2_RIGHT = 99,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_3_LEFT = 100,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_3_MIDDLE = 101,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_3_RIGHT = 102,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_4_LEFT = 103,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_4_MIDDLE = 104,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_4_RIGHT = 105,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_5_LEFT = 106,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_5_MIDDLE = 107,
    RANDO_LOC_HYRULE_TOWN_GORON_MERCHANT_5_RIGHT = 108,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_1_REWARD = 109,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_2_REWARD = 110,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_3_REWARD = 111,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_4_REWARD = 112,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_5_REWARD = 113,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_6_REWARD = 114,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_7_REWARD = 115,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_8_REWARD = 116,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_9_REWARD = 117,
    RANDO_LOC_HYRULE_TOWN_CUCCOS_LEVEL_10_REWARD = 118,
    RANDO_LOC_HYRULE_TOWN_SHOE_SHOP_REWARD = 119,
    RANDO_LOC_HYRULE_TOWN_DOJO_REWARD_1 = 120,
    RANDO_LOC_HYRULE_TOWN_DOJO_REWARD_2 = 121,
    RANDO_LOC_HYRULE_TOWN_DOJO_REWARD_3 = 122,
    RANDO_LOC_HYRULE_TOWN_DOJO_REWARD_4 = 123,
    RANDO_LOC_SOUTH_HYRULE_FIELD_MINISH_SIZE_WATER_HOLE_HEART_PIECE = 124,
    RANDO_LOC_SOUTH_HYRULE_FIELD_TINGLE_REWARD = 125,
    RANDO_LOC_EASTERN_HILLS_FARM_DIG_CAVE_ITEM = 126,
    RANDO_LOC_MINISH_WOODS_TOP_HEART_PIECE = 127,
    RANDO_LOC_MINISH_WOODS_BOTTOM_HEART_PIECE = 128,
    RANDO_LOC_MINISH_WOODS_FLIPPER_HOLE_HEART_PIECE = 129,
    RANDO_LOC_MINISH_WOODS_WITCH_HUT_ITEM = 130,
    RANDO_LOC_MINISH_WOODS_BOMB_MINISH_REWARD_1 = 131,
    RANDO_LOC_MINISH_WOODS_BOMB_MINISH_REWARD_2 = 132,
    RANDO_LOC_MINISH_VILLAGE_HEART_PIECE = 133,
    RANDO_LOC_MINISH_VILLAGE_BARREL_HOUSE_ITEM = 134,
    RANDO_LOC_MINISH_WOODS_GREAT_FAIRY_REWARD = 135,
    RANDO_LOC_TRILBY_HIGHLANDS_SCRUB_REWARD = 136,
    RANDO_LOC_MOUNT_CRENEL_BASE_ENTRANCE_VINE = 137,
    RANDO_LOC_MOUNT_CRENEL_BASE_FAIRY_CAVE_ITEM_1 = 138,
    RANDO_LOC_MOUNT_CRENEL_BASE_FAIRY_CAVE_ITEM_2 = 139,
    RANDO_LOC_MOUNT_CRENEL_BASE_FAIRY_CAVE_ITEM_3 = 140,
    RANDO_LOC_MOUNT_CRENEL_BASE_WATER_CAVE_HEART_PIECE = 141,
    RANDO_LOC_MOUNT_CRENEL_DIG_CAVE_HEART_PIECE = 142,
    RANDO_LOC_MOUNT_CRENEL_FAIRY_CAVE_HEART_PIECE = 143,
    RANDO_LOC_MOUNT_CRENEL_SCRUB_REWARD = 144,
    RANDO_LOC_MOUNT_CRENEL_DOJO_HEART_PIECE = 145,
    RANDO_LOC_MOUNT_CRENEL_DOJO_REWARD = 146,
    RANDO_LOC_MOUNT_CRENEL_GREAT_FAIRY_REWARD = 147,
    RANDO_LOC_MOUNT_CRENEL_MELARI_UPPER_TOP_MIDDLE_DIG = 148,
    RANDO_LOC_MOUNT_CRENEL_MELARI_UPPER_TOP_RIGHT_DIG = 149,
    RANDO_LOC_MOUNT_CRENEL_MELARI_UPPER_MIDDLE_RIGHT_DIG = 150,
    RANDO_LOC_MOUNT_CRENEL_MELARI_UPPER_MIDDLE_LEFT_DIG = 151,
    RANDO_LOC_MOUNT_CRENEL_MELARI_REWARD = 152,
    RANDO_LOC_CASTOR_WILDS_NEAR_WATERFALL_CAVE_HEART_PIECE = 153,
    RANDO_LOC_CASTOR_WILDS_DOJO_HEART_PIECE = 154,
    RANDO_LOC_CASTOR_WILDS_DOJO_REWARD = 155,
    RANDO_LOC_CASTOR_WILDS_WATERFALL_FUSION_DOJO_REWARD = 156,
    RANDO_LOC_WIND_RUINS_MINISH_CAVE_HEART_PIECE = 157,
    RANDO_LOC_ROYAL_VALLEY_GRAVEYARD_LEFT_GRAVE_HEART_PIECE = 158,
    RANDO_LOC_ROYAL_VALLEY_LOST_WOODS_CHEST = 159,
    RANDO_LOC_ROYAL_VALLEY_GREAT_FAIRY_REWARD = 160,
    RANDO_LOC_ROYAL_VALLEY_DAMPE_REWARD = 161,
    RANDO_LOC_NORTH_HYRULE_FIELD_HEART_PIECE = 162,
    RANDO_LOC_NORTH_HYRULE_FIELD_DIG_SPOT = 163,
    RANDO_LOC_NORTH_HYRULE_FIELD_WATERFALL_FUSION_DOJO_REWARD = 164,
    RANDO_LOC_HYRULE_CASTLE_GARDEN_DOJO_HEART_PIECE = 165,
    RANDO_LOC_HYRULE_CASTLE_GARDEN_DOJO_REWARD = 166,
    RANDO_LOC_LON_LON_RANCH_PATH_HEART_PIECE = 167,
    RANDO_LOC_LON_LON_RANCH_DIG_SPOT = 168,
    RANDO_LOC_LAKE_HYLIA_CAPE_CAVE_LON_LON_HEART_PIECE = 169,
    RANDO_LOC_LAKE_HYLIA_SMALL_ISLAND_HEART_PIECE = 170,
    RANDO_LOC_LAKE_HYLIA_BOTTOM_HEART_PIECE = 171,
    RANDO_LOC_LAKE_HYLIA_DOJO_HEART_PIECE = 172,
    RANDO_LOC_LAKE_HYLIA_DOJO_REWARD = 173,
    RANDO_LOC_LAKE_HYLIA_DOG_REWARD = 174,
    RANDO_LOC_LAKE_HYLIA_MAYOR_CABIN_ITEM = 175,
    RANDO_LOC_VEIL_FALLS_ENTRANCE_HEART_PIECE = 176,
    RANDO_LOC_VEIL_FALLS_LOWER_HEART_PIECE = 177,
    RANDO_LOC_VEIL_FALLS_LOWER_ROCK_ITEM_1 = 178,
    RANDO_LOC_VEIL_FALLS_LOWER_ROCK_ITEM_2 = 179,
    RANDO_LOC_VEIL_FALLS_LOWER_ROCK_ITEM_3 = 180,
    RANDO_LOC_VEIL_FALLS_LOWER_WATERFALL_FUSION_DOJO_REWARD = 181,
    RANDO_LOC_VEIL_FALLS_NORTH_DIG_SPOT = 182,
    RANDO_LOC_VEIL_FALLS_SOUTH_DIG_SPOT = 183,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_TOP_TOP = 184,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_TOP_LEFT = 185,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_TOP_MIDDLE = 186,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_TOP_RIGHT = 187,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_TOP_BOTTOM = 188,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_SIDE_TOP = 189,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_SIDE_LEFT = 190,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_SIDE_RIGHT = 191,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_SIDE_BOTTOM = 192,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_UNDERWATER_TOP_LEFT = 193,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_UNDERWATER_TOP_RIGHT = 194,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_UNDERWATER_MIDDLE_LEFT = 195,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_UNDERWATER_MIDDLE_RIGHT = 196,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_UNDERWATER_BOTTOM_LEFT = 197,
    RANDO_LOC_VEIL_FALLS_RUPEE_CAVE_UNDERWATER_BOTTOM_RIGHT = 198,
    RANDO_LOC_VEIL_FALLS_BIGGORON = 199,
    RANDO_LOC_CLOUD_TOPS_NORTH_KILL = 200,
    RANDO_LOC_CLOUD_TOPS_SOUTH_KILL = 201,
    RANDO_LOC_CLOUD_TOPS_NORTH_WEST_DIG_SPOT = 202,
    RANDO_LOC_CLOUD_TOPS_NORTH_EAST_DIG_SPOT = 203,
    RANDO_LOC_CLOUD_TOPS_SOUTH_MIDDLE_DIG_SPOT = 204,
    RANDO_LOC_CLOUD_TOPS_SOUTH_EAST_TOP_DIG_SPOT = 205,
    RANDO_LOC_CLOUD_TOPS_SOUTH_DIG_SPOT = 206,
    RANDO_LOC_CLOUD_TOPS_SOUTH_RIGHT_DIG_SPOT = 207,
    RANDO_LOC_CLOUD_TOPS_SOUTH_EAST_BOTTOM_DIG_SPOT = 208,
    RANDO_LOC_WIND_TRIBE_2F_GREGAL_REWARD_1 = 209,
    RANDO_LOC_WIND_TRIBE_2F_GREGAL_REWARD_2 = 210,
    /* Dungeon-item chests (maps / compasses / big keys), appended so all
     * prior ids stay stable. Shuffled only when shuffle_dungeon_items;
     * pinned vanilla otherwise. Sidecar v7. */
    RANDO_LOC_DEEPWOOD_SHRINE_MAP_CHEST = 211,
    RANDO_LOC_DEEPWOOD_SHRINE_BIG_KEY_CHEST = 212,
    RANDO_LOC_DEEPWOOD_SHRINE_COMPASS_CHEST = 213,
    RANDO_LOC_CAVE_OF_FLAMES_MAP_CHEST = 214,
    RANDO_LOC_CAVE_OF_FLAMES_COMPASS_CHEST = 215,
    RANDO_LOC_CAVE_OF_FLAMES_BIG_KEY_CHEST = 216,
    RANDO_LOC_FORTRESS_OF_WINDS_COMPASS_CHEST = 217,
    RANDO_LOC_FORTRESS_OF_WINDS_MAP_CHEST = 218,
    RANDO_LOC_FORTRESS_OF_WINDS_BIG_KEY_CHEST = 219,
    RANDO_LOC_TEMPLE_OF_DROPLETS_MAP_CHEST = 220,
    RANDO_LOC_TEMPLE_OF_DROPLETS_COMPASS_CHEST = 221,
    RANDO_LOC_PALACE_OF_WINDS_BIG_KEY_CHEST = 222,
    RANDO_LOC_PALACE_OF_WINDS_MAP_CHEST = 223,
    RANDO_LOC_PALACE_OF_WINDS_COMPASS_CHEST = 224,
    RANDO_LOC_DARK_HYRULE_CASTLE_BIG_KEY_CHEST = 225,
    RANDO_LOC_DARK_HYRULE_CASTLE_COMPASS_CHEST = 226,
    RANDO_LOC_DARK_HYRULE_CASTLE_MAP_CHEST = 227,
} RandoLocationId;

typedef struct RandoLocationDef {
    uint32_t key;
    uint8_t category;
    const char* name;
    uint16_t vanilla_item;
    uint8_t helper;
    uint8_t req_sword;
    uint8_t req_bombs;
    uint16_t req_items[3];
} RandoLocationDef;

extern uint16_t randomized_item_table[RANDO_LOCATION_COUNT];
extern uint8_t randomized_item_subtype_table[RANDO_LOCATION_COUNT];

RandomizerSettings Rando_DefaultSettings(void);
uint64_t Rando_SeedFromString(const char* text);

/* Legacy menu-settings hash. Parser-backed seeds use the 64-bit logic source
 * fingerprint below, which covers the bundled .logic bytes and overrides. */
uint32_t Rando_SettingsFingerprint(const RandomizerSettings* settings);

/* Required API for the file-select UI. */
bool GenerateSeed(uint64_t seed, RandomizerSettings settings);

RandoStatus Rando_GenerateSeed(uint64_t seed, const RandomizerSettings* settings, uint64_t* out_seed);
void Rando_Reset(void);
bool Rando_IsActive(void);
bool Rando_IsLogicSeed(void);
uint64_t Rando_GetLogicFingerprint(void);
uint32_t Rando_GetSeed(void);
uint64_t Rando_GetSeed64(void);
RandomizerSettings Rando_GetSettings(void);
void Rando_SetCosmetics(int tunic_color, int heart_color);
const uint16_t* Rando_GetRandomizedItemTable(void);
const uint8_t* Rando_GetRandomizedItemSubtypeTable(void);
size_t Rando_GetLocationCount(void);
const RandoLocationDef* Rando_GetLocationDef(RandoLocationId id);
uint16_t Rando_ResolveLocationItem(RandoLocationId location, uint16_t vanilla_item);
bool Rando_ActivateTable(uint64_t seed, RandomizerSettings settings, const uint16_t* table,
                         const uint8_t* subtype_table, size_t count);
bool Rando_ActivateLogicTable(uint64_t seed, RandomizerSettings settings, const uint16_t* table,
                              const uint8_t* subtype_table, size_t count, uint64_t fingerprint);

bool Rando_VerifyCurrentSeed(void);

bool Rando_OverrideLocationKey(uint32_t location_key, uint8_t* type, uint8_t* subtype);

bool Rando_OverrideItem(uint8_t* type, uint8_t* subtype);

/* Returns the required buffer size including NUL. Pass NULL, 0 to size a copy. */
size_t Rando_GetSpoiler(char* buf, size_t buflen);

#ifdef __cplusplus
}
#endif

#endif /* PORT_RANDO_RANDO_H */
