/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 * Generated by tools/gen_stubs.py
 */

#include "gba/m4a.h"
#include "port_config.h"
#include "room.h"

/*
 * Data stubs: temporary placeholders for assets (SFX/MUS/ROM tables).
 * Replace with real ROM mapping / asset loading later.
 */

/* gUnk_080046A4 and gUnk_080047F6 now provided by src/data/data_080046A4.c */
/* BG tilemap DMA size table (u16[4]): sizes for screen sizes 0-3 */
const u16 gUnk_080B2CD8[4] = { 0x0800, 0x1000, 0x1000, 0x2000 };
/* Direction offset table (s16 xy pairs, indexed by animationState & 6).
   Used by UpdatePlayerCollision to check the tile AHEAD of the player. */
const s16 gUnk_080B4468[8] = {
    0,   -15, /* North: 15px above */
    12,  -3,  /* East:  12px right, 3px above */
    0,   9,   /* South: 9px below */
    -12, -3,  /* West:  12px left, 3px above */
};
/* Direction offset table for door transition position calculation. */
const s16 gUnk_080B4478[8] = {
    0,   -15, /* North */
    12,  -3,  /* East */
    0,   12,  /* South */
    -12, -3,  /* West */
};
/* Tile position offset per direction (s16[4], indexed by direction >> 3).
   -64 = one row up, +1 = one col right, +64 = one row down, -1 = one col left. */
const s16 gUnk_080B4488[4] = { -64, 1, 64, -1 };
/* Direction offset table for border/scroll checks (s16 xy pairs). */
const s16 gUnk_080B4490[8] = {
    0,  -9, /* North */
    6,  0,  /* East */
    0,  3,  /* South */
    -6, 0,  /* West */
};
/* Collision direction masks (u16[4], indexed by animationState >> 1). */
const u16 gUnk_080B44A0[4] = { 0x000E, 0xE000, 0x00E0, 0x0E00 };
/* Direction offset table (s16 xy pairs) for climbing/ladder checks. */
const s16 gUnk_080B44A8[8] = {
    0,   -12, /* North */
    12,  0,   /* East */
    0,   12,  /* South */
    -12, 0,   /* West */
};
/* gUnk_080B44B8: function pointer table for tile entity condition checks.
   On GBA these are sub_0801AE30 (always TRUE) and sub_0801AE34 (scroll_flags check).
   Using non-zero values so the != 0 check passes. */
const u32 gUnk_080B44B8[2] = { 1, 1 };
/* gUnk_080B44C0: tile entity table for layer 1 â€” empty (just terminator 0xFFFF) */
const u16 gUnk_080B44C0[] = { 0xFFFF };
/* gUnk_080B44C2: tile entity table for layer 2 â€” 1 entry + terminator
   Data { tileType=0x75, kind=9, id=0x25, type=0, type2=0, unk_a=1 } */
const u16 gUnk_080B44C2[] = { 0x0075, 0x0009, 0x0025, 0x0000, 0x0000, 0x0001, 0xFFFF };
u8 gUnk_080C9044[8] = { 0 };
/* Hitbox data (gUnk_080FD178 through gUnk_080FD588) is now provided by src/data/hitbox.c */
/* Font/text data â€” loaded from ROM by Port_LoadRom */
void* gTextVariableSources[5];
u8 gUnk_08109244[4] __attribute__((aligned(4)));
void* gUnk_08109248[9];
u8 gUnk_0810926C[64] __attribute__((aligned(4)));
void* gUnk_081092AC[10];
u8 gUnk_081092D4[346] __attribute__((aligned(4)));
u8 gUnk_0810942E[160] __attribute__((aligned(4)));
u8 gUnk_081094CE[1378] __attribute__((aligned(4)));
void* gUnk_0810B6EC[21]; /* SpriteLoadData* pointer table â€” resolved at init */
/* gUnk_0810B774 and gUnk_0810B77C: function pointer tables, defined in port_linked_stubs.c */
/* gUnk_08128A38: defined in figurineMenuData.c (struct with func ptrs) */
/* gUnk_08128AD8: defined in figurineMenuData.c */
/* gUnk_08128D14, gUnk_08128D24, gUnk_08128D30: func ptr tables, defined in port_linked_stubs.c */
/* gUnk_08128D58: func ptr table, defined in port_linked_stubs.c */
/* gUnk_08128DB0: func ptr table, defined in port_linked_stubs.c */
/* gUnk_08128DCC: func ptr table, defined in port_linked_stubs.c */
/* gUnk_08128E78: func ptr table, defined in port_linked_stubs.c */
/* gUnk_08128F1C: func ptr table, defined in port_linked_stubs.c */
/* gUnk_0812901C -- defined in port_stubs.c as proper function pointer table */
/* gUnk_08133368 (OBJ palettes) now provided by src/data/objPalettes.c */
/* gUnk_08134FBC, gUnk_08135048, gUnk_08135190, gUnk_0813A76C now provided by src/data/transitions.c */
/* gUnk_0813AB58..gUnk_0813ADEC (screen transitions) now provided by src/data/screenTransitions.c */
const SongHeader sfx100 = { 0 };
const SongHeader sfx101 = { 0 };
const SongHeader sfx102 = { 0 };
const SongHeader sfx103 = { 0 };
const SongHeader sfx104 = { 0 };
const SongHeader sfx105 = { 0 };
const SongHeader sfx106 = { 0 };
const SongHeader sfx107 = { 0 };
const SongHeader sfx108 = { 0 };
const SongHeader sfx109 = { 0 };
const SongHeader sfx10A = { 0 };
const SongHeader sfx10B = { 0 };
const SongHeader sfx10D = { 0 };
const SongHeader sfx10E = { 0 };
const SongHeader sfx10F = { 0 };
const SongHeader sfx110 = { 0 };
const SongHeader sfx111 = { 0 };
const SongHeader sfx112 = { 0 };
const SongHeader sfx113 = { 0 };
const SongHeader sfx114 = { 0 };
const SongHeader sfx115 = { 0 };
const SongHeader sfx116 = { 0 };
const SongHeader sfx117 = { 0 };
const SongHeader sfx11C = { 0 };
const SongHeader sfx11D = { 0 };
const SongHeader sfx122 = { 0 };
const SongHeader sfx123 = { 0 };
const SongHeader sfx124 = { 0 };
const SongHeader sfx125 = { 0 };
const SongHeader sfx126 = { 0 };
const SongHeader sfx12A = { 0 };
const SongHeader sfx12B = { 0 };
const SongHeader sfx12C = { 0 };
const SongHeader sfx12D = { 0 };
const SongHeader sfx12E = { 0 };
const SongHeader sfx12F = { 0 };
const SongHeader sfx130 = { 0 };
const SongHeader sfx131 = { 0 };
const SongHeader sfx132 = { 0 };
const SongHeader sfx133 = { 0 };
const SongHeader sfx134 = { 0 };
const SongHeader sfx135 = { 0 };
const SongHeader sfx136 = { 0 };
const SongHeader sfx137 = { 0 };
const SongHeader sfx138 = { 0 };
const SongHeader sfx139 = { 0 };
const SongHeader sfx13A = { 0 };
const SongHeader sfx13B = { 0 };
const SongHeader sfx13C = { 0 };
const SongHeader sfx140 = { 0 };
const SongHeader sfx143 = { 0 };
const SongHeader sfx144 = { 0 };
const SongHeader sfx145 = { 0 };
const SongHeader sfx146 = { 0 };
const SongHeader sfx147 = { 0 };
const SongHeader sfx148 = { 0 };
const SongHeader sfx149 = { 0 };
const SongHeader sfx14A = { 0 };
const SongHeader sfx14B = { 0 };
const SongHeader sfx14C = { 0 };
const SongHeader sfx14D = { 0 };
const SongHeader sfx14E = { 0 };
const SongHeader sfx14F = { 0 };
const SongHeader sfx150 = { 0 };
const SongHeader sfx151 = { 0 };
const SongHeader sfx153 = { 0 };
const SongHeader sfx154 = { 0 };
const SongHeader sfx155 = { 0 };
const SongHeader sfx156 = { 0 };
const SongHeader sfx157 = { 0 };
const SongHeader sfx158 = { 0 };
const SongHeader sfx159 = { 0 };
const SongHeader sfx15A = { 0 };
const SongHeader sfx15B = { 0 };
const SongHeader sfx15C = { 0 };
const SongHeader sfx15D = { 0 };
const SongHeader sfx15E = { 0 };
const SongHeader sfx15F = { 0 };
const SongHeader sfx160 = { 0 };
const SongHeader sfx161 = { 0 };
const SongHeader sfx162 = { 0 };
const SongHeader sfx164 = { 0 };
const SongHeader sfx165 = { 0 };
const SongHeader sfx166 = { 0 };
const SongHeader sfx167 = { 0 };
const SongHeader sfx168 = { 0 };
const SongHeader sfx169 = { 0 };
const SongHeader sfx16A = { 0 };
const SongHeader sfx16C = { 0 };
const SongHeader sfx16D = { 0 };
const SongHeader sfx16E = { 0 };
const SongHeader sfx171 = { 0 };
const SongHeader sfx172 = { 0 };
const SongHeader sfx174 = { 0 };
const SongHeader sfx175 = { 0 };
const SongHeader sfx176 = { 0 };
const SongHeader sfx177 = { 0 };
const SongHeader sfx178 = { 0 };
const SongHeader sfx179 = { 0 };
const SongHeader sfx17A = { 0 };
const SongHeader sfx180 = { 0 };
const SongHeader sfx181 = { 0 };
const SongHeader sfx182 = { 0 };
const SongHeader sfx183 = { 0 };
const SongHeader sfx184 = { 0 };
const SongHeader sfx185 = { 0 };
const SongHeader sfx186 = { 0 };
const SongHeader sfx189 = { 0 };
const SongHeader sfx18A = { 0 };
const SongHeader sfx18B = { 0 };
const SongHeader sfx18C = { 0 };
const SongHeader sfx18D = { 0 };
const SongHeader sfx18E = { 0 };
const SongHeader sfx18F = { 0 };
const SongHeader sfx190 = { 0 };
const SongHeader sfx191 = { 0 };
const SongHeader sfx192 = { 0 };
const SongHeader sfx193 = { 0 };
const SongHeader sfx194 = { 0 };
const SongHeader sfx195 = { 0 };
const SongHeader sfx196 = { 0 };
const SongHeader sfx197 = { 0 };
const SongHeader sfx198 = { 0 };
const SongHeader sfx199 = { 0 };
const SongHeader sfx19A = { 0 };
const SongHeader sfx19B = { 0 };
const SongHeader sfx19C = { 0 };
const SongHeader sfx19D = { 0 };
const SongHeader sfx19E = { 0 };
const SongHeader sfx19F = { 0 };
const SongHeader sfx1A0 = { 0 };
const SongHeader sfx1A1 = { 0 };
const SongHeader sfx1A2 = { 0 };
const SongHeader sfx1A3 = { 0 };
const SongHeader sfx1A4 = { 0 };
const SongHeader sfx1A5 = { 0 };
const SongHeader sfx1A6 = { 0 };
const SongHeader sfx1A7 = { 0 };
const SongHeader sfx1A8 = { 0 };
const SongHeader sfx1A9 = { 0 };
const SongHeader sfx1AA = { 0 };
const SongHeader sfx1AB = { 0 };
const SongHeader sfx1AC = { 0 };
const SongHeader sfx1AD = { 0 };
const SongHeader sfx1AE = { 0 };
const SongHeader sfx1AF = { 0 };
const SongHeader sfx1B0 = { 0 };
const SongHeader sfx1B4 = { 0 };
const SongHeader sfx1B5 = { 0 };
const SongHeader sfx1B6 = { 0 };
const SongHeader sfx1BC = { 0 };
const SongHeader sfx1BD = { 0 };
const SongHeader sfx1BE = { 0 };
const SongHeader sfx1BF = { 0 };
const SongHeader sfx1C0 = { 0 };
const SongHeader sfx1C1 = { 0 };
const SongHeader sfx1C2 = { 0 };
const SongHeader sfx1C3 = { 0 };
const SongHeader sfx1C4 = { 0 };
const SongHeader sfx1C5 = { 0 };
const SongHeader sfx1C6 = { 0 };
const SongHeader sfx1C7 = { 0 };
const SongHeader sfx1C8 = { 0 };
const SongHeader sfx1C9 = { 0 };
const SongHeader sfx1CA = { 0 };
const SongHeader sfx1CB = { 0 };
const SongHeader sfx1CC = { 0 };
const SongHeader sfx1D0 = { 0 };
const SongHeader sfx1D2 = { 0 };
const SongHeader sfx1D3 = { 0 };
const SongHeader sfx1D4 = { 0 };
const SongHeader sfx1D5 = { 0 };
const SongHeader sfx1DB = { 0 };
const SongHeader sfx1DC = { 0 };
const SongHeader sfx1DD = { 0 };
const SongHeader sfx1DE = { 0 };
const SongHeader sfx1DF = { 0 };
const SongHeader sfx1E0 = { 0 };
const SongHeader sfx1E1 = { 0 };
const SongHeader sfx1E2 = { 0 };
const SongHeader sfx1E3 = { 0 };
const SongHeader sfx1E4 = { 0 };
const SongHeader sfx1E5 = { 0 };
const SongHeader sfx1E6 = { 0 };
const SongHeader sfx1E7 = { 0 };
const SongHeader sfx1E8 = { 0 };
const SongHeader sfx1E9 = { 0 };
const SongHeader sfx1EA = { 0 };
const SongHeader sfx1EB = { 0 };
const SongHeader sfx1EC = { 0 };
const SongHeader sfx1ED = { 0 };
const SongHeader sfx1EE = { 0 };
const SongHeader sfx1EF = { 0 };
const SongHeader sfx1F0 = { 0 };
const SongHeader sfx1F1 = { 0 };
const SongHeader sfx1F2 = { 0 };
const SongHeader sfx1F3 = { 0 };
const SongHeader sfx1F4 = { 0 };
const SongHeader sfx1F5 = { 0 };
const SongHeader sfx1F6 = { 0 };
const SongHeader sfx1F7 = { 0 };
const SongHeader sfx1F8 = { 0 };
const SongHeader sfx1F9 = { 0 };
const SongHeader sfx1FA = { 0 };
const SongHeader sfx1FB = { 0 };
const SongHeader sfx1FC = { 0 };
const SongHeader sfx1FD = { 0 };
const SongHeader sfx1FE = { 0 };
const SongHeader sfx1FF = { 0 };
const SongHeader sfx200 = { 0 };
const SongHeader sfx201 = { 0 };
const SongHeader sfx202 = { 0 };
const SongHeader sfx203 = { 0 };
const SongHeader sfx204 = { 0 };
const SongHeader sfx205 = { 0 };
const SongHeader sfx206 = { 0 };
const SongHeader sfx207 = { 0 };
const SongHeader sfx208 = { 0 };
const SongHeader sfx209 = { 0 };
const SongHeader sfx20A = { 0 };
const SongHeader sfx20B = { 0 };
const SongHeader sfx20C = { 0 };
const SongHeader sfx20D = { 0 };
const SongHeader sfx20E = { 0 };
const SongHeader sfx20F = { 0 };
const SongHeader sfx210 = { 0 };
const SongHeader sfx211 = { 0 };
const SongHeader sfx212 = { 0 };
const SongHeader sfx213 = { 0 };
const SongHeader sfx214 = { 0 };
const SongHeader sfx215 = { 0 };
const SongHeader sfx216 = { 0 };
const SongHeader sfx217 = { 0 };
const SongHeader sfx218 = { 0 };
const SongHeader sfx219 = { 0 };
const SongHeader sfx21A = { 0 };
const SongHeader sfx21B = { 0 };
const SongHeader sfx21C = { 0 };
const SongHeader sfx21D = { 0 };
const SongHeader sfx21E = { 0 };
const SongHeader sfx21F = { 0 };
const SongHeader sfx220 = { 0 };
const SongHeader sfx221 = { 0 };
const SongHeader sfx6B = { 0 };
const SongHeader sfx7E = { 0 };
const SongHeader sfx80 = { 0 };
const SongHeader sfx81 = { 0 };
const SongHeader sfx82 = { 0 };
const SongHeader sfx86 = { 0 };
const SongHeader sfx88 = { 0 };
const SongHeader sfx9B = { 0 };
const SongHeader sfx9C = { 0 };
const SongHeader sfx9D = { 0 };
const SongHeader sfx9E = { 0 };
const SongHeader sfx9F = { 0 };
const SongHeader sfxA0 = { 0 };
const SongHeader sfxA8 = { 0 };
const SongHeader sfxA9 = { 0 };
const SongHeader sfxAA = { 0 };
const SongHeader sfxAC = { 0 };
const SongHeader sfxAE = { 0 };
const SongHeader sfxAF = { 0 };
const SongHeader sfxApparate = { 0 };
const SongHeader sfxB0 = { 0 };
const SongHeader sfxB5 = { 0 };
const SongHeader sfxB6 = { 0 };
const SongHeader sfxB7 = { 0 };
const SongHeader sfxB8 = { 0 };
const SongHeader sfxB9 = { 0 };
const SongHeader sfxBA = { 0 };
const SongHeader sfxBB = { 0 };
const SongHeader sfxBC = { 0 };
const SongHeader sfxBD = { 0 };
const SongHeader sfxBE = { 0 };
const SongHeader sfxBF = { 0 };
const SongHeader sfxBarrelEnter = { 0 };
const SongHeader sfxBarrelRelease = { 0 };
const SongHeader sfxBarrelRoll = { 0 };
const SongHeader sfxBarrelRollStop = { 0 };
const SongHeader sfxBeep = { 0 };
const SongHeader sfxBossDie = { 0 };
const SongHeader sfxBossExplode = { 0 };
const SongHeader sfxBossHit = { 0 };
const SongHeader sfxButtonDepress = { 0 };
const SongHeader sfxButtonPress = { 0 };
const SongHeader sfxC0 = { 0 };
const SongHeader sfxC1 = { 0 };
const SongHeader sfxC2 = { 0 };
const SongHeader sfxC3 = { 0 };
const SongHeader sfxC4 = { 0 };
const SongHeader sfxC5 = { 0 };
const SongHeader sfxC6 = { 0 };
const SongHeader sfxC7 = { 0 };
const SongHeader sfxC8 = { 0 };
const SongHeader sfxC9 = { 0 };
const SongHeader sfxCA = { 0 };
const SongHeader sfxCB = { 0 };
const SongHeader sfxCF = { 0 };
const SongHeader sfxChargingUp = { 0 };
const SongHeader sfxChestOpen = { 0 };
const SongHeader sfxCuccoMinigameBell = { 0 };
const SongHeader sfxD0 = { 0 };
const SongHeader sfxD9 = { 0 };
const SongHeader sfxDA = { 0 };
const SongHeader sfxE3 = { 0 };
const SongHeader sfxE4 = { 0 };
const SongHeader sfxEA = { 0 };
const SongHeader sfxEB = { 0 };
const SongHeader sfxEC = { 0 };
const SongHeader sfxED = { 0 };
const SongHeader sfxEE = { 0 };
const SongHeader sfxEF = { 0 };
const SongHeader sfxElementCharge = { 0 };
const SongHeader sfxElementFloat = { 0 };
const SongHeader sfxElementInfuse = { 0 };
const SongHeader sfxElementPlace = { 0 };
const SongHeader sfxEmArmosOn = { 0 };
const SongHeader sfxEmDekuscrubHit = { 0 };
const SongHeader sfxEmMoblinSpear = { 0 };
const SongHeader sfxEvaporate = { 0 };
const SongHeader sfxEzloUi = { 0 };
const SongHeader sfxF0 = { 0 };
const SongHeader sfxF1 = { 0 };
const SongHeader sfxF2 = { 0 };
const SongHeader sfxF3 = { 0 };
const SongHeader sfxF5 = { 0 };
const SongHeader sfxF8 = { 0 };
const SongHeader sfxFA = { 0 };
const SongHeader sfxFB = { 0 };
const SongHeader sfxFC = { 0 };
const SongHeader sfxFF = { 0 };
const SongHeader sfxFallHole = { 0 };
const SongHeader sfxHammer1 = { 0 };
const SongHeader sfxHammer2 = { 0 };
const SongHeader sfxHammer3 = { 0 };
const SongHeader sfxHammer4 = { 0 };
const SongHeader sfxHammer5 = { 0 };
const SongHeader sfxHammer6 = { 0 };
const SongHeader sfxHeartBounce = { 0 };
const SongHeader sfxHeartContainerSpawn = { 0 };
const SongHeader sfxHeartGet = { 0 };
const SongHeader sfxHit = { 0 };
const SongHeader sfxIceBlockMelt = { 0 };
const SongHeader sfxIceBlockSlide = { 0 };
const SongHeader sfxIceBlockStop = { 0 };
const SongHeader sfxItemBombExplode = { 0 };
const SongHeader sfxItemGlovesKnockback = { 0 };
const SongHeader sfxItemLanternOff = { 0 };
const SongHeader sfxItemLanternOn = { 0 };
const SongHeader sfxItemShieldBounce = { 0 };
const SongHeader sfxItemSwordBeam = { 0 };
const SongHeader sfxItemSwordCharge = { 0 };
const SongHeader sfxItemSwordChargeFinish = { 0 };
const SongHeader sfxKeyAppear = { 0 };
const SongHeader sfxLavaTitleFlip = { 0 };
const SongHeader sfxLavaTitleLand = { 0 };
const SongHeader sfxLavaTitleSink = { 0 };
const SongHeader sfxLavaTitleStep = { 0 };
const SongHeader sfxLavaTitleWobble = { 0 };
const SongHeader sfxLowHealth = { 0 };
const SongHeader sfxMenuCancel = { 0 };
const SongHeader sfxMenuError = { 0 };
const SongHeader sfxMetalClink = { 0 };
const SongHeader sfxMinish1 = { 0 };
const SongHeader sfxMinish2 = { 0 };
const SongHeader sfxMinish3 = { 0 };
const SongHeader sfxMinish4 = { 0 };
const SongHeader sfxNearPortal = { 0 };
const SongHeader sfxNone = { 0 };
const SongHeader sfxPlyDie = { 0 };
const SongHeader sfxPlyGrow = { 0 };
const SongHeader sfxPlyJump = { 0 };
const SongHeader sfxPlyLand = { 0 };
const SongHeader sfxPlyLift = { 0 };
const SongHeader sfxPlyShrinking = { 0 };
const SongHeader sfxPlyVo1 = { 0 };
const SongHeader sfxPlyVo2 = { 0 };
const SongHeader sfxPlyVo3 = { 0 };
const SongHeader sfxPlyVo4 = { 0 };
const SongHeader sfxPlyVo5 = { 0 };
const SongHeader sfxPlyVo6 = { 0 };
const SongHeader sfxPlyVo7 = { 0 };
const SongHeader sfxPressurePlate = { 0 };
const SongHeader sfxRemSleep = { 0 };
const SongHeader sfxRupeeBounce = { 0 };
const SongHeader sfxRupeeGet = { 0 };
const SongHeader sfxSecret = { 0 };
const SongHeader sfxSecretBig = { 0 };
const SongHeader sfxSparkles = { 0 };
const SongHeader sfxSpiritsRelease = { 0 };
const SongHeader sfxStairs = { 0 };
const SongHeader sfxStairsAscend = { 0 };
const SongHeader sfxStairsDescend = { 0 };
const SongHeader sfxSummon = { 0 };
const SongHeader sfxTaskComplete = { 0 };
const SongHeader sfxTeleporter = { 0 };
const SongHeader sfxTextboxChoice = { 0 };
const SongHeader sfxTextboxClose = { 0 };
const SongHeader sfxTextboxNext = { 0 };
const SongHeader sfxTextboxOpen = { 0 };
const SongHeader sfxTextboxSelect = { 0 };
const SongHeader sfxTextboxSwap = { 0 };
const SongHeader sfxThudHeavy = { 0 };
const SongHeader sfxToggleDiving = { 0 };
const SongHeader sfxVoBeedle = { 0 };
const SongHeader sfxVoCat = { 0 };
const SongHeader sfxVoCheep = { 0 };
const SongHeader sfxVoCow = { 0 };
const SongHeader sfxVoCucco1 = { 0 };
const SongHeader sfxVoCucco2 = { 0 };
const SongHeader sfxVoCucco3 = { 0 };
const SongHeader sfxVoCucco4 = { 0 };
const SongHeader sfxVoCucco5 = { 0 };
const SongHeader sfxVoCuccoCall = { 0 };
const SongHeader sfxVoDog = { 0 };
const SongHeader sfxVoEpona = { 0 };
const SongHeader sfxVoEzlo1 = { 0 };
const SongHeader sfxVoEzlo2 = { 0 };
const SongHeader sfxVoEzlo3 = { 0 };
const SongHeader sfxVoEzlo4 = { 0 };
const SongHeader sfxVoEzlo5 = { 0 };
const SongHeader sfxVoEzlo6 = { 0 };
const SongHeader sfxVoEzlo7 = { 0 };
const SongHeader sfxVoGoron1 = { 0 };
const SongHeader sfxVoGoron2 = { 0 };
const SongHeader sfxVoGoron3 = { 0 };
const SongHeader sfxVoGoron4 = { 0 };
const SongHeader sfxVoKing1 = { 0 };
const SongHeader sfxVoKing2 = { 0 };
const SongHeader sfxVoKing3 = { 0 };
const SongHeader sfxVoKing4 = { 0 };
const SongHeader sfxVoKing5 = { 0 };
const SongHeader sfxVoSturgeon = { 0 };
const SongHeader sfxVoTingle1 = { 0 };
const SongHeader sfxVoTingle2 = { 0 };
const SongHeader sfxVoZelda1 = { 0 };
const SongHeader sfxVoZelda2 = { 0 };
const SongHeader sfxVoZelda3 = { 0 };
const SongHeader sfxVoZelda4 = { 0 };
const SongHeader sfxVoZelda5 = { 0 };
const SongHeader sfxVoZelda6 = { 0 };
const SongHeader sfxVoZelda7 = { 0 };
const SongHeader sfxWaterSplash = { 0 };
const SongHeader sfxWaterWalk = { 0 };
const SongHeader sfxWind1 = { 0 };
const SongHeader sfxWind2 = { 0 };
const SongHeader sfxWind3 = { 0 };
/* ---- ROM data stub initialization ---- */
#include <stdio.h>
#include <string.h>
#include "port_config.h"
extern u8* gRomData;
extern u32 gRomSize;

#define PORT_DATA_STUB_SIZE 1024

/* Copied ROM entity-list provenance. */
static struct {
    const u8* base;
    u32 size;
} gCopiedRomEntityLists[26];
static size_t gCopiedRomEntityListCount;

int Port_IsCopiedRomEntityData(const void* entityData) {
    uintptr_t p = (uintptr_t)entityData;
    for (size_t i = 0; i < gCopiedRomEntityListCount; i++) {
        uintptr_t base = (uintptr_t)gCopiedRomEntityLists[i].base;
        if (p >= base && p - base < gCopiedRomEntityLists[i].size &&
            (p - base) % sizeof(EntityData) == 0) {
            return 1;
        }
    }
    return 0;
}

void Port_InitDataStubs(void) {
    gCopiedRomEntityListCount = 0;
    if (!gRomData || gRomSize == 0 || !gRomOffsets) {
        fprintf(stderr, "Port_InitDataStubs: ROM not loaded yet!\n");
        return;
    }
    u32 count = 0;
    /* gUnk_080046A4 and gUnk_080047F6 — now provided by src/data/data_080046A4.c */
    /* Hitbox data (gUnk_080FD178 through gUnk_080FD588) now provided by src/data/hitbox.c - no ROM loading needed */
    /* gUnk_0810B6EC — SpriteLoadData* pointer table (Hyrule-Town NPCs), resolve GBA addrs.
     * The table is region-relocated (USA 0x10B6EC, JP 0x10B3B0, EU 0x10AE40); a fixed USA
     * offset on a JP/EU ROM yields all-NULL pointers and a NULL-deref crash on town entry.
     * Source the offset via the region-aware accessor (gen_stubs.py is gone; hand-maintained). */
    {
        extern u32 Port_TownspersonSpriteLoadPtrsOffset(void);
        u32 off = Port_TownspersonSpriteLoadPtrsOffset();
        for (u32 i = 0; i < 21; i++) {
            u32 gba_addr;
            memcpy(&gba_addr, &gRomData[off + i * 4], 4);
            if (gba_addr >= 0x08000000u && gba_addr < 0x08000000u + gRomSize)
                gUnk_0810B6EC[i] = &gRomData[gba_addr - 0x08000000u];
            else
                gUnk_0810B6EC[i] = NULL;
        }
        count++;
    }
    /* gUnk_0810B774 and gUnk_0810B77C: function pointer tables, defined natively in port_linked_stubs.c â€” skip ROM
     * loading */
    /* gUnk_08128A38 and gUnk_08128AD8: defined in figurineMenuData.c â€” skip ROM loading */
    /* gUnk_08128D14, D24, D30: func ptr tables â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128D58: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128DB0: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128DCC: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128E78: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128F1C: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08134FBC..gUnk_0813ADEC (transitions + screen transitions) now provided by src/data/ */
    /* gCollisionMtx — populate the full buffer from ROM.
     * collision.c declares it as `extern ColSettings gCollisionMtx[173*34]`
     * (each ColSettings = 12 bytes).  On GBA, reads go well beyond the 1210
     * bytes at 0x080B7B74 into adjacent ROM data.  Copy the full region so
     * collision handlers with hardcoded indices (like 0x11AA) also work. */
    {
        extern u8 gCollisionMtx[];
        u32 col_rom_off = gRomOffsets->collisionMatrix;
        u32 col_size = 173u * 34u * 12u; /* 70584 bytes */
        if (col_rom_off + col_size <= gRomSize) {
            memcpy(gCollisionMtx, &gRomData[col_rom_off], col_size);
        } else if (gRomSize > col_rom_off) {
            /* Partial copy: fill what we have, zero the rest */
            u32 avail = gRomSize - col_rom_off;
            memcpy(gCollisionMtx, &gRomData[col_rom_off], avail);
            memset(&gCollisionMtx[avail], 0, col_size - avail);
        }
        count++;
    }
    /* Per-room "additional entity list" data — most are dropped from
     * port_asset_index.c and the corresponding port_linked_stubs.c arrays
     * are zero. The C code at sub_StateChange_DeepwoodShrineBoss_Main does
     * `LoadRoomEntityList(&gUnk_additional_a_DeepwoodShrineBoss_Main)` to
     * spawn the heart container + warp after the boss dies, so without this
     * copy the rewards never appear (issue #12). */
    {
        extern EntityData gUnk_additional_a_DeepwoodShrineBoss_Main;
        extern EntityData gUnk_additional_8_MelarisMine_Main;
        extern EntityData gUnk_additional_9_MelarisMine_Main;
        extern EntityData gUnk_additional_8_DeepwoodShrine_StairsToB1;
        extern EntityData gUnk_additional_8_HouseInteriors1_Library1F;
        extern EntityData gUnk_additional_9_HouseInteriors1_Library1F;
        extern EntityData gUnk_additional_8_HyruleCastle_3;
        extern EntityData gUnk_additional_a_CaveOfFlamesBoss_Main;
        extern EntityData gUnk_additional_a_TempleOfDroplets_BigOcto;
        extern EntityData gUnk_additional_8_PalaceOfWinds_GyorgTornado;
        extern EntityData gUnk_additional_9_PalaceOfWinds_GyorgTornado;
        extern EntityData gUnk_additional_c_HouseInteriors2_Romio;
        extern EntityData gUnk_additional_9_HouseInteriors2_Percy;
        extern EntityData gUnk_additional_a_HouseInteriors2_Percy;
        extern EntityData gUnk_additional_8_HouseInteriors3_BorlovEntrance;
        extern EntityData gUnk_additional_9_HouseInteriors3_BorlovEntrance;
        extern EntityData gUnk_additional_a_HouseInteriors3_BorlovEntrance;
        extern EntityData Entities_MinishPaths_MayorsCabin_gUnk_080D6138;
        extern EntityData Entities_HouseInteriors1_Mayor_080D6210;
        extern EntityData UpperInn_Oracles;
        extern EntityData UpperInn_NoFarore;
        extern EntityData UpperInn_NoDin;
        extern EntityData UpperInn_NoNayru;
        extern EntityData UpperInn_Din;
        extern EntityData UpperInn_Nayru;
        extern EntityData UpperInn_Farore;
        /* Retail region offsets. Every size includes the final 16-byte
         * terminator and fits the corresponding ENTITY_DATA_STUB storage.
         * EU/JP were checked against USA entity fields; only embedded script
         * pointers differ. See tools/tests/regional_entity_lists.py. */
        struct PerRoomEntityListInit {
            const char* name;
            u32 usa_offset;
            u32 eu_offset;
            u32 jp_offset;
            u32 size;
            u8* dest;
        };
        struct PerRoomEntityListInit entries[] = {
            { "gUnk_additional_a_DeepwoodShrineBoss_Main", 0xDF94Cu, 0xDF068u, 0xDF6BCu, 0x30u,
              (u8*)&gUnk_additional_a_DeepwoodShrineBoss_Main },
            { "gUnk_additional_8_MelarisMine_Main", 0xDD214u, 0xDC950u, 0xDCFA4u, 0x60u,
              (u8*)&gUnk_additional_8_MelarisMine_Main },
            { "gUnk_additional_9_MelarisMine_Main", 0xDD274u, 0xDC9B0u, 0xDD004u, 0x20u,
              (u8*)&gUnk_additional_9_MelarisMine_Main },
            { "gUnk_additional_8_DeepwoodShrine_StairsToB1", 0xDE834u, 0xDDF70u, 0xDE5C4u, 0x30u,
              (u8*)&gUnk_additional_8_DeepwoodShrine_StairsToB1 },
            { "gUnk_additional_8_HouseInteriors1_Library1F", 0xD66F4u, 0xD5E50u, 0xD6494u, 0x20u,
              (u8*)&gUnk_additional_8_HouseInteriors1_Library1F },
            { "gUnk_additional_9_HouseInteriors1_Library1F", 0xD6734u, 0xD5E90u, 0xD64D4u, 0x50u,
              (u8*)&gUnk_additional_9_HouseInteriors1_Library1F },
            { "gUnk_additional_8_HyruleCastle_3", 0xD7690u, 0xD6DECu, 0xD7430u, 0x40u,
              (u8*)&gUnk_additional_8_HyruleCastle_3 },
            { "gUnk_additional_a_CaveOfFlamesBoss_Main", 0xE1814u, 0xE0F30u, 0xE1584u, 0x30u,
              (u8*)&gUnk_additional_a_CaveOfFlamesBoss_Main },
            { "gUnk_additional_a_TempleOfDroplets_BigOcto", 0xE49F4u, 0xE40F0u, 0xE4744u, 0x30u,
              (u8*)&gUnk_additional_a_TempleOfDroplets_BigOcto },
            { "gUnk_additional_8_PalaceOfWinds_GyorgTornado", 0xE72E4u, 0xE69E0u, 0xE7034u, 0x30u,
              (u8*)&gUnk_additional_8_PalaceOfWinds_GyorgTornado },
            { "gUnk_additional_9_PalaceOfWinds_GyorgTornado", 0xE7314u, 0xE6A10u, 0xE7064u, 0x30u,
              (u8*)&gUnk_additional_9_PalaceOfWinds_GyorgTornado },
            { "gUnk_additional_c_HouseInteriors2_Romio", 0xF236Cu, 0xF19A0u, 0xF2094u, 0x20u,
              (u8*)&gUnk_additional_c_HouseInteriors2_Romio },
            { "gUnk_additional_9_HouseInteriors2_Percy", 0xF2718u, 0xF1D4Cu, 0xF2440u, 0x40u,
              (u8*)&gUnk_additional_9_HouseInteriors2_Percy },
            { "gUnk_additional_a_HouseInteriors2_Percy", 0xF2758u, 0xF1D8Cu, 0xF2480u, 0x40u,
              (u8*)&gUnk_additional_a_HouseInteriors2_Percy },
            { "gUnk_additional_8_HouseInteriors3_BorlovEntrance", 0xF5F38u, 0xF54F4u, 0xF5C50u, 0x20u,
              (u8*)&gUnk_additional_8_HouseInteriors3_BorlovEntrance },
            { "gUnk_additional_9_HouseInteriors3_BorlovEntrance", 0xF5F58u, 0xF5514u, 0xF5C70u, 0x20u,
              (u8*)&gUnk_additional_9_HouseInteriors3_BorlovEntrance },
            { "gUnk_additional_a_HouseInteriors3_BorlovEntrance", 0xF5F78u, 0xF5534u, 0xF5C90u, 0x20u,
              (u8*)&gUnk_additional_a_HouseInteriors3_BorlovEntrance },
            { "Entities_MinishPaths_MayorsCabin_gUnk_080D6138", 0xD6138u, 0xD5894u, 0xD5ED8u, 0x60u,
              (u8*)&Entities_MinishPaths_MayorsCabin_gUnk_080D6138 },
            { "Entities_HouseInteriors1_Mayor_080D6210", 0xD6210u, 0xD596Cu, 0xD5FB0u, 0x50u,
              (u8*)&Entities_HouseInteriors1_Mayor_080D6210 },
            { "UpperInn_Oracles", 0xD6BF4u, 0xD6350u, 0xD6994u, 0x40u,
              (u8*)&UpperInn_Oracles },
            { "UpperInn_NoFarore", 0xD6C34u, 0xD6390u, 0xD69D4u, 0x30u,
              (u8*)&UpperInn_NoFarore },
            { "UpperInn_NoDin", 0xD6C64u, 0xD63C0u, 0xD6A04u, 0x30u,
              (u8*)&UpperInn_NoDin },
            { "UpperInn_NoNayru", 0xD6C94u, 0xD63F0u, 0xD6A34u, 0x30u,
              (u8*)&UpperInn_NoNayru },
            { "UpperInn_Din", 0xD6CC4u, 0xD6420u, 0xD6A64u, 0x20u,
              (u8*)&UpperInn_Din },
            { "UpperInn_Nayru", 0xD6CE4u, 0xD6440u, 0xD6A84u, 0x20u,
              (u8*)&UpperInn_Nayru },
            { "UpperInn_Farore", 0xD6D04u, 0xD6460u, 0xD6AA4u, 0x20u,
              (u8*)&UpperInn_Farore },
        };
        _Static_assert(sizeof(entries) / sizeof(entries[0]) <=
                           sizeof(gCopiedRomEntityLists) / sizeof(gCopiedRomEntityLists[0]),
                       "Additional entity-list provenance capacity");
        gCopiedRomEntityListCount = 0;
        for (size_t i = 0; i < sizeof(entries) / sizeof(entries[0]); i++) {
            const struct PerRoomEntityListInit* entry = &entries[i];
            u32 offset = 0;
            switch (gRomRegion) {
                case ROM_REGION_USA: offset = entry->usa_offset; break;
                case ROM_REGION_EU: offset = entry->eu_offset; break;
                case ROM_REGION_JP: offset = entry->jp_offset; break;
                default: break;
            }
            /* A failed load must still be a bounded, empty entity list. */
            memset(entry->dest, 0, entry->size);
            entry->dest[0] = 0xFF;
            if (offset && offset <= gRomSize && entry->size <= gRomSize - offset &&
                entry->size >= sizeof(EntityData) && entry->size % sizeof(EntityData) == 0 &&
                gRomData[offset + entry->size - sizeof(EntityData)] == 0xFF) {
                memcpy(entry->dest, &gRomData[offset], entry->size);
                gCopiedRomEntityLists[gCopiedRomEntityListCount].base = entry->dest;
                gCopiedRomEntityLists[gCopiedRomEntityListCount].size = entry->size;
                gCopiedRomEntityListCount++;
                count++;
            } else {
                fprintf(stderr, "[rom] Invalid additional entity list: %s\n", entry->name);
            }
        }
    }
    fprintf(stderr, "Port_InitDataStubs: initialized %u data stubs from ROM.\n", count);
}
