/* AUTO-GENERATED by tools/generate_flag_remap.py - DO NOT EDIT BY HAND.
 * Per-region local-flag ordinal remap (baseline -> loaded region).
 * Regenerate after editing the flag-bank enums in include/flags.h.
 *
 * EU LocalFlags1: 238 remapped ordinals; USA-only=['KS_A06', 'KS_B18', 'KS_C21', 'KS_C25']; region-only=['HIKYOU_00_T0', 'HIKYOU_00_H00', 'SOUGEN_07_H00']
 * JP LocalFlags1: 238 remapped ordinals; USA-only=['KS_A06', 'KS_B18', 'KS_C21', 'KS_C25']; region-only=['HIKYOU_00_T0', 'HIKYOU_00_H00', 'SOUGEN_07_H00']
 */
#ifndef FLAG_REMAP_GENERATED_H
#define FLAG_REMAP_GENERATED_H

#define FLAG_REMAP_BANK_COUNT 12
#define FLAG_REMAP_TABLE_WIDTH 256

#ifdef __cplusplus
extern "C" {
#endif

/* [bankNumber-1][baselineOrdinal] -> region ordinal. Identity outside
 * the few diverging banks/ordinals; index bankNumber 1..12 as row 0..11. */
extern const unsigned char gFlagRemapEU[12][256];
extern const unsigned char gFlagRemapJP[12][256];

#ifdef __cplusplus
}
#endif

#endif /* FLAG_REMAP_GENERATED_H */
