/**
 * @file port_script_funcs.c
 * AUTO-GENERATED by tools/gen_script_funcs.py — DO NOT EDIT
 *
 * Lookup table mapping GBA function addresses to PC function pointers
 * for script Call/CallWithArg commands.
 */

#include "entity.h"
#include "script.h"
#include "region.h" /* REGION_IS_* for per-region table selection */
#include <stddef.h>

/* Forward declarations of all script-callable functions */
extern void AddInteractableCheckableObject();
extern void Anju_MakeInteractable();
extern void Beedle_ConfirmBuyItem();
extern void Beedle_GetObjectType();
extern void Beedle_IsBottleInInventory();
extern void BladeBrothers_CheckLastSwordMove();
extern void BladeBrothers_GetScroll();
extern void BladeBrothers_LearnSkill();
extern void BladeBrothers_ResetLastSwordMove();
extern void BladeBrothers_StartPlayerDemonstration();
extern void Brocco_MakeInteractable();
extern void Carpenter_MakeInteractable();
extern void CastleMaid_SetDialogFunc();
extern void CheckAnyKeyPressed();
extern void CheckEntityOnScreen();
extern void CheckInteractType();
extern void CheckLastSwordMove();
extern void CheckMessageEqual();
extern void CreateDust();
extern void CreatePlayerExclamationMark();
extern void CreatePlayerQuestionMark();
extern void CreateRepeatedSoundManager();
extern void CuccoMinigame_AdvanceLevel();
extern void CuccoMinigame_Cleanup();
extern void CuccoMinigame_Init();
extern void CuccoMinigame_Results();
extern void CuccoMinigame_TellObjective();
extern void CuccoMinigame_WinItem();
extern void CuccoMinigame_WinRupees();
extern void Dampe_MakeInteractable();
extern void DeleteAllEnemies();
extern void DeleteHitbox();
extern void DeleteNpcRem();
extern void DeleteRepeatedSoundManager();
extern void Din_MakeInteractable();
extern void DisablePauseMenu();
extern void DisablePauseMenuAndPutAwayItems();
extern void DisablePlayerSwimState();
extern void DisableRandomDrops();
extern void DoGravity();
extern void EnablePauseMenu();
extern void EnableRandomDrops();
extern void EquipItem();
extern void Farmers_MakeInteractable();
extern void Farmers_MarkEenieFuserDoner();
extern void Farore_MakeInteractable();
extern void FigurineDevice_LostOrFinishedMessage();
extern void FigurineDevice_NewFigurinesMessage();
extern void FigurineDevice_NoFigurinesLeftMessage();
extern void FigurineDevice_NothingNewToDrawMessage();
extern void FigurineDevice_TryAgainMessage();
extern void ForestMinish_MakeInteractable();
extern void GetConditionSet();
extern void GetRandomInt();
extern void GhostBrothers_MakeInteractable();
extern void GoronMerchant_TryToBuyKinstone();
extern void Goron_MakeInteractable();
extern void Gregal_MakeInteractable();
extern void GuardWithSpear_CheckSwordMoveSpin();
extern void GuardWithSpear_ResetLastSwordMove();
extern void GuardWithSpear_ResetLastSwordMoveIfNotInSwordState();
extern void HurdyGurdyMan_MakeInteractable();
extern void Kid_MakeInteractable();
extern void KingDaltus_MakeInteractable();
extern void LoadMenu();
extern void MakeCheckableObjectInteractable();
extern void MakeInteractableAsMinish();
extern void MakePedestalInteractable();
extern void Mama_MakeInteractable();
extern void MarkFuserDone();
extern void MayorHagen_MakeInteractable();
extern void Melari_MakeInteractable();
extern void MinisterPotho_MakeInteractable();
extern void MountainMinish_MakeInteractable();
extern void Mutoh_MakeInteractable();
extern void NPC4E_ChangeInteractableHitbox();
extern void NPC4E_DoScreenTransition();
extern void NPC4E_IsEveryPinwheelActivated();
extern void NPC4E_IsKinstoneFused();
extern void NPC4E_MakeFuserInteractable();
extern void NPC4E_RestoreEquippedItems();
extern void NPC4E_SaveEquippedItems();
extern void NPC4E_SetPinwheelFlag();
extern void Nayru_MakeInteractable();
extern void Percy_MakeInteractable();
extern void Pina_MakeInteractable();
extern void PlayerDropHeldObject();
extern void PlayerSetNormalAndCollide();
extern void Postman_MakeInteractable();
extern void PutItemAnySlot();
extern void ReadPlayerAnimationState();
extern void Rem_MakeInteractable();
extern void RemoveAllBakedGoods();
extern void ResetPlayerAnimationAndAction();
extern void ResetPlayerEventPriority();
extern void ResetPlayerFlag();
extern void ScriptCommand_BuyShopItem();
extern void ScriptCommand_CheckShopItemPrice();
extern void ScriptCommand_PlayerDropHeldObject();
extern void ScriptCommand_SaleItemConfirmMessage();
extern void ScriptCommand_SetMessageValue();
extern void SetCollisionLayer1();
extern void SetCollisionLayer2();
extern void SetEntityHeight();
extern void SetPlayerActionNormal();
extern void SetPlayerAnimation2();
extern void SetPlayerCollisionLayer1();
extern void SetPlayerEventPriority();
extern void SetPlayerFlag();
extern void SetPlayerIFrames();
extern void SetPlayerMacro();
extern void SetPlayerPos();
extern void SetPriorityHighest();
extern void SetPriorityMessage();
extern void SetPriorityPlayerEvent();
extern void SetSpriteOffset();
extern void Simon_CreateChest();
extern void SittingPersion_ShowDialogue();
extern void SittingPerson_MakeInteractable();
extern void Smith_ChangeInteractableHitbox();
extern void Smith_MakeInteractable();
extern void StartDarkNutTimer();
extern void Sturgeon_MakeInteractable();
extern void Teachers_MakeInteractable();
extern void TingleSiblings_MakeInteractable();
extern void TownMinish_MakeInteractable();
extern void Townsperson_MakeInteractable();
extern void UpdatePlayerSkills();
extern void Vaati_Apparate();
extern void Vaati_Evaporate();
extern void WaitForAnimDone();
extern void WaitForCameraTouchRoomBorder();
extern void WaitForPlayerAnim();
extern void WaitForPlayerIdle();
extern void WaitForPlayerMacro();
extern void WaitForPlayerNormal();
extern void WaitForPlayerNormalOrTalkEzlo();
extern void WindTribespeople_MakeInteractable();
extern void Windcrest_ChangeInteractableHitbox();
extern void Windcrest_Unlock();
extern void nullsub_527();
extern void script_ModBombs();
extern void sub_08046078();
extern void sub_0804BCDC();
extern void sub_0804BF38();
extern void sub_0804D7EC();
extern void sub_0804D810();
extern void sub_0804E864();
extern void sub_0804F6A8();
extern void sub_0804F6C8();
extern void sub_0804F6E8();
extern void sub_0804F724();
extern void sub_0804F760();
extern void sub_0804F79C();
extern void sub_0804F808();
extern void sub_0804F830();
extern void sub_0804F854();
extern void sub_0804F89C();
extern void sub_0804F8E0();
extern void sub_0804F928();
extern void sub_0804F944();
extern void sub_0804F960();
extern void sub_0804F994();
extern void sub_0804F9C8();
extern void sub_08053250();
extern void sub_08053634();
extern void sub_08053648();
extern void sub_0805367C();
extern void sub_0805368C();
extern void sub_080536A8();
extern void sub_080536B8();
extern void sub_08053B3C();
extern void sub_08053BE8();
extern void sub_08053C84();
extern void sub_08054968();
extern void sub_08054EB8();
extern void sub_08054EFC();
extern void sub_08054F64();
extern void sub_0806014C();
extern void sub_08060158();
extern void sub_08060208();
extern void sub_0806021C();
extern void sub_0806025C();
extern void sub_08060270();
extern void sub_080602BC();
extern void sub_08060318();
extern void sub_08060340();
extern void sub_08060700();
extern void sub_0806075C();
extern void sub_0806076C();
extern void sub_080608E4();
extern void sub_08061E90();
extern void sub_08061F94();
extern void sub_08061FB0();
extern void sub_08061FB8();
extern void sub_08061FD8();
extern void sub_08061FE4();
extern void sub_08061FF4();
extern void sub_0806200C(); /* #152: cat-person CALL_FUNC dialog target (bestiary line) */
extern void sub_08062048();
extern void sub_08062500();
extern void sub_0806265C();
extern void sub_08062698();
extern void sub_080626AC();
extern void sub_080626C0();
extern void sub_08062788();
extern void sub_080627E8();
extern void sub_08062948();
extern void sub_08062CBC();
extern void sub_08062D18();
extern void sub_08062E14();
extern void sub_08062EDC();
extern void sub_0806305C();
extern void sub_080630A4();
extern void sub_080636D8();
extern void sub_08063850();
extern void sub_08063874();
extern void sub_08063C14();
extern void sub_08063C2C();
extern void sub_08063C44();
extern void sub_08063C5C();
extern void sub_08063C74();
extern void sub_08063C90();
extern void sub_08064050();
extern void sub_0806407C();
extern void sub_08064180();
extern void sub_08064198();
extern void sub_080642B8();
extern void sub_080643D8();
extern void sub_08064428();
extern void sub_080646A4();
extern void sub_08064CD8();
extern void sub_08064D08();
extern void sub_08064D10();
extern void sub_08064F28();
extern void sub_08065370();
extern void sub_080654DC();
extern void sub_080654EC();
extern void sub_080654FC();
extern void sub_08065528();
extern void sub_08065780();
extern void sub_08065914();
extern void sub_08065CCC();
extern void sub_08065F64();
extern void sub_0806622C();
extern void sub_08066258();
extern void sub_0806673C();
extern void sub_08066904();
extern void sub_08066D04();
extern void sub_08066D14();
extern void sub_08066D4C();
extern void sub_08066E08();
extern void sub_08066E20();
extern void sub_08066E38();
extern void sub_08066E50();
extern void sub_08066E68();
extern void sub_08066E80();
extern void sub_08066F94();
extern void sub_08066FB8();
extern void sub_080670B4();
extern void sub_080670E4();
extern void sub_080672B0();
extern void sub_080672C8();
extern void sub_08067304();
extern void sub_08067534();
extern void sub_0806757C();
extern void sub_080675D4();
extern void sub_080676D8();
extern void sub_080676E0();
extern void sub_0806811C();
extern void sub_08068190();
extern void sub_080681D8();
extern void sub_08068910();
extern void sub_08068964();
extern void sub_08068BB4();
extern void sub_08068BD0();
extern void sub_08068C28();
extern void sub_08068C8C();
extern void sub_08068CA0();
extern void sub_08068CFC();
extern void sub_08068DB8();
extern void sub_08068DD0();
extern void sub_08068DE8();
extern void sub_08068E00();
extern void sub_08068E18();
extern void sub_08068E30();
extern void sub_08068E48();
extern void sub_08068E60();
extern void sub_08068E78();
extern void sub_08068F00();
extern void sub_08068F14();
extern void sub_08068F3C();
extern void sub_0806948C();
extern void sub_080694D8();
extern void sub_080694EC();
extern void sub_08069660();
extern void sub_08069684();
extern void sub_080696B0();
extern void sub_08069888();
extern void sub_0806991C();
extern void sub_080699AC();
extern void sub_08069A3C();
extern void sub_08069A60();
extern void sub_08069A84();
extern void sub_08069AA8();
extern void sub_08069ACC();
extern void sub_08069EE8();
extern void sub_0806A958();
extern void sub_0806A96C();
extern void sub_0806A9B0();
extern void sub_0806A9E8();
extern void sub_0806AA10();
extern void sub_0806AA18();
extern void sub_0806AA50();
extern void sub_0806AB74();
extern void sub_0806AED8();
extern void sub_0806AEE4();
extern void sub_0806AF60();
extern void sub_0806AF70();
extern void sub_0806AF78();
extern void sub_0806AFE8();
extern void sub_0806B260();
extern void sub_0806B2B4();
extern void sub_0806B4F0();
extern void sub_0806BA34();
extern void sub_0806BB1C();
extern void sub_0806BB7C();
extern void sub_0806BBB0();
extern void sub_0806BC94();
extern void sub_0806BCB8();
extern void sub_0806BCE8();
extern void sub_0806BE84();
extern void sub_0806BEC8();
extern void sub_0806BEFC();
extern void sub_0806BF44();
extern void sub_0806C00C();
extern void sub_0806C028();
extern void sub_0806C038();
extern void sub_0806C09C();
extern void sub_0806C224();
extern void sub_0806C280();
extern void sub_0806C2A0();
extern void sub_0806C4A8();
extern void sub_0806C4DC();
extern void sub_0806C578();
extern void sub_0806C588();
extern void sub_0806C598();
extern void sub_0806C70C();
extern void sub_0806C90C();
extern void sub_0806CA5C();
extern void sub_0806CCB4();
extern void sub_0806CCD0();
extern void sub_0806CCF8();
extern void sub_0806CD04();
extern void sub_0806CD14();
extern void sub_0806CD20();
extern void sub_0806CD30();
extern void sub_0806CD3C();
extern void sub_0806CD4C();
extern void sub_0806CE80();
extern void sub_0806D5D4();
extern void sub_0806D600();
extern void sub_0806D620();
extern void sub_0806D638();
extern void sub_0806D640();
extern void sub_0806D650();
extern void sub_0806D658();
extern void sub_0806D660();
extern void sub_0806D66C();
extern void sub_0806D67C();
extern void sub_0806D6D0();
extern void sub_0806D70C();
extern void sub_0806D74C();
extern void sub_0806D788();
extern void sub_0806D7C4();
extern void sub_0806D804();
extern void sub_0806D858();
extern void sub_0806D8A0();
extern void sub_0806D908();
extern void sub_0806D944();
extern void sub_0806D96C();
extern void sub_0806D9A4();
extern void sub_0806DB84();
extern void sub_0806DC7C();
extern void sub_0806DCA0();
extern void sub_0806DCC0();
extern void sub_0806E140();
extern void sub_0806E1E0();
extern void sub_0806E1FC();
extern void sub_0806E20C();
extern void sub_0806E23C();
extern void sub_0806E250();
extern void sub_0806E2DC();
extern void sub_0806E418();
extern void sub_0806E964();
extern void sub_0806EC38();
extern void sub_0807529C();
extern void sub_080752AC();
extern void sub_0807F1A0();
extern void sub_0807F1C4();
extern void sub_0807F1E8();
extern void sub_0807F210();
extern void sub_0807F36C();
extern void sub_0807F3C8();
extern void sub_0807F3D8();
extern void sub_0807F464();
extern void sub_0807F4F8();
extern void sub_0807F5B0();
extern void sub_0807F650();
extern void sub_0807F680();
extern void sub_0807F6B4();
extern void sub_0807F714();
extern void sub_0807F738();
extern void sub_0807F844();
extern void sub_0807F8E8();
extern void sub_0807F93C();
extern void sub_0807FADC();
extern void sub_0807FB28();
extern void sub_0807FB94(); /* Roll Credits — SetTask(TASK_STAFFROLL) */
extern void sub_0807FBA0();
extern void sub_0807FBB4();
extern void sub_0807FBC4();
extern void sub_0807FBCC();
extern void sub_0807FBD4();
#if !defined(EU) || defined(PC_PORT)
extern void sub_0807FBFC();
#endif
/* sub_0807FC24 is USA/demo-only in the decomp (src/script.c) — absent in EU
 * and JP, where the equivalent lives at a different, unnamed address. */
#if defined(USA) || defined(DEMO_USA) || defined(DEMO_JP) || defined(PC_PORT)
extern void sub_0807FC24();
#endif
extern void sub_0808692C();
extern void sub_080869A4();
extern void sub_080873FC();
extern void sub_08087424();
extern void sub_0808747C();
#if !defined(EU) || defined(PC_PORT)
extern void sub_0808861C();
#endif
/* sub_08088658 (figurine device door-check) is !JP in the decomp — also EU-less. */
#if (!defined(EU) && !defined(JP)) || defined(PC_PORT)
extern void sub_08088658();
#endif
extern void sub_0808D280();
extern void sub_0808D2CC();
extern void sub_08094AE8();
extern void sub_08094B0C();
extern void sub_08094B3C();
extern void sub_08094B6C();
extern void sub_08094B80();
extern void sub_08094B94();
extern void sub_08094BE0();
extern void sub_08094CDC();
extern void sub_08094D10();
extern void sub_08094D34();
extern void sub_08094D70();
extern void sub_08094DD8();
extern void sub_08094E0C();
extern void sub_08094F98();
extern void sub_08095164();
extern void sub_08095244();
extern void sub_08095330();
extern void sub_08095364();
extern void sub_08095420();
extern void sub_0809545C();
extern void sub_0809567C();
extern void sub_08095810();
extern void sub_08095A1C();
extern void sub_08095D54();
extern void sub_08095D8C();
extern void sub_08095E7C();
extern void sub_08095EAC();
extern void sub_08096028();
extern void sub_080960C4();
extern void sub_080961B0();
extern void sub_080962F8();
extern void sub_0809E0A0();
extern void sub_0809E0D4();
extern void sub_080A0464();
extern void sub_080A0B28();
extern void sub_080A1270();
extern void sub_080A1648();
extern void sub_080A169C();

typedef struct {
    u32 gba_addr;
    void (*func)(void);
} ScriptFuncEntry;

static const ScriptFuncEntry sScriptFuncTable[] = {
    { 0x08046079, (void (*)(void))sub_08046078 },
    { 0x0804BCDD, (void (*)(void))sub_0804BCDC },
    { 0x0804BF39, (void (*)(void))sub_0804BF38 },
    { 0x0804D7ED, (void (*)(void))sub_0804D7EC },
    { 0x0804D811, (void (*)(void))sub_0804D810 },
    { 0x0804E865, (void (*)(void))sub_0804E864 },
    { 0x0804F6A9, (void (*)(void))sub_0804F6A8 },
    { 0x0804F6C9, (void (*)(void))sub_0804F6C8 },
    { 0x0804F6E9, (void (*)(void))sub_0804F6E8 },
    { 0x0804F725, (void (*)(void))sub_0804F724 },
    { 0x0804F761, (void (*)(void))sub_0804F760 },
    { 0x0804F79D, (void (*)(void))sub_0804F79C },
    { 0x0804F809, (void (*)(void))sub_0804F808 },
    { 0x0804F831, (void (*)(void))sub_0804F830 },
    { 0x0804F855, (void (*)(void))sub_0804F854 },
    { 0x0804F89D, (void (*)(void))sub_0804F89C },
    { 0x0804F8E1, (void (*)(void))sub_0804F8E0 },
    { 0x0804F929, (void (*)(void))sub_0804F928 },
    { 0x0804F945, (void (*)(void))sub_0804F944 },
    { 0x0804F961, (void (*)(void))sub_0804F960 },
    { 0x0804F995, (void (*)(void))sub_0804F994 },
    { 0x0804F9C9, (void (*)(void))sub_0804F9C8 },
    { 0x08053251, (void (*)(void))sub_08053250 },
    { 0x08053495, (void (*)(void))StartDarkNutTimer },
    { 0x08053635, (void (*)(void))sub_08053634 },
    { 0x08053649, (void (*)(void))sub_08053648 },
    { 0x0805367D, (void (*)(void))sub_0805367C },
    { 0x0805368D, (void (*)(void))sub_0805368C },
    { 0x080536A9, (void (*)(void))sub_080536A8 },
    { 0x080536B9, (void (*)(void))sub_080536B8 },
    { 0x08053B3D, (void (*)(void))sub_08053B3C },
    { 0x08053BE9, (void (*)(void))sub_08053BE8 },
    { 0x08053C85, (void (*)(void))sub_08053C84 },
    { 0x08054565, (void (*)(void))DisableRandomDrops },
    { 0x08054571, (void (*)(void))EnableRandomDrops },
    { 0x08054969, (void (*)(void))sub_08054968 },
    /* HAND-FIX (keep on regenerate): Goron Kinstone wall/sync callbacks
     * (worldEvent17.c) called from script_GoronKinstone / Goron2Kinstone*. */
    { 0x08054EB9, (void (*)(void))sub_08054EB8 },
    { 0x08054EFD, (void (*)(void))sub_08054EFC },
    { 0x08054F65, (void (*)(void))sub_08054F64 },
    { 0x0805DDED, (void (*)(void))CreateRepeatedSoundManager },
    { 0x0805DE19, (void (*)(void))DeleteRepeatedSoundManager },
    { 0x0805E545, (void (*)(void))SetPlayerEventPriority },
    { 0x0805E565, (void (*)(void))ResetPlayerEventPriority },
    { 0x0805EBCD, (void (*)(void))DeleteAllEnemies },
    { 0x08060091, (void (*)(void))ForestMinish_MakeInteractable },
    { 0x0806014D, (void (*)(void))sub_0806014C },
    { 0x08060159, (void (*)(void))sub_08060158 },
    { 0x08060209, (void (*)(void))sub_08060208 },
    { 0x0806021D, (void (*)(void))sub_0806021C },
    { 0x0806025D, (void (*)(void))sub_0806025C },
    { 0x08060271, (void (*)(void))sub_08060270 },
    { 0x080602BD, (void (*)(void))sub_080602BC },
    { 0x0806030D, (void (*)(void))script_ModBombs },
    { 0x08060319, (void (*)(void))sub_08060318 },
    { 0x08060341, (void (*)(void))sub_08060340 },
    { 0x080606C1, (void (*)(void))Postman_MakeInteractable },
    { 0x08060701, (void (*)(void))sub_08060700 },
    { 0x0806075D, (void (*)(void))sub_0806075C },
    { 0x0806076D, (void (*)(void))sub_0806076C },
    { 0x080608E5, (void (*)(void))sub_080608E4 },
    { 0x08061E71, (void (*)(void))Townsperson_MakeInteractable },
    { 0x08061E91, (void (*)(void))sub_08061E90 },
    { 0x08061F95, (void (*)(void))sub_08061F94 },
    { 0x08061FB1, (void (*)(void))sub_08061FB0 },
    { 0x08061FB9, (void (*)(void))sub_08061FB8 },
    { 0x08061FD9, (void (*)(void))sub_08061FD8 },
    { 0x08061FE5, (void (*)(void))sub_08061FE4 },
    { 0x08061FF5, (void (*)(void))sub_08061FF4 },
    { 0x0806200D, (void (*)(void))sub_0806200C },
    { 0x08062049, (void (*)(void))sub_08062048 },
    { 0x08062501, (void (*)(void))sub_08062500 },
    { 0x0806265D, (void (*)(void))sub_0806265C },
    { 0x08062699, (void (*)(void))sub_08062698 },
    { 0x080626AD, (void (*)(void))sub_080626AC },
    { 0x080626C1, (void (*)(void))sub_080626C0 },
    { 0x08062789, (void (*)(void))sub_08062788 },
    { 0x080627E9, (void (*)(void))sub_080627E8 },
    { 0x08062949, (void (*)(void))sub_08062948 },
    { 0x08062A49, (void (*)(void))Kid_MakeInteractable },
    { 0x08062CBD, (void (*)(void))sub_08062CBC },
    { 0x08062D19, (void (*)(void))sub_08062D18 },
    { 0x08062E15, (void (*)(void))sub_08062E14 },
    { 0x08062EB9, (void (*)(void))RemoveAllBakedGoods },
    { 0x08062EDD, (void (*)(void))sub_08062EDC },
    { 0x0806305D, (void (*)(void))sub_0806305C },
    { 0x080630A5, (void (*)(void))sub_080630A4 },
    { 0x080634E5, (void (*)(void))Beedle_GetObjectType },
    { 0x080634ED, (void (*)(void))Beedle_ConfirmBuyItem },
    { 0x08063505, (void (*)(void))Beedle_IsBottleInInventory },
    { 0x080636D9, (void (*)(void))sub_080636D8 },
    { 0x080636F5, (void (*)(void))Brocco_MakeInteractable },
    { 0x08063851, (void (*)(void))sub_08063850 },
    { 0x08063875, (void (*)(void))sub_08063874 },
    { 0x08063945, (void (*)(void))SittingPersion_ShowDialogue },
    { 0x080639D1, (void (*)(void))SittingPerson_MakeInteractable },
    { 0x08063C15, (void (*)(void))sub_08063C14 },
    { 0x08063C2D, (void (*)(void))sub_08063C2C },
    { 0x08063C45, (void (*)(void))sub_08063C44 },
    { 0x08063C5D, (void (*)(void))sub_08063C5C },
    { 0x08063C75, (void (*)(void))sub_08063C74 },
    { 0x08063C91, (void (*)(void))sub_08063C90 },
    { 0x08063CAD, (void (*)(void))Pina_MakeInteractable },
    { 0x08064051, (void (*)(void))sub_08064050 },
    { 0x0806407D, (void (*)(void))sub_0806407C },
    { 0x08064181, (void (*)(void))sub_08064180 },
    { 0x08064199, (void (*)(void))sub_08064198 },
    { 0x080642B9, (void (*)(void))sub_080642B8 },
    { 0x080643D9, (void (*)(void))sub_080643D8 },
    { 0x08064429, (void (*)(void))sub_08064428 },
    { 0x08064471, (void (*)(void))GuardWithSpear_CheckSwordMoveSpin },
    { 0x08064489, (void (*)(void))GuardWithSpear_ResetLastSwordMoveIfNotInSwordState },
    { 0x080644A5, (void (*)(void))GuardWithSpear_ResetLastSwordMove },
    { 0x080644B5, (void (*)(void))CheckLastSwordMove },
    { 0x08064645, (void (*)(void))CastleMaid_SetDialogFunc },
    { 0x080646A5, (void (*)(void))sub_080646A4 },
    { 0x08064829, (void (*)(void))Din_MakeInteractable },
    { 0x08064929, (void (*)(void))Nayru_MakeInteractable },
    { 0x08064A29, (void (*)(void))Farore_MakeInteractable },
    { 0x08064CC1, (void (*)(void))Sturgeon_MakeInteractable },
    { 0x08064CD9, (void (*)(void))sub_08064CD8 },
    { 0x08064D09, (void (*)(void))sub_08064D08 },
    { 0x08064D11, (void (*)(void))sub_08064D10 },
    { 0x08064EA5, (void (*)(void))TingleSiblings_MakeInteractable },
    { 0x08064F29, (void (*)(void))sub_08064F28 },
    { 0x08065371, (void (*)(void))sub_08065370 },
    { 0x080654DD, (void (*)(void))sub_080654DC },
    { 0x080654ED, (void (*)(void))sub_080654EC },
    { 0x080654FD, (void (*)(void))sub_080654FC },
    { 0x08065529, (void (*)(void))sub_08065528 },
    { 0x08065781, (void (*)(void))sub_08065780 },
    { 0x08065915, (void (*)(void))sub_08065914 },
    { 0x08065CCD, (void (*)(void))sub_08065CCC },
    { 0x08065D01, (void (*)(void))GhostBrothers_MakeInteractable },
    { 0x08065F65, (void (*)(void))sub_08065F64 },
    { 0x0806622D, (void (*)(void))sub_0806622C },
    { 0x08066259, (void (*)(void))sub_08066258 },
    { 0x08066275, (void (*)(void))Smith_ChangeInteractableHitbox },
    { 0x08066289, (void (*)(void))Smith_MakeInteractable },
    { 0x0806672D, (void (*)(void))KingDaltus_MakeInteractable },
    { 0x0806673D, (void (*)(void))sub_0806673C },
    { 0x080668F1, (void (*)(void))MinisterPotho_MakeInteractable },
    { 0x08066905, (void (*)(void))sub_08066904 },
    { 0x08066C95, (void (*)(void))Vaati_Apparate },
    { 0x08066CA5, (void (*)(void))Vaati_Evaporate },
    { 0x08066D05, (void (*)(void))sub_08066D04 },
    { 0x08066D15, (void (*)(void))sub_08066D14 },
    { 0x08066D4D, (void (*)(void))sub_08066D4C },
    { 0x08066E09, (void (*)(void))sub_08066E08 },
    { 0x08066E21, (void (*)(void))sub_08066E20 },
    { 0x08066E39, (void (*)(void))sub_08066E38 },
    { 0x08066E51, (void (*)(void))sub_08066E50 },
    { 0x08066E69, (void (*)(void))sub_08066E68 },
    { 0x08066E81, (void (*)(void))sub_08066E80 },
    { 0x08066F95, (void (*)(void))sub_08066F94 },
    { 0x08066FB9, (void (*)(void))sub_08066FB8 },
    { 0x080670B5, (void (*)(void))sub_080670B4 },
    { 0x080670E5, (void (*)(void))sub_080670E4 },
    { 0x08067101, (void (*)(void))Mutoh_MakeInteractable },
    { 0x080672B1, (void (*)(void))sub_080672B0 },
    { 0x080672C9, (void (*)(void))sub_080672C8 },
    { 0x08067305, (void (*)(void))sub_08067304 },
    { 0x08067315, (void (*)(void))Carpenter_MakeInteractable },
    { 0x08067535, (void (*)(void))sub_08067534 },
    { 0x0806757D, (void (*)(void))sub_0806757C },
    { 0x080675D5, (void (*)(void))sub_080675D4 },
    { 0x080676D9, (void (*)(void))sub_080676D8 },
    { 0x080676E1, (void (*)(void))sub_080676E0 },
    { 0x08068105, (void (*)(void))MountainMinish_MakeInteractable },
    { 0x0806811D, (void (*)(void))sub_0806811C },
    { 0x08068191, (void (*)(void))sub_08068190 },
    { 0x080681D9, (void (*)(void))sub_080681D8 },
    { 0x08068885, (void (*)(void))Melari_MakeInteractable },
    { 0x08068911, (void (*)(void))sub_08068910 },
    { 0x08068965, (void (*)(void))sub_08068964 },
    { 0x08068B85, (void (*)(void))BladeBrothers_StartPlayerDemonstration },
    { 0x08068BB5, (void (*)(void))sub_08068BB4 },
    { 0x08068BD1, (void (*)(void))sub_08068BD0 },
    { 0x08068C29, (void (*)(void))sub_08068C28 },
    { 0x08068C6D, (void (*)(void))BladeBrothers_GetScroll },
    { 0x08068C8D, (void (*)(void))sub_08068C8C },
    { 0x08068CA1, (void (*)(void))sub_08068CA0 },
    { 0x08068CFD, (void (*)(void))sub_08068CFC },
    { 0x08068DB9, (void (*)(void))sub_08068DB8 },
    { 0x08068DD1, (void (*)(void))sub_08068DD0 },
    { 0x08068DE9, (void (*)(void))sub_08068DE8 },
    { 0x08068E01, (void (*)(void))sub_08068E00 },
    { 0x08068E19, (void (*)(void))sub_08068E18 },
    { 0x08068E31, (void (*)(void))sub_08068E30 },
    { 0x08068E49, (void (*)(void))sub_08068E48 },
    { 0x08068E61, (void (*)(void))sub_08068E60 },
    { 0x08068E79, (void (*)(void))sub_08068E78 },
    { 0x08068E91, (void (*)(void))BladeBrothers_LearnSkill },
    { 0x08068EB5, (void (*)(void))BladeBrothers_ResetLastSwordMove },
    { 0x08068EC5, (void (*)(void))BladeBrothers_CheckLastSwordMove },
    { 0x08068F01, (void (*)(void))sub_08068F00 },
    { 0x08068F15, (void (*)(void))sub_08068F14 },
    { 0x08068F3D, (void (*)(void))sub_08068F3C },
    { 0x0806948D, (void (*)(void))sub_0806948C },
    { 0x080694B1, (void (*)(void))Goron_MakeInteractable },
    { 0x080694D9, (void (*)(void))sub_080694D8 },
    { 0x080694ED, (void (*)(void))sub_080694EC },
    { 0x08069661, (void (*)(void))sub_08069660 },
    { 0x08069685, (void (*)(void))sub_08069684 },
    { 0x080696B1, (void (*)(void))sub_080696B0 },
    { 0x08069719, (void (*)(void))GoronMerchant_TryToBuyKinstone },
    { 0x08069889, (void (*)(void))sub_08069888 },
    { 0x0806991D, (void (*)(void))sub_0806991C },
    { 0x080699AD, (void (*)(void))sub_080699AC },
    { 0x08069A3D, (void (*)(void))sub_08069A3C },
    { 0x08069A61, (void (*)(void))sub_08069A60 },
    { 0x08069A85, (void (*)(void))sub_08069A84 },
    { 0x08069AA9, (void (*)(void))sub_08069AA8 },
    { 0x08069ACD, (void (*)(void))sub_08069ACC },
    { 0x08069EE9, (void (*)(void))sub_08069EE8 },
    { 0x0806A93D, (void (*)(void))Rem_MakeInteractable },
    { 0x0806A959, (void (*)(void))sub_0806A958 },
    { 0x0806A96D, (void (*)(void))sub_0806A96C },
    { 0x0806A9B1, (void (*)(void))sub_0806A9B0 },
    { 0x0806A9E9, (void (*)(void))sub_0806A9E8 },
    { 0x0806AA11, (void (*)(void))sub_0806AA10 },
    { 0x0806AA19, (void (*)(void))sub_0806AA18 },
    { 0x0806AA51, (void (*)(void))sub_0806AA50 },
    { 0x0806AB75, (void (*)(void))sub_0806AB74 },
    { 0x0806AB9D, (void (*)(void))DeleteNpcRem },
    { 0x0806ADFD, (void (*)(void))TownMinish_MakeInteractable },
    { 0x0806AED9, (void (*)(void))sub_0806AED8 },
    { 0x0806AEE5, (void (*)(void))sub_0806AEE4 },
    { 0x0806AF61, (void (*)(void))sub_0806AF60 },
    { 0x0806AF71, (void (*)(void))sub_0806AF70 },
    { 0x0806AF79, (void (*)(void))sub_0806AF78 },
    { 0x0806AFE9, (void (*)(void))sub_0806AFE8 },
    { 0x0806B261, (void (*)(void))sub_0806B260 },
    { 0x0806B2B5, (void (*)(void))sub_0806B2B4 },
    { 0x0806B4F1, (void (*)(void))sub_0806B4F0 },
    { 0x0806B60D, (void (*)(void))Percy_MakeInteractable },
    { 0x0806BA35, (void (*)(void))sub_0806BA34 },
    { 0x0806BB1D, (void (*)(void))sub_0806BB1C },
    { 0x0806BB7D, (void (*)(void))sub_0806BB7C },
    { 0x0806BBB1, (void (*)(void))sub_0806BBB0 },
    { 0x0806BC95, (void (*)(void))sub_0806BC94 },
    { 0x0806BCB9, (void (*)(void))sub_0806BCB8 },
    { 0x0806BCC1, (void (*)(void))Farmers_MarkEenieFuserDoner },
    { 0x0806BCD5, (void (*)(void))Farmers_MakeInteractable },
    { 0x0806BCE9, (void (*)(void))sub_0806BCE8 },
    { 0x0806BE3D, (void (*)(void))Dampe_MakeInteractable },
    { 0x0806BE85, (void (*)(void))sub_0806BE84 },
    { 0x0806BEC9, (void (*)(void))sub_0806BEC8 },
    { 0x0806BEFD, (void (*)(void))sub_0806BEFC },
    { 0x0806BF45, (void (*)(void))sub_0806BF44 },
    { 0x0806C00D, (void (*)(void))sub_0806C00C },
    { 0x0806C029, (void (*)(void))sub_0806C028 },
    { 0x0806C039, (void (*)(void))sub_0806C038 },
    { 0x0806C09D, (void (*)(void))sub_0806C09C },
    { 0x0806C225, (void (*)(void))sub_0806C224 },
    { 0x0806C23D, (void (*)(void))Simon_CreateChest },
    { 0x0806C281, (void (*)(void))sub_0806C280 },
    { 0x0806C2A1, (void (*)(void))sub_0806C2A0 },
    { 0x0806C355, (void (*)(void))Anju_MakeInteractable },
    { 0x0806C4A9, (void (*)(void))sub_0806C4A8 },
    { 0x0806C4DD, (void (*)(void))sub_0806C4DC },
    { 0x0806C4F9, (void (*)(void))Mama_MakeInteractable },
    { 0x0806C579, (void (*)(void))sub_0806C578 },
    { 0x0806C589, (void (*)(void))sub_0806C588 },
    { 0x0806C599, (void (*)(void))sub_0806C598 },
    { 0x0806C675, (void (*)(void))Teachers_MakeInteractable },
    { 0x0806C70D, (void (*)(void))sub_0806C70C },
    { 0x0806C871, (void (*)(void))WindTribespeople_MakeInteractable },
    { 0x0806C90D, (void (*)(void))sub_0806C90C },
    { 0x0806CA5D, (void (*)(void))sub_0806CA5C },
    { 0x0806CCB5, (void (*)(void))sub_0806CCB4 },
    { 0x0806CCD1, (void (*)(void))sub_0806CCD0 },
    { 0x0806CCF9, (void (*)(void))sub_0806CCF8 },
    { 0x0806CD05, (void (*)(void))sub_0806CD04 },
    { 0x0806CD15, (void (*)(void))sub_0806CD14 },
    { 0x0806CD21, (void (*)(void))sub_0806CD20 },
    { 0x0806CD31, (void (*)(void))sub_0806CD30 },
    { 0x0806CD3D, (void (*)(void))sub_0806CD3C },
    { 0x0806CD4D, (void (*)(void))sub_0806CD4C },
    { 0x0806CD59, (void (*)(void))Gregal_MakeInteractable },
    { 0x0806CE5D, (void (*)(void))MayorHagen_MakeInteractable },
    { 0x0806CE81, (void (*)(void))sub_0806CE80 },
    { 0x0806D5D5, (void (*)(void))sub_0806D5D4 },
    { 0x0806D601, (void (*)(void))sub_0806D600 },
    { 0x0806D621, (void (*)(void))sub_0806D620 },
    { 0x0806D639, (void (*)(void))sub_0806D638 },
    { 0x0806D641, (void (*)(void))sub_0806D640 },
    { 0x0806D651, (void (*)(void))sub_0806D650 },
    { 0x0806D659, (void (*)(void))sub_0806D658 },
    { 0x0806D661, (void (*)(void))sub_0806D660 },
    { 0x0806D66D, (void (*)(void))sub_0806D66C },
    { 0x0806D67D, (void (*)(void))sub_0806D67C },
    { 0x0806D6D1, (void (*)(void))sub_0806D6D0 },
    { 0x0806D70D, (void (*)(void))sub_0806D70C },
    { 0x0806D74D, (void (*)(void))sub_0806D74C },
    { 0x0806D789, (void (*)(void))sub_0806D788 },
    { 0x0806D7C5, (void (*)(void))sub_0806D7C4 },
    { 0x0806D805, (void (*)(void))sub_0806D804 },
    { 0x0806D859, (void (*)(void))sub_0806D858 },
    { 0x0806D8A1, (void (*)(void))sub_0806D8A0 },
    { 0x0806D909, (void (*)(void))sub_0806D908 },
    { 0x0806D945, (void (*)(void))sub_0806D944 },
    { 0x0806D96D, (void (*)(void))sub_0806D96C },
    { 0x0806D9A5, (void (*)(void))sub_0806D9A4 },
    { 0x0806DA05, (void (*)(void))NPC4E_ChangeInteractableHitbox },
    { 0x0806DA1D, (void (*)(void))NPC4E_DoScreenTransition },
    { 0x0806DAAD, (void (*)(void))NPC4E_IsKinstoneFused },
    { 0x0806DAD1, (void (*)(void))NPC4E_MakeFuserInteractable },
    { 0x0806DAE9, (void (*)(void))NPC4E_SetPinwheelFlag },
    { 0x0806DB45, (void (*)(void))NPC4E_IsEveryPinwheelActivated },
    { 0x0806DB85, (void (*)(void))sub_0806DB84 },
    { 0x0806DC3D, (void (*)(void))NPC4E_SaveEquippedItems },
    { 0x0806DC59, (void (*)(void))NPC4E_RestoreEquippedItems },
    { 0x0806DC7D, (void (*)(void))sub_0806DC7C },
    { 0x0806DCA1, (void (*)(void))sub_0806DCA0 },
    { 0x0806DCC1, (void (*)(void))sub_0806DCC0 },
    { 0x0806E141, (void (*)(void))sub_0806E140 },
    { 0x0806E1E1, (void (*)(void))sub_0806E1E0 },
    { 0x0806E1FD, (void (*)(void))sub_0806E1FC },
    { 0x0806E20D, (void (*)(void))sub_0806E20C },
    { 0x0806E23D, (void (*)(void))sub_0806E23C },
    { 0x0806E251, (void (*)(void))sub_0806E250 },
    { 0x0806E2DD, (void (*)(void))sub_0806E2DC },
    { 0x0806E419, (void (*)(void))sub_0806E418 },
    { 0x0806E441, (void (*)(void))HurdyGurdyMan_MakeInteractable },
    { 0x0806E965, (void (*)(void))sub_0806E964 },
    { 0x0806EC39, (void (*)(void))sub_0806EC38 },
    { 0x0806F189, (void (*)(void))MarkFuserDone },
    { 0x0807529D, (void (*)(void))sub_0807529C },
    { 0x080752AD, (void (*)(void))sub_080752AC },
    { 0x080787B5, (void (*)(void))AddInteractableCheckableObject },
    { 0x08079185, (void (*)(void))PlayerDropHeldObject },
    { 0x080791BD, (void (*)(void))SetPlayerActionNormal },
    { 0x080791D1, (void (*)(void))ResetPlayerAnimationAndAction },
    { 0x0807921D, (void (*)(void))PlayerSetNormalAndCollide },
    { 0x0807AEE5, (void (*)(void))UpdatePlayerSkills },
    { 0x0807DF29, (void (*)(void))DisablePauseMenuAndPutAwayItems },
    { 0x0807DF39, (void (*)(void))DisablePauseMenu },
    { 0x0807DF51, (void (*)(void))EnablePauseMenu },
    { 0x0807F0D9, (void (*)(void))CheckAnyKeyPressed },
    { 0x0807F0ED, (void (*)(void))GetRandomInt },
    { 0x0807F159, (void (*)(void))SetCollisionLayer1 },
    { 0x0807F169, (void (*)(void))SetPlayerCollisionLayer1 },
    { 0x0807F181, (void (*)(void))SetCollisionLayer2 },
    { 0x0807F1A1, (void (*)(void))sub_0807F1A0 },
    { 0x0807F1C5, (void (*)(void))sub_0807F1C4 },
    { 0x0807F1E9, (void (*)(void))sub_0807F1E8 },
    { 0x0807F211, (void (*)(void))sub_0807F210 },
    { 0x0807F239, (void (*)(void))SetPlayerAnimation2 },
    { 0x0807F245, (void (*)(void))EquipItem },
    { 0x0807F29D, (void (*)(void))SetPlayerMacro },
    { 0x0807F2A9, (void (*)(void))WaitForPlayerMacro },
    { 0x0807F2D5, (void (*)(void))WaitForAnimDone },
    { 0x0807F305, (void (*)(void))WaitForPlayerAnim },
    { 0x0807F339, (void (*)(void))DeleteHitbox },
    { 0x0807F349, (void (*)(void))SetPriorityMessage },
    { 0x0807F355, (void (*)(void))SetPriorityPlayerEvent },
    { 0x0807F361, (void (*)(void))SetPriorityHighest },
    { 0x0807F36D, (void (*)(void))sub_0807F36C },
    { 0x0807F3C9, (void (*)(void))sub_0807F3C8 },
    { 0x0807F3D9, (void (*)(void))sub_0807F3D8 },
    { 0x0807F3F9, (void (*)(void))CreatePlayerExclamationMark },
    { 0x0807F40D, (void (*)(void))CreatePlayerQuestionMark },
    { 0x0807F421, (void (*)(void))LoadMenu },
    { 0x0807F435, (void (*)(void))CheckInteractType },
    { 0x0807F465, (void (*)(void))sub_0807F464 },
    { 0x0807F4F9, (void (*)(void))sub_0807F4F8 },
    { 0x0807F585, (void (*)(void))ReadPlayerAnimationState },
    { 0x0807F595, (void (*)(void))WaitForPlayerIdle },
    { 0x0807F5B1, (void (*)(void))sub_0807F5B0 },
    { 0x0807F5C1, (void (*)(void))WaitForCameraTouchRoomBorder },
    { 0x0807F651, (void (*)(void))sub_0807F650 },
    { 0x0807F681, (void (*)(void))sub_0807F680 },
    { 0x0807F6B5, (void (*)(void))sub_0807F6B4 },
    { 0x0807F6E9, (void (*)(void))SetPlayerFlag },
    { 0x0807F6F9, (void (*)(void))ResetPlayerFlag },
    { 0x0807F715, (void (*)(void))sub_0807F714 },
    { 0x0807F739, (void (*)(void))sub_0807F738 },
    { 0x0807F75D, (void (*)(void))SetPlayerPos },
    { 0x0807F77D, (void (*)(void))GetConditionSet },
    { 0x0807F78D, (void (*)(void))ScriptCommand_SaleItemConfirmMessage },
    { 0x0807F7C5, (void (*)(void))ScriptCommand_CheckShopItemPrice },
    { 0x0807F801, (void (*)(void))ScriptCommand_BuyShopItem },
    { 0x0807F83D, (void (*)(void))ScriptCommand_PlayerDropHeldObject },
    { 0x0807F845, (void (*)(void))sub_0807F844 },
    { 0x0807F855, (void (*)(void))ScriptCommand_SetMessageValue },
    { 0x0807F8BD, (void (*)(void))CheckEntityOnScreen },
    { 0x0807F8D1, (void (*)(void))DoGravity },
    { 0x0807F8E9, (void (*)(void))sub_0807F8E8 },
    { 0x0807F919, (void (*)(void))PutItemAnySlot },
    { 0x0807F925, (void (*)(void))MakeInteractableAsMinish },
    { 0x0807F92D, (void (*)(void))MakePedestalInteractable },
    { 0x0807F935, (void (*)(void))MakeCheckableObjectInteractable },
    { 0x0807F93D, (void (*)(void))sub_0807F93C },
    { 0x0807F971, (void (*)(void))CheckMessageEqual },
    { 0x0807F98D, (void (*)(void))SetEntityHeight },
    { 0x0807F995, (void (*)(void))SetSpriteOffset },
    { 0x0807F9A5, (void (*)(void))WaitForPlayerNormal },
    { 0x0807FA41, (void (*)(void))WaitForPlayerNormalOrTalkEzlo },
    { 0x0807FADD, (void (*)(void))sub_0807FADC },
    { 0x0807FB29, (void (*)(void))sub_0807FB28 },
    { 0x0807FB65, (void (*)(void))SetPlayerIFrames },
    { 0x0807FB75, (void (*)(void))DisablePlayerSwimState },
    { 0x0807FB95, (void (*)(void))sub_0807FB94 },
    { 0x0807FBA1, (void (*)(void))sub_0807FBA0 },
    { 0x0807FBB5, (void (*)(void))sub_0807FBB4 },
    { 0x0807FBC5, (void (*)(void))sub_0807FBC4 },
    { 0x0807FBCD, (void (*)(void))sub_0807FBCC },
    { 0x0807FBD5, (void (*)(void))sub_0807FBD4 },
#if !defined(EU) || defined(PC_PORT)
    { 0x0807FBFD, (void (*)(void))sub_0807FBFC },
#endif
#if defined(USA) || defined(DEMO_USA) || defined(DEMO_JP) || defined(PC_PORT)
    { 0x0807FC25, (void (*)(void))sub_0807FC24 },
#endif
    { 0x0808692D, (void (*)(void))sub_0808692C },
    { 0x080869A5, (void (*)(void))sub_080869A4 },
    { 0x080873FD, (void (*)(void))sub_080873FC },
    { 0x08087425, (void (*)(void))sub_08087424 },
    { 0x0808747D, (void (*)(void))sub_0808747C },
    { 0x08088479, (void (*)(void))FigurineDevice_NoFigurinesLeftMessage },
    { 0x08088505, (void (*)(void))FigurineDevice_NothingNewToDrawMessage },
    { 0x08088545, (void (*)(void))FigurineDevice_NewFigurinesMessage },
    { 0x08088575, (void (*)(void))FigurineDevice_TryAgainMessage },
    { 0x080885B1, (void (*)(void))FigurineDevice_LostOrFinishedMessage },
#if !defined(EU) || defined(PC_PORT)
    { 0x0808861D, (void (*)(void))sub_0808861C },
#endif
#if (!defined(EU) && !defined(JP)) || defined(PC_PORT)
    { 0x08088659, (void (*)(void))sub_08088658 },
#endif

    { 0x0808D281, (void (*)(void))sub_0808D280 },
    { 0x0808D2CD, (void (*)(void))sub_0808D2CC },
    { 0x08094AE9, (void (*)(void))sub_08094AE8 },
    { 0x08094B0D, (void (*)(void))sub_08094B0C },
    { 0x08094B3D, (void (*)(void))sub_08094B3C },
    { 0x08094B6D, (void (*)(void))sub_08094B6C },
    { 0x08094B81, (void (*)(void))sub_08094B80 },
    { 0x08094B95, (void (*)(void))sub_08094B94 },
    { 0x08094BE1, (void (*)(void))sub_08094BE0 },
    { 0x08094CDD, (void (*)(void))sub_08094CDC },
    { 0x08094D11, (void (*)(void))sub_08094D10 },
    { 0x08094D35, (void (*)(void))sub_08094D34 },
    { 0x08094D71, (void (*)(void))sub_08094D70 },
    { 0x08094DD9, (void (*)(void))sub_08094DD8 },
    { 0x08094E0D, (void (*)(void))sub_08094E0C },
    { 0x08094F99, (void (*)(void))sub_08094F98 },
    { 0x08095165, (void (*)(void))sub_08095164 },
    { 0x08095245, (void (*)(void))sub_08095244 },
    { 0x08095331, (void (*)(void))sub_08095330 },
    { 0x08095365, (void (*)(void))sub_08095364 },
    { 0x08095421, (void (*)(void))sub_08095420 },
    { 0x08095459, (void (*)(void))nullsub_527 },
    { 0x0809545D, (void (*)(void))sub_0809545C },
    { 0x0809567D, (void (*)(void))sub_0809567C },
    { 0x08095811, (void (*)(void))sub_08095810 },
    { 0x08095A1D, (void (*)(void))sub_08095A1C },
    { 0x08095D55, (void (*)(void))sub_08095D54 },
    { 0x08095D8D, (void (*)(void))sub_08095D8C },
    { 0x08095E7D, (void (*)(void))sub_08095E7C },
    { 0x08095EAD, (void (*)(void))sub_08095EAC },
    { 0x08096029, (void (*)(void))sub_08096028 },
    { 0x080960C5, (void (*)(void))sub_080960C4 },
    { 0x080961B1, (void (*)(void))sub_080961B0 },
    { 0x080962F9, (void (*)(void))sub_080962F8 },
    { 0x0809E0A1, (void (*)(void))sub_0809E0A0 },
    { 0x0809E0D5, (void (*)(void))sub_0809E0D4 },
    { 0x080A0465, (void (*)(void))sub_080A0464 },
    { 0x080A0B29, (void (*)(void))sub_080A0B28 },
    { 0x080A1271, (void (*)(void))sub_080A1270 },
    { 0x080A1389, (void (*)(void))CuccoMinigame_Cleanup },
    { 0x080A13B5, (void (*)(void))CuccoMinigame_Results },
    { 0x080A13E9, (void (*)(void))CuccoMinigame_WinItem },
    { 0x080A1461, (void (*)(void))CuccoMinigame_WinRupees },
    { 0x080A14A9, (void (*)(void))CuccoMinigame_AdvanceLevel },
    { 0x080A1551, (void (*)(void))CuccoMinigame_Init },
    { 0x080A1609, (void (*)(void))CuccoMinigame_TellObjective },
    { 0x080A1649, (void (*)(void))sub_080A1648 },
    { 0x080A169D, (void (*)(void))sub_080A169C },
    { 0x080A2125, (void (*)(void))Windcrest_ChangeInteractableHitbox },
    { 0x080A2139, (void (*)(void))Windcrest_Unlock },
    { 0x080A29BD, (void (*)(void))CreateDust },
};

#define SCRIPT_FUNC_TABLE_SIZE (sizeof(sScriptFuncTable) / sizeof(sScriptFuncTable[0]))

#if defined(MULTI_REGION)
/* Per-region script-func tables for the fat binary. Same native functions as the
 * baseline (USA) table, but keyed by each region's RETAIL Thumb addresses, derived
 * by exact symbol lookup in the matching upstream zeldaret/tmc maps (see
 * docs/MULTI_REGION.md). Funcs absent from a region's map (version-exclusive) are
 * omitted there. All referenced funcs are defined in the USA-baseline compile. */
static const ScriptFuncEntry sScriptFuncTable_EU[] = {
    { 0x08045E85, (void (*)(void))sub_08046078 },
    { 0x0804B9A9, (void (*)(void))sub_0804BCDC },
    { 0x0804BC05, (void (*)(void))sub_0804BF38 },
    { 0x0804D4B9, (void (*)(void))sub_0804D7EC },
    { 0x0804D4DD, (void (*)(void))sub_0804D810 },
    { 0x0804E4FD, (void (*)(void))sub_0804E864 },
    { 0x0804F2F5, (void (*)(void))sub_0804F6A8 },
    { 0x0804F315, (void (*)(void))sub_0804F6C8 },
    { 0x0804F335, (void (*)(void))sub_0804F6E8 },
    { 0x0804F371, (void (*)(void))sub_0804F724 },
    { 0x0804F3AD, (void (*)(void))sub_0804F760 },
    { 0x0804F3E9, (void (*)(void))sub_0804F79C },
    { 0x0804F455, (void (*)(void))sub_0804F808 },
    { 0x0804F47D, (void (*)(void))sub_0804F830 },
    { 0x0804F4A1, (void (*)(void))sub_0804F854 },
    { 0x0804F4E9, (void (*)(void))sub_0804F89C },
    { 0x0804F52D, (void (*)(void))sub_0804F8E0 },
    { 0x0804F575, (void (*)(void))sub_0804F928 },
    { 0x0804F591, (void (*)(void))sub_0804F944 },
    { 0x0804F5AD, (void (*)(void))sub_0804F960 },
    { 0x0804F5E1, (void (*)(void))sub_0804F994 },
    { 0x0804F615, (void (*)(void))sub_0804F9C8 },
    { 0x08052DE9, (void (*)(void))sub_08053250 },
    { 0x0805302D, (void (*)(void))StartDarkNutTimer },
    { 0x080531CD, (void (*)(void))sub_08053634 },
    { 0x080531E1, (void (*)(void))sub_08053648 },
    { 0x08053215, (void (*)(void))sub_0805367C },
    { 0x08053225, (void (*)(void))sub_0805368C },
    { 0x08053241, (void (*)(void))sub_080536A8 },
    { 0x08053251, (void (*)(void))sub_080536B8 },
    { 0x080536D5, (void (*)(void))sub_08053B3C },
    { 0x08053781, (void (*)(void))sub_08053BE8 },
    { 0x0805381D, (void (*)(void))sub_08053C84 },
    { 0x080540FD, (void (*)(void))DisableRandomDrops },
    { 0x08054109, (void (*)(void))EnableRandomDrops },
    { 0x080544E9, (void (*)(void))sub_08054968 },
    /* HAND-FIX (keep on regenerate): Goron Kinstone callbacks, eu.map. */
    { 0x08054A39, (void (*)(void))sub_08054EB8 },
    { 0x08054A7D, (void (*)(void))sub_08054EFC },
    { 0x08054AE5, (void (*)(void))sub_08054F64 },
    { 0x0805D889, (void (*)(void))CreateRepeatedSoundManager },
    { 0x0805D8B5, (void (*)(void))DeleteRepeatedSoundManager },
    { 0x0805DFCD, (void (*)(void))SetPlayerEventPriority },
    { 0x0805DFED, (void (*)(void))ResetPlayerEventPriority },
    { 0x0805E655, (void (*)(void))DeleteAllEnemies },
    { 0x0805FB19, (void (*)(void))ForestMinish_MakeInteractable },
    { 0x0805FBD5, (void (*)(void))sub_0806014C },
    { 0x0805FBE1, (void (*)(void))sub_08060158 },
    { 0x0805FC91, (void (*)(void))sub_08060208 },
    { 0x0805FCA5, (void (*)(void))sub_0806021C },
    { 0x0805FCE5, (void (*)(void))sub_0806025C },
    { 0x0805FCF9, (void (*)(void))sub_08060270 },
    { 0x0805FD45, (void (*)(void))sub_080602BC },
    { 0x0805FD95, (void (*)(void))script_ModBombs },
    { 0x0805FDA1, (void (*)(void))sub_08060318 },
    { 0x0805FDC9, (void (*)(void))sub_08060340 },
    { 0x08060149, (void (*)(void))Postman_MakeInteractable },
    { 0x08060189, (void (*)(void))sub_08060700 },
    { 0x080601E5, (void (*)(void))sub_0806075C },
    { 0x080601F5, (void (*)(void))sub_0806076C },
    { 0x0806036D, (void (*)(void))sub_080608E4 },
    { 0x080618F9, (void (*)(void))Townsperson_MakeInteractable },
    { 0x08061919, (void (*)(void))sub_08061E90 },
    { 0x08061A1D, (void (*)(void))sub_08061F94 },
    { 0x08061A39, (void (*)(void))sub_08061FB0 },
    { 0x08061A41, (void (*)(void))sub_08061FB8 },
    { 0x08061A61, (void (*)(void))sub_08061FD8 },
    { 0x08061A6D, (void (*)(void))sub_08061FE4 },
    { 0x08061A7D, (void (*)(void))sub_08061FF4 },
    { 0x08061A95, (void (*)(void))sub_0806200C },
    { 0x08061AD1, (void (*)(void))sub_08062048 },
    { 0x08061F89, (void (*)(void))sub_08062500 },
    { 0x080620E5, (void (*)(void))sub_0806265C },
    { 0x08062121, (void (*)(void))sub_08062698 },
    { 0x08062135, (void (*)(void))sub_080626AC },
    { 0x08062149, (void (*)(void))sub_080626C0 },
    { 0x08062211, (void (*)(void))sub_08062788 },
    { 0x08062271, (void (*)(void))sub_080627E8 },
    { 0x080623D1, (void (*)(void))sub_08062948 },
    { 0x080624D1, (void (*)(void))Kid_MakeInteractable },
    { 0x08062745, (void (*)(void))sub_08062CBC },
    { 0x080627A1, (void (*)(void))sub_08062D18 },
    { 0x0806289D, (void (*)(void))sub_08062E14 },
    { 0x08062941, (void (*)(void))RemoveAllBakedGoods },
    { 0x08062965, (void (*)(void))sub_08062EDC },
    { 0x08062AE5, (void (*)(void))sub_0806305C },
    { 0x08062B2D, (void (*)(void))sub_080630A4 },
    { 0x08062F6D, (void (*)(void))Beedle_GetObjectType },
    { 0x08062F75, (void (*)(void))Beedle_ConfirmBuyItem },
    { 0x08062F8D, (void (*)(void))Beedle_IsBottleInInventory },
    { 0x08063161, (void (*)(void))sub_080636D8 },
    { 0x0806317D, (void (*)(void))Brocco_MakeInteractable },
    { 0x080632D9, (void (*)(void))sub_08063850 },
    { 0x080632FD, (void (*)(void))sub_08063874 },
    { 0x080633CD, (void (*)(void))SittingPersion_ShowDialogue },
    { 0x08063459, (void (*)(void))SittingPerson_MakeInteractable },
    { 0x0806369D, (void (*)(void))sub_08063C14 },
    { 0x080636B5, (void (*)(void))sub_08063C2C },
    { 0x080636CD, (void (*)(void))sub_08063C44 },
    { 0x080636E5, (void (*)(void))sub_08063C5C },
    { 0x080636FD, (void (*)(void))sub_08063C74 },
    { 0x08063719, (void (*)(void))sub_08063C90 },
    { 0x08063735, (void (*)(void))Pina_MakeInteractable },
    { 0x08063AD9, (void (*)(void))sub_08064050 },
    { 0x08063B05, (void (*)(void))sub_0806407C },
    { 0x08063C09, (void (*)(void))sub_08064180 },
    { 0x08063C21, (void (*)(void))sub_08064198 },
    { 0x08063D41, (void (*)(void))sub_080642B8 },
    { 0x08063E61, (void (*)(void))sub_080643D8 },
    { 0x08063EB1, (void (*)(void))sub_08064428 },
    { 0x08063EF9, (void (*)(void))GuardWithSpear_CheckSwordMoveSpin },
    { 0x08063F11, (void (*)(void))GuardWithSpear_ResetLastSwordMoveIfNotInSwordState },
    { 0x08063F2D, (void (*)(void))GuardWithSpear_ResetLastSwordMove },
    { 0x08063F3D, (void (*)(void))CheckLastSwordMove },
    { 0x080640CD, (void (*)(void))CastleMaid_SetDialogFunc },
    { 0x0806412D, (void (*)(void))sub_080646A4 },
    { 0x080642B1, (void (*)(void))Din_MakeInteractable },
    { 0x080643B1, (void (*)(void))Nayru_MakeInteractable },
    { 0x080644B1, (void (*)(void))Farore_MakeInteractable },
    { 0x08064749, (void (*)(void))Sturgeon_MakeInteractable },
    { 0x08064761, (void (*)(void))sub_08064CD8 },
    { 0x08064791, (void (*)(void))sub_08064D08 },
    { 0x08064799, (void (*)(void))sub_08064D10 },
    { 0x0806492D, (void (*)(void))TingleSiblings_MakeInteractable },
    { 0x080649B1, (void (*)(void))sub_08064F28 },
    { 0x08064DE9, (void (*)(void))sub_08065370 },
    { 0x08064F4D, (void (*)(void))sub_080654DC },
    { 0x08064F5D, (void (*)(void))sub_080654EC },
    { 0x08064F6D, (void (*)(void))sub_080654FC },
    { 0x08064F99, (void (*)(void))sub_08065528 },
    { 0x080651F1, (void (*)(void))sub_08065780 },
    { 0x08065385, (void (*)(void))sub_08065914 },
    { 0x0806573D, (void (*)(void))sub_08065CCC },
    { 0x08065771, (void (*)(void))GhostBrothers_MakeInteractable },
    { 0x080659D5, (void (*)(void))sub_08065F64 },
    { 0x08065C9D, (void (*)(void))sub_0806622C },
    { 0x08065CC9, (void (*)(void))sub_08066258 },
    { 0x08065CE5, (void (*)(void))Smith_ChangeInteractableHitbox },
    { 0x08065CF9, (void (*)(void))Smith_MakeInteractable },
    { 0x0806619D, (void (*)(void))KingDaltus_MakeInteractable },
    { 0x080661AD, (void (*)(void))sub_0806673C },
    { 0x08066361, (void (*)(void))MinisterPotho_MakeInteractable },
    { 0x08066375, (void (*)(void))sub_08066904 },
    { 0x08066705, (void (*)(void))Vaati_Apparate },
    { 0x08066715, (void (*)(void))Vaati_Evaporate },
    { 0x08066775, (void (*)(void))sub_08066D04 },
    { 0x08066785, (void (*)(void))sub_08066D14 },
    { 0x080667BD, (void (*)(void))sub_08066D4C },
    { 0x08066879, (void (*)(void))sub_08066E08 },
    { 0x08066891, (void (*)(void))sub_08066E20 },
    { 0x080668A9, (void (*)(void))sub_08066E38 },
    { 0x080668C1, (void (*)(void))sub_08066E50 },
    { 0x080668D9, (void (*)(void))sub_08066E68 },
    { 0x080668F1, (void (*)(void))sub_08066E80 },
    { 0x08066A05, (void (*)(void))sub_08066F94 },
    { 0x08066A29, (void (*)(void))sub_08066FB8 },
    { 0x08066B25, (void (*)(void))sub_080670B4 },
    { 0x08066B55, (void (*)(void))sub_080670E4 },
    { 0x08066B71, (void (*)(void))Mutoh_MakeInteractable },
    { 0x08066D21, (void (*)(void))sub_080672B0 },
    { 0x08066D39, (void (*)(void))sub_080672C8 },
    { 0x08066D75, (void (*)(void))sub_08067304 },
    { 0x08066D85, (void (*)(void))Carpenter_MakeInteractable },
    { 0x08066FA5, (void (*)(void))sub_08067534 },
    { 0x08066FED, (void (*)(void))sub_0806757C },
    { 0x08067045, (void (*)(void))sub_080675D4 },
    { 0x08067149, (void (*)(void))sub_080676D8 },
    { 0x08067151, (void (*)(void))sub_080676E0 },
    { 0x08067B75, (void (*)(void))MountainMinish_MakeInteractable },
    { 0x08067B8D, (void (*)(void))sub_0806811C },
    { 0x08067C01, (void (*)(void))sub_08068190 },
    { 0x08067C49, (void (*)(void))sub_080681D8 },
    { 0x080682F5, (void (*)(void))Melari_MakeInteractable },
    { 0x08068381, (void (*)(void))sub_08068910 },
    { 0x080683D5, (void (*)(void))sub_08068964 },
    { 0x080685F5, (void (*)(void))BladeBrothers_StartPlayerDemonstration },
    { 0x08068625, (void (*)(void))sub_08068BB4 },
    { 0x08068641, (void (*)(void))sub_08068BD0 },
    { 0x08068699, (void (*)(void))sub_08068C28 },
    { 0x080686DD, (void (*)(void))BladeBrothers_GetScroll },
    { 0x080686FD, (void (*)(void))sub_08068C8C },
    { 0x08068711, (void (*)(void))sub_08068CA0 },
    { 0x0806876D, (void (*)(void))sub_08068CFC },
    { 0x08068829, (void (*)(void))sub_08068DB8 },
    { 0x08068841, (void (*)(void))sub_08068DD0 },
    { 0x08068859, (void (*)(void))sub_08068DE8 },
    { 0x08068871, (void (*)(void))sub_08068E00 },
    { 0x08068889, (void (*)(void))sub_08068E18 },
    { 0x080688A1, (void (*)(void))sub_08068E30 },
    { 0x080688B9, (void (*)(void))sub_08068E48 },
    { 0x080688D1, (void (*)(void))sub_08068E60 },
    { 0x080688E9, (void (*)(void))sub_08068E78 },
    { 0x08068901, (void (*)(void))BladeBrothers_LearnSkill },
    { 0x08068925, (void (*)(void))BladeBrothers_ResetLastSwordMove },
    { 0x08068935, (void (*)(void))BladeBrothers_CheckLastSwordMove },
    { 0x08068971, (void (*)(void))sub_08068F00 },
    { 0x08068985, (void (*)(void))sub_08068F14 },
    { 0x080689AD, (void (*)(void))sub_08068F3C },
    { 0x08068EFD, (void (*)(void))sub_0806948C },
    { 0x08068F21, (void (*)(void))Goron_MakeInteractable },
    { 0x08068F49, (void (*)(void))sub_080694D8 },
    { 0x08068F5D, (void (*)(void))sub_080694EC },
    { 0x080690D1, (void (*)(void))sub_08069660 },
    { 0x080690F5, (void (*)(void))sub_08069684 },
    { 0x08069121, (void (*)(void))sub_080696B0 },
    { 0x08069189, (void (*)(void))GoronMerchant_TryToBuyKinstone },
    { 0x080692F9, (void (*)(void))sub_08069888 },
    { 0x0806938D, (void (*)(void))sub_0806991C },
    { 0x0806941D, (void (*)(void))sub_080699AC },
    { 0x080694AD, (void (*)(void))sub_08069A3C },
    { 0x080694D1, (void (*)(void))sub_08069A60 },
    { 0x080694F5, (void (*)(void))sub_08069A84 },
    { 0x08069519, (void (*)(void))sub_08069AA8 },
    { 0x0806953D, (void (*)(void))sub_08069ACC },
    { 0x08069965, (void (*)(void))sub_08069EE8 },
    { 0x0806A3B9, (void (*)(void))Rem_MakeInteractable },
    { 0x0806A3D5, (void (*)(void))sub_0806A958 },
    { 0x0806A3E9, (void (*)(void))sub_0806A96C },
    { 0x0806A42D, (void (*)(void))sub_0806A9B0 },
    { 0x0806A465, (void (*)(void))sub_0806A9E8 },
    { 0x0806A48D, (void (*)(void))sub_0806AA10 },
    { 0x0806A495, (void (*)(void))sub_0806AA18 },
    { 0x0806A4CD, (void (*)(void))sub_0806AA50 },
    { 0x0806A5F1, (void (*)(void))sub_0806AB74 },
    { 0x0806A619, (void (*)(void))DeleteNpcRem },
    { 0x0806A879, (void (*)(void))TownMinish_MakeInteractable },
    { 0x0806A955, (void (*)(void))sub_0806AED8 },
    { 0x0806A961, (void (*)(void))sub_0806AEE4 },
    { 0x0806A9DD, (void (*)(void))sub_0806AF60 },
    { 0x0806A9ED, (void (*)(void))sub_0806AF70 },
    { 0x0806A9F5, (void (*)(void))sub_0806AF78 },
    { 0x0806AA65, (void (*)(void))sub_0806AFE8 },
    { 0x0806ACDD, (void (*)(void))sub_0806B260 },
    { 0x0806AD31, (void (*)(void))sub_0806B2B4 },
    { 0x0806AF6D, (void (*)(void))sub_0806B4F0 },
    { 0x0806B089, (void (*)(void))Percy_MakeInteractable },
    { 0x0806B4B1, (void (*)(void))sub_0806BA34 },
    { 0x0806B599, (void (*)(void))sub_0806BB1C },
    { 0x0806B5F9, (void (*)(void))sub_0806BB7C },
    { 0x0806B62D, (void (*)(void))sub_0806BBB0 },
    { 0x0806B711, (void (*)(void))sub_0806BC94 },
    { 0x0806B735, (void (*)(void))sub_0806BCB8 },
    { 0x0806B73D, (void (*)(void))Farmers_MarkEenieFuserDoner },
    { 0x0806B751, (void (*)(void))Farmers_MakeInteractable },
    { 0x0806B765, (void (*)(void))sub_0806BCE8 },
    { 0x0806B8B9, (void (*)(void))Dampe_MakeInteractable },
    { 0x0806B901, (void (*)(void))sub_0806BE84 },
    { 0x0806B945, (void (*)(void))sub_0806BEC8 },
    { 0x0806B979, (void (*)(void))sub_0806BEFC },
    { 0x0806B9C1, (void (*)(void))sub_0806BF44 },
    { 0x0806BA89, (void (*)(void))sub_0806C00C },
    { 0x0806BAA5, (void (*)(void))sub_0806C028 },
    { 0x0806BAB5, (void (*)(void))sub_0806C038 },
    { 0x0806BB19, (void (*)(void))sub_0806C09C },
    { 0x0806BC9D, (void (*)(void))sub_0806C224 },
    { 0x0806BCB5, (void (*)(void))Simon_CreateChest },
    { 0x0806BCF9, (void (*)(void))sub_0806C280 },
    { 0x0806BD19, (void (*)(void))sub_0806C2A0 },
    { 0x0806BDCD, (void (*)(void))Anju_MakeInteractable },
    { 0x0806BF21, (void (*)(void))sub_0806C4A8 },
    { 0x0806BF55, (void (*)(void))sub_0806C4DC },
    { 0x0806BF71, (void (*)(void))Mama_MakeInteractable },
    { 0x0806BFF1, (void (*)(void))sub_0806C578 },
    { 0x0806C001, (void (*)(void))sub_0806C588 },
    { 0x0806C011, (void (*)(void))sub_0806C598 },
    { 0x0806C0ED, (void (*)(void))Teachers_MakeInteractable },
    { 0x0806C185, (void (*)(void))sub_0806C70C },
    { 0x0806C2E9, (void (*)(void))WindTribespeople_MakeInteractable },
    { 0x0806C385, (void (*)(void))sub_0806C90C },
    { 0x0806C4D5, (void (*)(void))sub_0806CA5C },
    { 0x0806C72D, (void (*)(void))sub_0806CCB4 },
    { 0x0806C749, (void (*)(void))sub_0806CCD0 },
    { 0x0806C771, (void (*)(void))sub_0806CCF8 },
    { 0x0806C77D, (void (*)(void))sub_0806CD04 },
    { 0x0806C78D, (void (*)(void))sub_0806CD14 },
    { 0x0806C799, (void (*)(void))sub_0806CD20 },
    { 0x0806C7A9, (void (*)(void))sub_0806CD30 },
    { 0x0806C7B5, (void (*)(void))sub_0806CD3C },
    { 0x0806C7C5, (void (*)(void))sub_0806CD4C },
    { 0x0806C7D1, (void (*)(void))Gregal_MakeInteractable },
    { 0x0806C8D5, (void (*)(void))MayorHagen_MakeInteractable },
    { 0x0806C8F9, (void (*)(void))sub_0806CE80 },
    { 0x0806D04D, (void (*)(void))sub_0806D5D4 },
    { 0x0806D079, (void (*)(void))sub_0806D600 },
    { 0x0806D099, (void (*)(void))sub_0806D620 },
    { 0x0806D0B1, (void (*)(void))sub_0806D638 },
    { 0x0806D0B9, (void (*)(void))sub_0806D640 },
    { 0x0806D0C9, (void (*)(void))sub_0806D650 },
    { 0x0806D0D1, (void (*)(void))sub_0806D658 },
    { 0x0806D0D9, (void (*)(void))sub_0806D660 },
    { 0x0806D0E5, (void (*)(void))sub_0806D66C },
    { 0x0806D0F5, (void (*)(void))sub_0806D67C },
    { 0x0806D149, (void (*)(void))sub_0806D6D0 },
    { 0x0806D185, (void (*)(void))sub_0806D70C },
    { 0x0806D1C5, (void (*)(void))sub_0806D74C },
    { 0x0806D201, (void (*)(void))sub_0806D788 },
    { 0x0806D23D, (void (*)(void))sub_0806D7C4 },
    { 0x0806D27D, (void (*)(void))sub_0806D804 },
    { 0x0806D2D1, (void (*)(void))sub_0806D858 },
    { 0x0806D319, (void (*)(void))sub_0806D8A0 },
    { 0x0806D381, (void (*)(void))sub_0806D908 },
    { 0x0806D3BD, (void (*)(void))sub_0806D944 },
    { 0x0806D3E5, (void (*)(void))sub_0806D96C },
    { 0x0806D41D, (void (*)(void))sub_0806D9A4 },
    { 0x0806D47D, (void (*)(void))NPC4E_ChangeInteractableHitbox },
    { 0x0806D495, (void (*)(void))NPC4E_DoScreenTransition },
    { 0x0806D525, (void (*)(void))NPC4E_IsKinstoneFused },
    { 0x0806D549, (void (*)(void))NPC4E_MakeFuserInteractable },
    { 0x0806D561, (void (*)(void))NPC4E_SetPinwheelFlag },
    { 0x0806D5BD, (void (*)(void))NPC4E_IsEveryPinwheelActivated },
    { 0x0806D5FD, (void (*)(void))sub_0806DB84 },
    { 0x0806D6B5, (void (*)(void))NPC4E_SaveEquippedItems },
    { 0x0806D6D1, (void (*)(void))NPC4E_RestoreEquippedItems },
    { 0x0806D6F5, (void (*)(void))sub_0806DC7C },
    { 0x0806D719, (void (*)(void))sub_0806DCA0 },
    { 0x0806D739, (void (*)(void))sub_0806DCC0 },
    { 0x0806DBB9, (void (*)(void))sub_0806E140 },
    { 0x0806DC59, (void (*)(void))sub_0806E1E0 },
    { 0x0806DC75, (void (*)(void))sub_0806E1FC },
    { 0x0806DC85, (void (*)(void))sub_0806E20C },
    { 0x0806DCB5, (void (*)(void))sub_0806E23C },
    { 0x0806DCC9, (void (*)(void))sub_0806E250 },
    { 0x0806DD55, (void (*)(void))sub_0806E2DC },
    { 0x0806DE91, (void (*)(void))sub_0806E418 },
    { 0x0806DEB9, (void (*)(void))HurdyGurdyMan_MakeInteractable },
    { 0x0806E3DD, (void (*)(void))sub_0806E964 },
    { 0x0806E679, (void (*)(void))sub_0806EC38 },
    { 0x0806EBC9, (void (*)(void))MarkFuserDone },
    { 0x08074CD9, (void (*)(void))sub_0807529C },
    { 0x08074CE9, (void (*)(void))sub_080752AC },
    { 0x080781E1, (void (*)(void))AddInteractableCheckableObject },
    { 0x08078BB1, (void (*)(void))PlayerDropHeldObject },
    { 0x08078BE9, (void (*)(void))SetPlayerActionNormal },
    { 0x08078BFD, (void (*)(void))ResetPlayerAnimationAndAction },
    { 0x08078C49, (void (*)(void))PlayerSetNormalAndCollide },
    { 0x0807A911, (void (*)(void))UpdatePlayerSkills },
    { 0x0807D94D, (void (*)(void))DisablePauseMenuAndPutAwayItems },
    { 0x0807D95D, (void (*)(void))DisablePauseMenu },
    { 0x0807D975, (void (*)(void))EnablePauseMenu },
    { 0x0807EAFD, (void (*)(void))CheckAnyKeyPressed },
    { 0x0807EB11, (void (*)(void))GetRandomInt },
    { 0x0807EB7D, (void (*)(void))SetCollisionLayer1 },
    { 0x0807EB8D, (void (*)(void))SetPlayerCollisionLayer1 },
    { 0x0807EBA5, (void (*)(void))SetCollisionLayer2 },
    { 0x0807EBC5, (void (*)(void))sub_0807F1A0 },
    { 0x0807EBE9, (void (*)(void))sub_0807F1C4 },
    { 0x0807EC0D, (void (*)(void))sub_0807F1E8 },
    { 0x0807EC35, (void (*)(void))sub_0807F210 },
    { 0x0807EC5D, (void (*)(void))SetPlayerAnimation2 },
    { 0x0807EC69, (void (*)(void))EquipItem },
    { 0x0807ECC1, (void (*)(void))SetPlayerMacro },
    { 0x0807ECCD, (void (*)(void))WaitForPlayerMacro },
    { 0x0807ECF9, (void (*)(void))WaitForAnimDone },
    { 0x0807ED29, (void (*)(void))WaitForPlayerAnim },
    { 0x0807ED5D, (void (*)(void))DeleteHitbox },
    { 0x0807ED6D, (void (*)(void))SetPriorityMessage },
    { 0x0807ED79, (void (*)(void))SetPriorityPlayerEvent },
    { 0x0807ED85, (void (*)(void))SetPriorityHighest },
    { 0x0807ED91, (void (*)(void))sub_0807F36C },
    { 0x0807EDED, (void (*)(void))sub_0807F3C8 },
    { 0x0807EDFD, (void (*)(void))sub_0807F3D8 },
    { 0x0807EE1D, (void (*)(void))CreatePlayerExclamationMark },
    { 0x0807EE31, (void (*)(void))CreatePlayerQuestionMark },
    { 0x0807EE45, (void (*)(void))LoadMenu },
    { 0x0807EE59, (void (*)(void))CheckInteractType },
    { 0x0807EE89, (void (*)(void))sub_0807F464 },
    { 0x0807EF1D, (void (*)(void))sub_0807F4F8 },
    { 0x0807EFA9, (void (*)(void))ReadPlayerAnimationState },
    { 0x0807EFB9, (void (*)(void))WaitForPlayerIdle },
    { 0x0807EFD5, (void (*)(void))sub_0807F5B0 },
    { 0x0807EFE5, (void (*)(void))WaitForCameraTouchRoomBorder },
    { 0x0807F075, (void (*)(void))sub_0807F650 },
    { 0x0807F0A5, (void (*)(void))sub_0807F680 },
    { 0x0807F0D9, (void (*)(void))sub_0807F6B4 },
    { 0x0807F10D, (void (*)(void))SetPlayerFlag },
    { 0x0807F11D, (void (*)(void))ResetPlayerFlag },
    { 0x0807F139, (void (*)(void))sub_0807F714 },
    { 0x0807F15D, (void (*)(void))sub_0807F738 },
    { 0x0807F181, (void (*)(void))SetPlayerPos },
    { 0x0807F1A1, (void (*)(void))GetConditionSet },
    { 0x0807F1B1, (void (*)(void))ScriptCommand_SaleItemConfirmMessage },
    { 0x0807F1E9, (void (*)(void))ScriptCommand_CheckShopItemPrice },
    { 0x0807F225, (void (*)(void))ScriptCommand_BuyShopItem },
    { 0x0807F261, (void (*)(void))ScriptCommand_PlayerDropHeldObject },
    { 0x0807F269, (void (*)(void))sub_0807F844 },
    { 0x0807F279, (void (*)(void))ScriptCommand_SetMessageValue },
    { 0x0807F2E1, (void (*)(void))CheckEntityOnScreen },
    { 0x0807F2F5, (void (*)(void))DoGravity },
    { 0x0807F30D, (void (*)(void))sub_0807F8E8 },
    { 0x0807F33D, (void (*)(void))PutItemAnySlot },
    { 0x0807F349, (void (*)(void))MakeInteractableAsMinish },
    { 0x0807F351, (void (*)(void))MakePedestalInteractable },
    { 0x0807F359, (void (*)(void))MakeCheckableObjectInteractable },
    { 0x0807F361, (void (*)(void))sub_0807F93C },
    { 0x0807F395, (void (*)(void))CheckMessageEqual },
    { 0x0807F3B1, (void (*)(void))SetEntityHeight },
    { 0x0807F3B9, (void (*)(void))SetSpriteOffset },
    { 0x0807F3C9, (void (*)(void))WaitForPlayerNormal },
    { 0x0807F465, (void (*)(void))WaitForPlayerNormalOrTalkEzlo },
    { 0x0807F501, (void (*)(void))sub_0807FADC },
    { 0x0807F54D, (void (*)(void))sub_0807FB28 },
    { 0x0807F589, (void (*)(void))SetPlayerIFrames },
    { 0x0807F599, (void (*)(void))DisablePlayerSwimState },
    { 0x0807F5B9, (void (*)(void))sub_0807FB94 },
    { 0x0807F5C5, (void (*)(void))sub_0807FBA0 },
    { 0x0807F5D9, (void (*)(void))sub_0807FBB4 },
    { 0x0807F5E9, (void (*)(void))sub_0807FBC4 },
    { 0x0807F5F1, (void (*)(void))sub_0807FBCC },
    { 0x0807F5F9, (void (*)(void))sub_0807FBD4 },
    { 0x08086309, (void (*)(void))sub_0808692C },
    { 0x08086381, (void (*)(void))sub_080869A4 },
    { 0x08086DD9, (void (*)(void))sub_080873FC },
    { 0x08086E01, (void (*)(void))sub_08087424 },
    { 0x08086E59, (void (*)(void))sub_0808747C },
    { 0x08087E05, (void (*)(void))FigurineDevice_NoFigurinesLeftMessage },
    { 0x08087E85, (void (*)(void))FigurineDevice_NothingNewToDrawMessage },
    { 0x08087EC5, (void (*)(void))FigurineDevice_NewFigurinesMessage },
    { 0x08087EF5, (void (*)(void))FigurineDevice_TryAgainMessage },
    { 0x08087F31, (void (*)(void))FigurineDevice_LostOrFinishedMessage },
    { 0x0808CB79, (void (*)(void))sub_0808D280 },
    { 0x0808CBC5, (void (*)(void))sub_0808D2CC },
    { 0x080943BD, (void (*)(void))sub_08094AE8 },
    { 0x080943E1, (void (*)(void))sub_08094B0C },
    { 0x08094411, (void (*)(void))sub_08094B3C },
    { 0x08094441, (void (*)(void))sub_08094B6C },
    { 0x08094455, (void (*)(void))sub_08094B80 },
    { 0x08094469, (void (*)(void))sub_08094B94 },
    { 0x080944B5, (void (*)(void))sub_08094BE0 },
    { 0x080945B1, (void (*)(void))sub_08094CDC },
    { 0x080945E5, (void (*)(void))sub_08094D10 },
    { 0x08094609, (void (*)(void))sub_08094D34 },
    { 0x08094645, (void (*)(void))sub_08094D70 },
    { 0x080946AD, (void (*)(void))sub_08094DD8 },
    { 0x080946E1, (void (*)(void))sub_08094E0C },
    { 0x0809486D, (void (*)(void))sub_08094F98 },
    { 0x080949F5, (void (*)(void))sub_08095164 },
    { 0x08094AD5, (void (*)(void))sub_08095244 },
    { 0x08094BC1, (void (*)(void))sub_08095330 },
    { 0x08094BF5, (void (*)(void))sub_08095364 },
    { 0x08094CB1, (void (*)(void))sub_08095420 },
    { 0x08094CE9, (void (*)(void))nullsub_527 },
    { 0x08094CED, (void (*)(void))sub_0809545C },
    { 0x08094F0D, (void (*)(void))sub_0809567C },
    { 0x080950A1, (void (*)(void))sub_08095810 },
    { 0x080952AD, (void (*)(void))sub_08095A1C },
    { 0x080955E5, (void (*)(void))sub_08095D54 },
    { 0x0809561D, (void (*)(void))sub_08095D8C },
    { 0x0809570D, (void (*)(void))sub_08095E7C },
    { 0x0809573D, (void (*)(void))sub_08095EAC },
    { 0x080958B9, (void (*)(void))sub_08096028 },
    { 0x08095955, (void (*)(void))sub_080960C4 },
    { 0x08095A41, (void (*)(void))sub_080961B0 },
    { 0x08095B89, (void (*)(void))sub_080962F8 },
    { 0x0809D931, (void (*)(void))sub_0809E0A0 },
    { 0x0809D965, (void (*)(void))sub_0809E0D4 },
    { 0x0809FCB9, (void (*)(void))sub_080A0464 },
    { 0x080A037D, (void (*)(void))sub_080A0B28 },
    { 0x080A0AAD, (void (*)(void))sub_080A1270 },
    { 0x080A0BC5, (void (*)(void))CuccoMinigame_Cleanup },
    { 0x080A0BF1, (void (*)(void))CuccoMinigame_Results },
    { 0x080A0C25, (void (*)(void))CuccoMinigame_WinItem },
    { 0x080A0C9D, (void (*)(void))CuccoMinigame_WinRupees },
    { 0x080A0CE5, (void (*)(void))CuccoMinigame_AdvanceLevel },
    { 0x080A0D8D, (void (*)(void))CuccoMinigame_Init },
    { 0x080A0E45, (void (*)(void))CuccoMinigame_TellObjective },
    { 0x080A0E85, (void (*)(void))sub_080A1648 },
    { 0x080A0ED9, (void (*)(void))sub_080A169C },
    { 0x080A1941, (void (*)(void))Windcrest_ChangeInteractableHitbox },
    { 0x080A1955, (void (*)(void))Windcrest_Unlock },
    /* HAND-FIX (keep on regenerate): the decomp names this CreateDust but the
     * retail maps name it CreateDeathFx (EU 0x080A21D8, JP 0x080A2774) — the
     * generator's name match drops it, killing dust/poof FX on EU/JP. */
    { 0x080A21D9, (void (*)(void))CreateDust },
};
#define SSCRIPTFUNCTABLE_EU_SIZE (sizeof(sScriptFuncTable_EU) / sizeof(sScriptFuncTable_EU[0]))

static const ScriptFuncEntry sScriptFuncTable_JP[] = {
    { 0x08045F75, (void (*)(void))sub_08046078 },
    { 0x0804BBC5, (void (*)(void))sub_0804BCDC },
    { 0x0804BE21, (void (*)(void))sub_0804BF38 },
    { 0x0804D6D5, (void (*)(void))sub_0804D7EC },
    { 0x0804D6F9, (void (*)(void))sub_0804D810 },
    { 0x0804E741, (void (*)(void))sub_0804E864 },
    { 0x0804F585, (void (*)(void))sub_0804F6A8 },
    { 0x0804F5A5, (void (*)(void))sub_0804F6C8 },
    { 0x0804F5C5, (void (*)(void))sub_0804F6E8 },
    { 0x0804F601, (void (*)(void))sub_0804F724 },
    { 0x0804F63D, (void (*)(void))sub_0804F760 },
    { 0x0804F679, (void (*)(void))sub_0804F79C },
    { 0x0804F6E5, (void (*)(void))sub_0804F808 },
    { 0x0804F70D, (void (*)(void))sub_0804F830 },
    { 0x0804F731, (void (*)(void))sub_0804F854 },
    { 0x0804F779, (void (*)(void))sub_0804F89C },
    { 0x0804F7BD, (void (*)(void))sub_0804F8E0 },
    { 0x0804F805, (void (*)(void))sub_0804F928 },
    { 0x0804F821, (void (*)(void))sub_0804F944 },
    { 0x0804F83D, (void (*)(void))sub_0804F960 },
    { 0x0804F871, (void (*)(void))sub_0804F994 },
    { 0x0804F8A5, (void (*)(void))sub_0804F9C8 },
    { 0x080530D5, (void (*)(void))sub_08053250 },
    { 0x08053319, (void (*)(void))StartDarkNutTimer },
    { 0x080534B9, (void (*)(void))sub_08053634 },
    { 0x080534CD, (void (*)(void))sub_08053648 },
    { 0x08053501, (void (*)(void))sub_0805367C },
    { 0x08053511, (void (*)(void))sub_0805368C },
    { 0x0805352D, (void (*)(void))sub_080536A8 },
    { 0x0805353D, (void (*)(void))sub_080536B8 },
    { 0x080539C1, (void (*)(void))sub_08053B3C },
    { 0x08053A6D, (void (*)(void))sub_08053BE8 },
    { 0x08053B09, (void (*)(void))sub_08053C84 },
    { 0x080543E9, (void (*)(void))DisableRandomDrops },
    { 0x080543F5, (void (*)(void))EnableRandomDrops },
    { 0x080547ED, (void (*)(void))sub_08054968 },
    /* HAND-FIX (keep on regenerate): Goron Kinstone callbacks, jp.map. */
    { 0x08054D3D, (void (*)(void))sub_08054EB8 },
    { 0x08054D81, (void (*)(void))sub_08054EFC },
    { 0x08054DE9, (void (*)(void))sub_08054F64 },
    { 0x0805DC41, (void (*)(void))CreateRepeatedSoundManager },
    { 0x0805DC6D, (void (*)(void))DeleteRepeatedSoundManager },
    { 0x0805E385, (void (*)(void))SetPlayerEventPriority },
    { 0x0805E3A5, (void (*)(void))ResetPlayerEventPriority },
    { 0x0805EA0D, (void (*)(void))DeleteAllEnemies },
    { 0x0805FED1, (void (*)(void))ForestMinish_MakeInteractable },
    { 0x0805FF8D, (void (*)(void))sub_0806014C },
    { 0x0805FF99, (void (*)(void))sub_08060158 },
    { 0x08060049, (void (*)(void))sub_08060208 },
    { 0x0806005D, (void (*)(void))sub_0806021C },
    { 0x0806009D, (void (*)(void))sub_0806025C },
    { 0x080600B1, (void (*)(void))sub_08060270 },
    { 0x080600FD, (void (*)(void))sub_080602BC },
    { 0x0806014D, (void (*)(void))script_ModBombs },
    { 0x08060159, (void (*)(void))sub_08060318 },
    { 0x08060181, (void (*)(void))sub_08060340 },
    { 0x08060501, (void (*)(void))Postman_MakeInteractable },
    { 0x08060541, (void (*)(void))sub_08060700 },
    { 0x0806059D, (void (*)(void))sub_0806075C },
    { 0x080605AD, (void (*)(void))sub_0806076C },
    { 0x08060725, (void (*)(void))sub_080608E4 },
    { 0x08061CB1, (void (*)(void))Townsperson_MakeInteractable },
    { 0x08061CD1, (void (*)(void))sub_08061E90 },
    { 0x08061DD5, (void (*)(void))sub_08061F94 },
    { 0x08061DF1, (void (*)(void))sub_08061FB0 },
    { 0x08061DF9, (void (*)(void))sub_08061FB8 },
    { 0x08061E19, (void (*)(void))sub_08061FD8 },
    { 0x08061E25, (void (*)(void))sub_08061FE4 },
    { 0x08061E35, (void (*)(void))sub_08061FF4 },
    { 0x08061E4D, (void (*)(void))sub_0806200C },
    { 0x08061E89, (void (*)(void))sub_08062048 },
    { 0x08062341, (void (*)(void))sub_08062500 },
    { 0x0806249D, (void (*)(void))sub_0806265C },
    { 0x080624D9, (void (*)(void))sub_08062698 },
    { 0x080624ED, (void (*)(void))sub_080626AC },
    { 0x08062501, (void (*)(void))sub_080626C0 },
    { 0x080625C9, (void (*)(void))sub_08062788 },
    { 0x08062629, (void (*)(void))sub_080627E8 },
    { 0x08062789, (void (*)(void))sub_08062948 },
    { 0x08062889, (void (*)(void))Kid_MakeInteractable },
    { 0x08062AFD, (void (*)(void))sub_08062CBC },
    { 0x08062B59, (void (*)(void))sub_08062D18 },
    { 0x08062C55, (void (*)(void))sub_08062E14 },
    { 0x08062CF9, (void (*)(void))RemoveAllBakedGoods },
    { 0x08062D1D, (void (*)(void))sub_08062EDC },
    { 0x08062E9D, (void (*)(void))sub_0806305C },
    { 0x08062EE5, (void (*)(void))sub_080630A4 },
    { 0x08063325, (void (*)(void))Beedle_GetObjectType },
    { 0x0806332D, (void (*)(void))Beedle_ConfirmBuyItem },
    { 0x08063345, (void (*)(void))Beedle_IsBottleInInventory },
    { 0x08063519, (void (*)(void))sub_080636D8 },
    { 0x08063535, (void (*)(void))Brocco_MakeInteractable },
    { 0x08063691, (void (*)(void))sub_08063850 },
    { 0x080636B5, (void (*)(void))sub_08063874 },
    { 0x08063785, (void (*)(void))SittingPersion_ShowDialogue },
    { 0x08063811, (void (*)(void))SittingPerson_MakeInteractable },
    { 0x08063A55, (void (*)(void))sub_08063C14 },
    { 0x08063A6D, (void (*)(void))sub_08063C2C },
    { 0x08063A85, (void (*)(void))sub_08063C44 },
    { 0x08063A9D, (void (*)(void))sub_08063C5C },
    { 0x08063AB5, (void (*)(void))sub_08063C74 },
    { 0x08063AD1, (void (*)(void))sub_08063C90 },
    { 0x08063AED, (void (*)(void))Pina_MakeInteractable },
    { 0x08063E91, (void (*)(void))sub_08064050 },
    { 0x08063EBD, (void (*)(void))sub_0806407C },
    { 0x08063FC1, (void (*)(void))sub_08064180 },
    { 0x08063FD9, (void (*)(void))sub_08064198 },
    { 0x080640F9, (void (*)(void))sub_080642B8 },
    { 0x08064219, (void (*)(void))sub_080643D8 },
    { 0x08064269, (void (*)(void))sub_08064428 },
    { 0x080642B1, (void (*)(void))GuardWithSpear_CheckSwordMoveSpin },
    { 0x080642C9, (void (*)(void))GuardWithSpear_ResetLastSwordMoveIfNotInSwordState },
    { 0x080642E5, (void (*)(void))GuardWithSpear_ResetLastSwordMove },
    { 0x080642F5, (void (*)(void))CheckLastSwordMove },
    { 0x08064485, (void (*)(void))CastleMaid_SetDialogFunc },
    { 0x080644E5, (void (*)(void))sub_080646A4 },
    { 0x08064669, (void (*)(void))Din_MakeInteractable },
    { 0x08064769, (void (*)(void))Nayru_MakeInteractable },
    { 0x08064869, (void (*)(void))Farore_MakeInteractable },
    { 0x08064B01, (void (*)(void))Sturgeon_MakeInteractable },
    { 0x08064B19, (void (*)(void))sub_08064CD8 },
    { 0x08064B49, (void (*)(void))sub_08064D08 },
    { 0x08064B51, (void (*)(void))sub_08064D10 },
    { 0x08064CE5, (void (*)(void))TingleSiblings_MakeInteractable },
    { 0x08064D69, (void (*)(void))sub_08064F28 },
    { 0x080651B1, (void (*)(void))sub_08065370 },
    { 0x0806531D, (void (*)(void))sub_080654DC },
    { 0x0806532D, (void (*)(void))sub_080654EC },
    { 0x0806533D, (void (*)(void))sub_080654FC },
    { 0x08065369, (void (*)(void))sub_08065528 },
    { 0x080655C1, (void (*)(void))sub_08065780 },
    { 0x08065755, (void (*)(void))sub_08065914 },
    { 0x08065B0D, (void (*)(void))sub_08065CCC },
    { 0x08065B41, (void (*)(void))GhostBrothers_MakeInteractable },
    { 0x08065DA5, (void (*)(void))sub_08065F64 },
    { 0x0806606D, (void (*)(void))sub_0806622C },
    { 0x08066099, (void (*)(void))sub_08066258 },
    { 0x080660B5, (void (*)(void))Smith_ChangeInteractableHitbox },
    { 0x080660C9, (void (*)(void))Smith_MakeInteractable },
    { 0x0806656D, (void (*)(void))KingDaltus_MakeInteractable },
    { 0x0806657D, (void (*)(void))sub_0806673C },
    { 0x08066731, (void (*)(void))MinisterPotho_MakeInteractable },
    { 0x08066745, (void (*)(void))sub_08066904 },
    { 0x08066AD5, (void (*)(void))Vaati_Apparate },
    { 0x08066AE5, (void (*)(void))Vaati_Evaporate },
    { 0x08066B45, (void (*)(void))sub_08066D04 },
    { 0x08066B55, (void (*)(void))sub_08066D14 },
    { 0x08066B8D, (void (*)(void))sub_08066D4C },
    { 0x08066C49, (void (*)(void))sub_08066E08 },
    { 0x08066C61, (void (*)(void))sub_08066E20 },
    { 0x08066C79, (void (*)(void))sub_08066E38 },
    { 0x08066C91, (void (*)(void))sub_08066E50 },
    { 0x08066CA9, (void (*)(void))sub_08066E68 },
    { 0x08066CC1, (void (*)(void))sub_08066E80 },
    { 0x08066DD5, (void (*)(void))sub_08066F94 },
    { 0x08066DF9, (void (*)(void))sub_08066FB8 },
    { 0x08066EF5, (void (*)(void))sub_080670B4 },
    { 0x08066F25, (void (*)(void))sub_080670E4 },
    { 0x08066F41, (void (*)(void))Mutoh_MakeInteractable },
    { 0x080670F1, (void (*)(void))sub_080672B0 },
    { 0x08067109, (void (*)(void))sub_080672C8 },
    { 0x08067145, (void (*)(void))sub_08067304 },
    { 0x08067155, (void (*)(void))Carpenter_MakeInteractable },
    { 0x08067375, (void (*)(void))sub_08067534 },
    { 0x080673BD, (void (*)(void))sub_0806757C },
    { 0x08067415, (void (*)(void))sub_080675D4 },
    { 0x08067519, (void (*)(void))sub_080676D8 },
    { 0x08067521, (void (*)(void))sub_080676E0 },
    { 0x08067F45, (void (*)(void))MountainMinish_MakeInteractable },
    { 0x08067F5D, (void (*)(void))sub_0806811C },
    { 0x08067FD1, (void (*)(void))sub_08068190 },
    { 0x08068019, (void (*)(void))sub_080681D8 },
    { 0x080686C5, (void (*)(void))Melari_MakeInteractable },
    { 0x08068751, (void (*)(void))sub_08068910 },
    { 0x080687A5, (void (*)(void))sub_08068964 },
    { 0x080689C5, (void (*)(void))BladeBrothers_StartPlayerDemonstration },
    { 0x080689F5, (void (*)(void))sub_08068BB4 },
    { 0x08068A11, (void (*)(void))sub_08068BD0 },
    { 0x08068A69, (void (*)(void))sub_08068C28 },
    { 0x08068AAD, (void (*)(void))BladeBrothers_GetScroll },
    { 0x08068ACD, (void (*)(void))sub_08068C8C },
    { 0x08068AE1, (void (*)(void))sub_08068CA0 },
    { 0x08068B3D, (void (*)(void))sub_08068CFC },
    { 0x08068BF9, (void (*)(void))sub_08068DB8 },
    { 0x08068C11, (void (*)(void))sub_08068DD0 },
    { 0x08068C29, (void (*)(void))sub_08068DE8 },
    { 0x08068C41, (void (*)(void))sub_08068E00 },
    { 0x08068C59, (void (*)(void))sub_08068E18 },
    { 0x08068C71, (void (*)(void))sub_08068E30 },
    { 0x08068C89, (void (*)(void))sub_08068E48 },
    { 0x08068CA1, (void (*)(void))sub_08068E60 },
    { 0x08068CB9, (void (*)(void))sub_08068E78 },
    { 0x08068CD1, (void (*)(void))BladeBrothers_LearnSkill },
    { 0x08068CF5, (void (*)(void))BladeBrothers_ResetLastSwordMove },
    { 0x08068D05, (void (*)(void))BladeBrothers_CheckLastSwordMove },
    { 0x08068D41, (void (*)(void))sub_08068F00 },
    { 0x08068D55, (void (*)(void))sub_08068F14 },
    { 0x08068D7D, (void (*)(void))sub_08068F3C },
    { 0x080692CD, (void (*)(void))sub_0806948C },
    { 0x080692F1, (void (*)(void))Goron_MakeInteractable },
    { 0x08069319, (void (*)(void))sub_080694D8 },
    { 0x0806932D, (void (*)(void))sub_080694EC },
    { 0x080694A1, (void (*)(void))sub_08069660 },
    { 0x080694C5, (void (*)(void))sub_08069684 },
    { 0x080694F1, (void (*)(void))sub_080696B0 },
    { 0x08069559, (void (*)(void))GoronMerchant_TryToBuyKinstone },
    { 0x080696C9, (void (*)(void))sub_08069888 },
    { 0x0806975D, (void (*)(void))sub_0806991C },
    { 0x080697ED, (void (*)(void))sub_080699AC },
    { 0x0806987D, (void (*)(void))sub_08069A3C },
    { 0x080698A1, (void (*)(void))sub_08069A60 },
    { 0x080698C5, (void (*)(void))sub_08069A84 },
    { 0x080698E9, (void (*)(void))sub_08069AA8 },
    { 0x0806990D, (void (*)(void))sub_08069ACC },
    { 0x08069D29, (void (*)(void))sub_08069EE8 },
    { 0x0806A77D, (void (*)(void))Rem_MakeInteractable },
    { 0x0806A799, (void (*)(void))sub_0806A958 },
    { 0x0806A7AD, (void (*)(void))sub_0806A96C },
    { 0x0806A7F1, (void (*)(void))sub_0806A9B0 },
    { 0x0806A829, (void (*)(void))sub_0806A9E8 },
    { 0x0806A851, (void (*)(void))sub_0806AA10 },
    { 0x0806A859, (void (*)(void))sub_0806AA18 },
    { 0x0806A891, (void (*)(void))sub_0806AA50 },
    { 0x0806A9B5, (void (*)(void))sub_0806AB74 },
    { 0x0806A9DD, (void (*)(void))DeleteNpcRem },
    { 0x0806AC3D, (void (*)(void))TownMinish_MakeInteractable },
    { 0x0806AD19, (void (*)(void))sub_0806AED8 },
    { 0x0806AD25, (void (*)(void))sub_0806AEE4 },
    { 0x0806ADA1, (void (*)(void))sub_0806AF60 },
    { 0x0806ADB1, (void (*)(void))sub_0806AF70 },
    { 0x0806ADB9, (void (*)(void))sub_0806AF78 },
    { 0x0806AE29, (void (*)(void))sub_0806AFE8 },
    { 0x0806B0A1, (void (*)(void))sub_0806B260 },
    { 0x0806B0F5, (void (*)(void))sub_0806B2B4 },
    { 0x0806B331, (void (*)(void))sub_0806B4F0 },
    { 0x0806B44D, (void (*)(void))Percy_MakeInteractable },
    { 0x0806B875, (void (*)(void))sub_0806BA34 },
    { 0x0806B95D, (void (*)(void))sub_0806BB1C },
    { 0x0806B9BD, (void (*)(void))sub_0806BB7C },
    { 0x0806B9F1, (void (*)(void))sub_0806BBB0 },
    { 0x0806BAD5, (void (*)(void))sub_0806BC94 },
    { 0x0806BAF9, (void (*)(void))sub_0806BCB8 },
    { 0x0806BB01, (void (*)(void))Farmers_MarkEenieFuserDoner },
    { 0x0806BB15, (void (*)(void))Farmers_MakeInteractable },
    { 0x0806BB29, (void (*)(void))sub_0806BCE8 },
    { 0x0806BC7D, (void (*)(void))Dampe_MakeInteractable },
    { 0x0806BCC5, (void (*)(void))sub_0806BE84 },
    { 0x0806BD09, (void (*)(void))sub_0806BEC8 },
    { 0x0806BD3D, (void (*)(void))sub_0806BEFC },
    { 0x0806BD85, (void (*)(void))sub_0806BF44 },
    { 0x0806BE4D, (void (*)(void))sub_0806C00C },
    { 0x0806BE69, (void (*)(void))sub_0806C028 },
    { 0x0806BE79, (void (*)(void))sub_0806C038 },
    { 0x0806BEDD, (void (*)(void))sub_0806C09C },
    { 0x0806C061, (void (*)(void))sub_0806C224 },
    { 0x0806C079, (void (*)(void))Simon_CreateChest },
    { 0x0806C0BD, (void (*)(void))sub_0806C280 },
    { 0x0806C0DD, (void (*)(void))sub_0806C2A0 },
    { 0x0806C191, (void (*)(void))Anju_MakeInteractable },
    { 0x0806C2E5, (void (*)(void))sub_0806C4A8 },
    { 0x0806C319, (void (*)(void))sub_0806C4DC },
    { 0x0806C335, (void (*)(void))Mama_MakeInteractable },
    { 0x0806C3B5, (void (*)(void))sub_0806C578 },
    { 0x0806C3C5, (void (*)(void))sub_0806C588 },
    { 0x0806C3D5, (void (*)(void))sub_0806C598 },
    { 0x0806C4B1, (void (*)(void))Teachers_MakeInteractable },
    { 0x0806C549, (void (*)(void))sub_0806C70C },
    { 0x0806C6AD, (void (*)(void))WindTribespeople_MakeInteractable },
    { 0x0806C749, (void (*)(void))sub_0806C90C },
    { 0x0806C899, (void (*)(void))sub_0806CA5C },
    { 0x0806CAF1, (void (*)(void))sub_0806CCB4 },
    { 0x0806CB0D, (void (*)(void))sub_0806CCD0 },
    { 0x0806CB35, (void (*)(void))sub_0806CCF8 },
    { 0x0806CB41, (void (*)(void))sub_0806CD04 },
    { 0x0806CB51, (void (*)(void))sub_0806CD14 },
    { 0x0806CB5D, (void (*)(void))sub_0806CD20 },
    { 0x0806CB6D, (void (*)(void))sub_0806CD30 },
    { 0x0806CB79, (void (*)(void))sub_0806CD3C },
    { 0x0806CB89, (void (*)(void))sub_0806CD4C },
    { 0x0806CB95, (void (*)(void))Gregal_MakeInteractable },
    { 0x0806CC99, (void (*)(void))MayorHagen_MakeInteractable },
    { 0x0806CCBD, (void (*)(void))sub_0806CE80 },
    { 0x0806D411, (void (*)(void))sub_0806D5D4 },
    { 0x0806D43D, (void (*)(void))sub_0806D600 },
    { 0x0806D45D, (void (*)(void))sub_0806D620 },
    { 0x0806D475, (void (*)(void))sub_0806D638 },
    { 0x0806D47D, (void (*)(void))sub_0806D640 },
    { 0x0806D48D, (void (*)(void))sub_0806D650 },
    { 0x0806D495, (void (*)(void))sub_0806D658 },
    { 0x0806D49D, (void (*)(void))sub_0806D660 },
    { 0x0806D4A9, (void (*)(void))sub_0806D66C },
    { 0x0806D4B9, (void (*)(void))sub_0806D67C },
    { 0x0806D50D, (void (*)(void))sub_0806D6D0 },
    { 0x0806D549, (void (*)(void))sub_0806D70C },
    { 0x0806D589, (void (*)(void))sub_0806D74C },
    { 0x0806D5C5, (void (*)(void))sub_0806D788 },
    { 0x0806D601, (void (*)(void))sub_0806D7C4 },
    { 0x0806D641, (void (*)(void))sub_0806D804 },
    { 0x0806D695, (void (*)(void))sub_0806D858 },
    { 0x0806D6DD, (void (*)(void))sub_0806D8A0 },
    { 0x0806D745, (void (*)(void))sub_0806D908 },
    { 0x0806D781, (void (*)(void))sub_0806D944 },
    { 0x0806D7A9, (void (*)(void))sub_0806D96C },
    { 0x0806D7E1, (void (*)(void))sub_0806D9A4 },
    { 0x0806D841, (void (*)(void))NPC4E_ChangeInteractableHitbox },
    { 0x0806D859, (void (*)(void))NPC4E_DoScreenTransition },
    { 0x0806D8E9, (void (*)(void))NPC4E_IsKinstoneFused },
    { 0x0806D90D, (void (*)(void))NPC4E_MakeFuserInteractable },
    { 0x0806D925, (void (*)(void))NPC4E_SetPinwheelFlag },
    { 0x0806D981, (void (*)(void))NPC4E_IsEveryPinwheelActivated },
    { 0x0806D9C1, (void (*)(void))sub_0806DB84 },
    { 0x0806DA79, (void (*)(void))NPC4E_SaveEquippedItems },
    { 0x0806DA95, (void (*)(void))NPC4E_RestoreEquippedItems },
    { 0x0806DAB9, (void (*)(void))sub_0806DC7C },
    { 0x0806DADD, (void (*)(void))sub_0806DCA0 },
    { 0x0806DAFD, (void (*)(void))sub_0806DCC0 },
    { 0x0806DF7D, (void (*)(void))sub_0806E140 },
    { 0x0806E01D, (void (*)(void))sub_0806E1E0 },
    { 0x0806E039, (void (*)(void))sub_0806E1FC },
    { 0x0806E049, (void (*)(void))sub_0806E20C },
    { 0x0806E079, (void (*)(void))sub_0806E23C },
    { 0x0806E08D, (void (*)(void))sub_0806E250 },
    { 0x0806E119, (void (*)(void))sub_0806E2DC },
    { 0x0806E255, (void (*)(void))sub_0806E418 },
    { 0x0806E27D, (void (*)(void))HurdyGurdyMan_MakeInteractable },
    { 0x0806E7A1, (void (*)(void))sub_0806E964 },
    { 0x0806EA75, (void (*)(void))sub_0806EC38 },
    { 0x0806EFC5, (void (*)(void))MarkFuserDone },
    { 0x080750D9, (void (*)(void))sub_0807529C },
    { 0x080750E9, (void (*)(void))sub_080752AC },
    { 0x080785F1, (void (*)(void))AddInteractableCheckableObject },
    { 0x08078FC1, (void (*)(void))PlayerDropHeldObject },
    { 0x08078FF9, (void (*)(void))SetPlayerActionNormal },
    { 0x0807900D, (void (*)(void))ResetPlayerAnimationAndAction },
    { 0x08079059, (void (*)(void))PlayerSetNormalAndCollide },
    { 0x0807AD21, (void (*)(void))UpdatePlayerSkills },
    { 0x0807DD65, (void (*)(void))DisablePauseMenuAndPutAwayItems },
    { 0x0807DD75, (void (*)(void))DisablePauseMenu },
    { 0x0807DD8D, (void (*)(void))EnablePauseMenu },
    { 0x0807EF15, (void (*)(void))CheckAnyKeyPressed },
    { 0x0807EF29, (void (*)(void))GetRandomInt },
    { 0x0807EF95, (void (*)(void))SetCollisionLayer1 },
    { 0x0807EFA5, (void (*)(void))SetPlayerCollisionLayer1 },
    { 0x0807EFBD, (void (*)(void))SetCollisionLayer2 },
    { 0x0807EFDD, (void (*)(void))sub_0807F1A0 },
    { 0x0807F001, (void (*)(void))sub_0807F1C4 },
    { 0x0807F025, (void (*)(void))sub_0807F1E8 },
    { 0x0807F04D, (void (*)(void))sub_0807F210 },
    { 0x0807F075, (void (*)(void))SetPlayerAnimation2 },
    { 0x0807F081, (void (*)(void))EquipItem },
    { 0x0807F0D9, (void (*)(void))SetPlayerMacro },
    { 0x0807F0E5, (void (*)(void))WaitForPlayerMacro },
    { 0x0807F111, (void (*)(void))WaitForAnimDone },
    { 0x0807F141, (void (*)(void))WaitForPlayerAnim },
    { 0x0807F175, (void (*)(void))DeleteHitbox },
    { 0x0807F185, (void (*)(void))SetPriorityMessage },
    { 0x0807F191, (void (*)(void))SetPriorityPlayerEvent },
    { 0x0807F19D, (void (*)(void))SetPriorityHighest },
    { 0x0807F1A9, (void (*)(void))sub_0807F36C },
    { 0x0807F205, (void (*)(void))sub_0807F3C8 },
    { 0x0807F215, (void (*)(void))sub_0807F3D8 },
    { 0x0807F235, (void (*)(void))CreatePlayerExclamationMark },
    { 0x0807F249, (void (*)(void))CreatePlayerQuestionMark },
    { 0x0807F25D, (void (*)(void))LoadMenu },
    { 0x0807F271, (void (*)(void))CheckInteractType },
    { 0x0807F2A1, (void (*)(void))sub_0807F464 },
    { 0x0807F335, (void (*)(void))sub_0807F4F8 },
    { 0x0807F3C1, (void (*)(void))ReadPlayerAnimationState },
    { 0x0807F3D1, (void (*)(void))WaitForPlayerIdle },
    { 0x0807F3ED, (void (*)(void))sub_0807F5B0 },
    { 0x0807F3FD, (void (*)(void))WaitForCameraTouchRoomBorder },
    { 0x0807F48D, (void (*)(void))sub_0807F650 },
    { 0x0807F4BD, (void (*)(void))sub_0807F680 },
    { 0x0807F4F1, (void (*)(void))sub_0807F6B4 },
    { 0x0807F525, (void (*)(void))SetPlayerFlag },
    { 0x0807F535, (void (*)(void))ResetPlayerFlag },
    { 0x0807F551, (void (*)(void))sub_0807F714 },
    { 0x0807F575, (void (*)(void))sub_0807F738 },
    { 0x0807F599, (void (*)(void))SetPlayerPos },
    { 0x0807F5B9, (void (*)(void))GetConditionSet },
    { 0x0807F5C9, (void (*)(void))ScriptCommand_SaleItemConfirmMessage },
    { 0x0807F601, (void (*)(void))ScriptCommand_CheckShopItemPrice },
    { 0x0807F63D, (void (*)(void))ScriptCommand_BuyShopItem },
    { 0x0807F679, (void (*)(void))ScriptCommand_PlayerDropHeldObject },
    { 0x0807F681, (void (*)(void))sub_0807F844 },
    { 0x0807F691, (void (*)(void))ScriptCommand_SetMessageValue },
    { 0x0807F6F9, (void (*)(void))CheckEntityOnScreen },
    { 0x0807F70D, (void (*)(void))DoGravity },
    { 0x0807F725, (void (*)(void))sub_0807F8E8 },
    { 0x0807F755, (void (*)(void))PutItemAnySlot },
    { 0x0807F761, (void (*)(void))MakeInteractableAsMinish },
    { 0x0807F769, (void (*)(void))MakePedestalInteractable },
    { 0x0807F771, (void (*)(void))MakeCheckableObjectInteractable },
    { 0x0807F779, (void (*)(void))sub_0807F93C },
    { 0x0807F7AD, (void (*)(void))CheckMessageEqual },
    { 0x0807F7C9, (void (*)(void))SetEntityHeight },
    { 0x0807F7D1, (void (*)(void))SetSpriteOffset },
    { 0x0807F7E1, (void (*)(void))WaitForPlayerNormal },
    { 0x0807F87D, (void (*)(void))WaitForPlayerNormalOrTalkEzlo },
    { 0x0807F919, (void (*)(void))sub_0807FADC },
    { 0x0807F965, (void (*)(void))sub_0807FB28 },
    { 0x0807F9A1, (void (*)(void))SetPlayerIFrames },
    { 0x0807F9B1, (void (*)(void))DisablePlayerSwimState },
    { 0x0807F9D1, (void (*)(void))sub_0807FB94 },
    { 0x0807F9DD, (void (*)(void))sub_0807FBA0 },
    { 0x0807F9F1, (void (*)(void))sub_0807FBB4 },
    { 0x0807FA01, (void (*)(void))sub_0807FBC4 },
    { 0x0807FA09, (void (*)(void))sub_0807FBCC },
    { 0x0807FA11, (void (*)(void))sub_0807FBD4 },
    { 0x0807FA39, (void (*)(void))sub_0807FBFC },
    { 0x0808674D, (void (*)(void))sub_0808692C },
    { 0x080867C5, (void (*)(void))sub_080869A4 },
    { 0x0808721D, (void (*)(void))sub_080873FC },
    { 0x08087245, (void (*)(void))sub_08087424 },
    { 0x0808729D, (void (*)(void))sub_0808747C },
    { 0x0808827D, (void (*)(void))FigurineDevice_NoFigurinesLeftMessage },
    { 0x08088309, (void (*)(void))FigurineDevice_NothingNewToDrawMessage },
    { 0x08088349, (void (*)(void))FigurineDevice_NewFigurinesMessage },
    { 0x08088379, (void (*)(void))FigurineDevice_TryAgainMessage },
    { 0x080883B5, (void (*)(void))FigurineDevice_LostOrFinishedMessage },
    { 0x08088421, (void (*)(void))sub_0808861C },
    { 0x0808D049, (void (*)(void))sub_0808D280 },
    { 0x0808D095, (void (*)(void))sub_0808D2CC },
    { 0x080948B1, (void (*)(void))sub_08094AE8 },
    { 0x080948D5, (void (*)(void))sub_08094B0C },
    { 0x08094905, (void (*)(void))sub_08094B3C },
    { 0x08094935, (void (*)(void))sub_08094B6C },
    { 0x08094949, (void (*)(void))sub_08094B80 },
    { 0x0809495D, (void (*)(void))sub_08094B94 },
    { 0x080949A9, (void (*)(void))sub_08094BE0 },
    { 0x08094AA5, (void (*)(void))sub_08094CDC },
    { 0x08094AD9, (void (*)(void))sub_08094D10 },
    { 0x08094AFD, (void (*)(void))sub_08094D34 },
    { 0x08094B39, (void (*)(void))sub_08094D70 },
    { 0x08094BA1, (void (*)(void))sub_08094DD8 },
    { 0x08094BD5, (void (*)(void))sub_08094E0C },
    { 0x08094D61, (void (*)(void))sub_08094F98 },
    { 0x08094F2D, (void (*)(void))sub_08095164 },
    { 0x0809500D, (void (*)(void))sub_08095244 },
    { 0x080950F9, (void (*)(void))sub_08095330 },
    { 0x0809512D, (void (*)(void))sub_08095364 },
    { 0x080951E9, (void (*)(void))sub_08095420 },
    { 0x08095221, (void (*)(void))nullsub_527 },
    { 0x08095225, (void (*)(void))sub_0809545C },
    { 0x08095445, (void (*)(void))sub_0809567C },
    { 0x080955D9, (void (*)(void))sub_08095810 },
    { 0x080957E5, (void (*)(void))sub_08095A1C },
    { 0x08095B1D, (void (*)(void))sub_08095D54 },
    { 0x08095B55, (void (*)(void))sub_08095D8C },
    { 0x08095C45, (void (*)(void))sub_08095E7C },
    { 0x08095C75, (void (*)(void))sub_08095EAC },
    { 0x08095DF1, (void (*)(void))sub_08096028 },
    { 0x08095E8D, (void (*)(void))sub_080960C4 },
    { 0x08095F79, (void (*)(void))sub_080961B0 },
    { 0x080960C1, (void (*)(void))sub_080962F8 },
    { 0x0809DE69, (void (*)(void))sub_0809E0A0 },
    { 0x0809DE9D, (void (*)(void))sub_0809E0D4 },
    { 0x080A022D, (void (*)(void))sub_080A0464 },
    { 0x080A08F1, (void (*)(void))sub_080A0B28 },
    { 0x080A1029, (void (*)(void))sub_080A1270 },
    { 0x080A1141, (void (*)(void))CuccoMinigame_Cleanup },
    { 0x080A116D, (void (*)(void))CuccoMinigame_Results },
    { 0x080A11A1, (void (*)(void))CuccoMinigame_WinItem },
    { 0x080A1219, (void (*)(void))CuccoMinigame_WinRupees },
    { 0x080A1261, (void (*)(void))CuccoMinigame_AdvanceLevel },
    { 0x080A1309, (void (*)(void))CuccoMinigame_Init },
    { 0x080A13C1, (void (*)(void))CuccoMinigame_TellObjective },
    { 0x080A1401, (void (*)(void))sub_080A1648 },
    { 0x080A1455, (void (*)(void))sub_080A169C },
    { 0x080A1EDD, (void (*)(void))Windcrest_ChangeInteractableHitbox },
    { 0x080A1EF1, (void (*)(void))Windcrest_Unlock },
    /* HAND-FIX (keep on regenerate): see EU table — maps name CreateDust
     * CreateDeathFx; JP retail addr 0x080A2774. */
    { 0x080A2775, (void (*)(void))CreateDust },
};
#define SSCRIPTFUNCTABLE_JP_SIZE (sizeof(sScriptFuncTable_JP) / sizeof(sScriptFuncTable_JP[0]))

/* Select the table for the active region (runtime gActiveRegion via REGION_IS_*). */
static const ScriptFuncEntry* ActiveScriptFuncTable(int* out_size) {
    if (REGION_IS_EU) {
        *out_size = (int)SSCRIPTFUNCTABLE_EU_SIZE;
        return sScriptFuncTable_EU;
    }
    if (REGION_IS_JP) {
        *out_size = (int)SSCRIPTFUNCTABLE_JP_SIZE;
        return sScriptFuncTable_JP;
    }
    *out_size = (int)SCRIPT_FUNC_TABLE_SIZE;
    return sScriptFuncTable;
}
#endif

/**
 * Look up a PC function pointer from a GBA Thumb address.
 * Returns NULL if not found.
 */
void* Port_LookupScriptFunc(u32 gba_addr) {
#if defined(MULTI_REGION)
    int size;
    const ScriptFuncEntry* table = ActiveScriptFuncTable(&size);
#else
    const ScriptFuncEntry* table = sScriptFuncTable;
    int size = (int)SCRIPT_FUNC_TABLE_SIZE;
#endif
    int lo = 0, hi = size - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (table[mid].gba_addr == gba_addr)
            return (void*)table[mid].func;
        else if (table[mid].gba_addr < gba_addr)
            lo = mid + 1;
        else
            hi = mid - 1;
    }
    return NULL;
}
