/*
 * port_inline_ptrs.c — AUTO-GENERATED by tools/gen_inline_ptrs.py — DO NOT EDIT
 *
 * Patch ROM-region inline rail pointers that the asset extractor doesn't include
 * in any .bin file. Several `gUnk_additional_*` room-property tables in
 * entity_headers.s interleave `.incbin` chunks with `.4byte gUnk_080X_XXXX`
 * rail-data pointers; the extractor records each `.incbin` separately and the
 * rail bytes between them fall into the gaps.
 *
 * On a developer machine those gaps are filled by Port_LoadRom from the full
 * baserom.gba (or extracted rom_data/ pages). On users' release tarballs neither
 * is present at runtime, so the gap bytes stay zero, room-property iterators see
 * NULL rail pointers, and rail-bound entities (lava platforms, moving platforms)
 * don't move. (#36 — Cave-of-Flames Rollobite + BossDoor; same pattern elsewhere.)
 *
 * The patch location and rail-pointer value are ROM addresses that DIFFER per
 * region, so the fat (multi-region) binary selects the active region's table at
 * runtime. Values derived by exact symbol lookup in the upstream zeldaret/tmc
 * maps (see tools/gen_inline_ptrs.py and docs/MULTI_REGION.md).
 */

#include <stddef.h>
#include <stdint.h>
#include "port_rom.h"
#include "region.h"


typedef struct {
    uint32_t offset;
    uint32_t value;
} InlinePtrEntry;

static const InlinePtrEntry kInlinePtrs_USA[] = {
    { 0x000E09DC, 0x080E09FC }, /* AREA_CAVE_OF_FLAMES, Room 0x08 (Rollobite). Leading rail pointer right */
    { 0x000E15E4, 0x080E1674 }, /* AREA_CAVE_OF_FLAMES, Room 0x18 (BossDoor) — 8 interleaved rail pointers */
    { 0x000E15F4, 0x080E16AA }, /* BossDoor rail pointer 2 */
    { 0x000E1604, 0x080E16CE }, /* BossDoor rail pointer 3 */
    { 0x000E1614, 0x080E16EC }, /* BossDoor rail pointer 4 */
    { 0x000E1624, 0x080E170A }, /* BossDoor rail pointer 5 */
    { 0x000E1634, 0x080E16EC }, /* BossDoor rail pointer 6 */
    { 0x000E1644, 0x080E170A }, /* BossDoor rail pointer 7 */
    { 0x000E1654, 0x080E16EC }, /* BossDoor rail pointer 8 */
};

static const InlinePtrEntry kInlinePtrs_EU[] = {
    { 0x000E00F8, 0x080E0118 }, /* AREA_CAVE_OF_FLAMES, Room 0x08 (Rollobite). Leading rail pointer right */
    { 0x000E0D00, 0x080E0D90 }, /* AREA_CAVE_OF_FLAMES, Room 0x18 (BossDoor) — 8 interleaved rail pointers */
    { 0x000E0D10, 0x080E0DC6 }, /* BossDoor rail pointer 2 */
    { 0x000E0D20, 0x080E0DEA }, /* BossDoor rail pointer 3 */
    { 0x000E0D30, 0x080E0E08 }, /* BossDoor rail pointer 4 */
    { 0x000E0D40, 0x080E0E26 }, /* BossDoor rail pointer 5 */
    { 0x000E0D50, 0x080E0E08 }, /* BossDoor rail pointer 6 */
    { 0x000E0D60, 0x080E0E26 }, /* BossDoor rail pointer 7 */
    { 0x000E0D70, 0x080E0E08 }, /* BossDoor rail pointer 8 */
};

static const InlinePtrEntry kInlinePtrs_JP[] = {
    { 0x000E074C, 0x080E076C }, /* AREA_CAVE_OF_FLAMES, Room 0x08 (Rollobite). Leading rail pointer right */
    { 0x000E1354, 0x080E13E4 }, /* AREA_CAVE_OF_FLAMES, Room 0x18 (BossDoor) — 8 interleaved rail pointers */
    { 0x000E1364, 0x080E141A }, /* BossDoor rail pointer 2 */
    { 0x000E1374, 0x080E143E }, /* BossDoor rail pointer 3 */
    { 0x000E1384, 0x080E145C }, /* BossDoor rail pointer 4 */
    { 0x000E1394, 0x080E147A }, /* BossDoor rail pointer 5 */
    { 0x000E13A4, 0x080E145C }, /* BossDoor rail pointer 6 */
    { 0x000E13B4, 0x080E147A }, /* BossDoor rail pointer 7 */
    { 0x000E13C4, 0x080E145C }, /* BossDoor rail pointer 8 */
};

/* Called from Port_LoadRom after assets + baserom.gba (if any) are in gRomData.
 * Idempotent — writes the canonical value over whatever's there. */
void Port_PatchInlinePtrs(void) {
    const InlinePtrEntry* table = kInlinePtrs_USA;
    size_t count = sizeof(kInlinePtrs_USA) / sizeof(kInlinePtrs_USA[0]);

    if (gRomData == 0) {
        return;
    }
#if defined(MULTI_REGION) || defined(EU) || defined(JP)
    if (REGION_IS_EU) {
        table = kInlinePtrs_EU;
        count = sizeof(kInlinePtrs_EU) / sizeof(kInlinePtrs_EU[0]);
    } else if (REGION_IS_JP) {
        table = kInlinePtrs_JP;
        count = sizeof(kInlinePtrs_JP) / sizeof(kInlinePtrs_JP[0]);
    }
#endif

    for (size_t i = 0; i < count; ++i) {
        uint32_t off = table[i].offset;
        if (off + 4 > gRomSize) {
            continue;
        }
        uint32_t v = table[i].value;
        gRomData[off + 0] = (uint8_t)(v & 0xFF);
        gRomData[off + 1] = (uint8_t)((v >> 8) & 0xFF);
        gRomData[off + 2] = (uint8_t)((v >> 16) & 0xFF);
        gRomData[off + 3] = (uint8_t)((v >> 24) & 0xFF);
    }
}
