/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 * Generated by tools/gen_stubs.py
 */

#include "entity.h"
#include "port_config.h"
#include "port_rom.h"
#include "port_gba_mem.h"
#include "port_types.h"
#include "player.h"
#include "projectile.h"
#include <stdint.h>
#include <string.h>
#include "port_rom.h"

extern u32 PlayerCanBeMoved(void);
extern u32 GetTileHazardType(Entity* entity);
extern u32 GetActTileAtEntity(Entity* entity);
extern void CalculateEntityTileCollisions(Entity* entity, u32 direction, u32 collisionType);
extern u32 ProcessMovementInternal(Entity* entity, s32 speed, s32 direction, u32 collisionType);
extern void sub_08079E58(s32 speed, u32 direction);
extern void CreateDrownFX(Entity* entity);
extern void CreateLavaDrownFX(Entity* entity);
extern void CreateSwampDrownFX(Entity* entity);
extern void CreatePitFallFX(Entity* entity);
extern bool32 IsColliding(Entity* this, Entity* that);
extern Entity* gCollidableList[];
extern u8 gCollidableCount;
extern void UpdateSpriteForCollisionLayer(Entity* entity);
extern void sub_080028E0(Entity* entity);
extern bool32 ProjectileInit(Entity* entity);
void sub_080044AE(Entity* entity, u32 speed, u32 direction);
void sub_08004542(Entity* entity);

/* ---- Collision resolution types (matching collision.c local defs) ---- */
typedef struct {
    /*0x00*/ u8 orgKnockbackSpeed;
    /*0x01*/ u8 orgIframes;
    /*0x02*/ u8 orgKnockbackDuration;
    /*0x03*/ u8 tgtDamage;
    /*0x04*/ u8 orgConfusedTime;
    /*0x05*/ u8 tgtKnockbackSpeed;
    /*0x06*/ s8 tgtIframes;
    /*0x07*/ u8 tgtKnockbackDuration;
    /*0x08*/ u8 orgDamage;
    /*0x09*/ u8 tgtConfusedTime;
    /*0x0a*/ u8 flags;
    /*0x0b*/ u8 pad;
} PortColSettings;

typedef u32 (*PortCollisionHandler)(Entity*, Entity*, u32, PortColSettings*);

extern PortCollisionHandler gCollisionHandlers[];
extern u8 gCollisionMtx[];
extern u32 CalculateDirectionTo(s32 x1, s32 y1, s32 x2, s32 y2);
extern u8* gRomData;
extern u32 gRomSize;

#define COL_MTX_ENTRY_SIZE 12
#define COL_MTX_STRIDE 34
#define COL_NUM_HANDLERS 23
#define COL_RESULT_NONE 0
#define COL_RESULT_COLLISION 1
/* #define COL_RESULT_NO_SET   2 */

/*
 * PortCalcCollision — simplified port of arm_CalcCollision (0x080B1D98).
 *
 * Called after IsColliding() has confirmed bounding-box overlap.
 * Computes collision direction, looks up the collision matrix, calls the
 * appropriate handler (which applies damage / knockback / iframes directly),
 * and sets knockbackDirection on both entities.
 *
 * Returns 0 if handler says no collision, 1 otherwise.
 */
static u32 PortCalcCollision(Entity* thisEntity, Entity* other) {
    /* 1. Compute collision direction (5-bit, 0-31) using hitbox-adjusted
     *    positions, matching the GBA arm_CalcCollisionDirection call. */
    s32 dx = thisEntity->x.HALF.HI - other->x.HALF.HI;
    s32 dy = thisEntity->y.HALF.HI - other->y.HALF.HI;

    if (thisEntity->hitbox && other->hitbox) {
        dx += thisEntity->hitbox->offset_x - other->hitbox->offset_x;
        dy += thisEntity->hitbox->offset_y - other->hitbox->offset_y;
    }

    u32 direction = CalculateDirectionTo(dx, dy, 0, 0);

    /* 2. Matrix lookup: gCollisionMtx[34 * other->hitType + this->hurtType]
     *    each entry = 12 bytes (PortColSettings). */
    u32 matIdx = (u32)COL_MTX_STRIDE * (u32)(u8)other->hitType + (u32)(u8)thisEntity->hurtType;
    u32 byteOff = matIdx * COL_MTX_ENTRY_SIZE;

    u32 handlerIdx = 0; /* default → CollisionDefault */
    PortColSettings* settings;

    /* Read collision settings directly from ROM at the exact offset the GBA
     * would access.  On GBA, gCollisionMtx (0x080B7B74) is only 1210 bytes,
     * but the code reads far beyond it into adjacent ROM data for high
     * hitType values (e.g. deku seed hitType=0x68).  gRomData has all that
     * data at the correct offsets. */
    if (!gRomOffsets)
        return 0;
    u32 romOff = gRomOffsets->collisionMatrix + byteOff;
    if (gRomData && romOff + COL_MTX_ENTRY_SIZE <= gRomSize) {
        u8* entry = &gRomData[romOff];
        settings = (PortColSettings*)entry;
        if (entry[0] == 0xFF) {
            /* Redirect entry: handler index at entry+2 (u16 LE) */
            handlerIdx = entry[2] | ((u32)entry[3] << 8);
        }
    } else {
        /* ROM not loaded or offset out of range → skip collision */
        return 0;
    }

    if (handlerIdx >= COL_NUM_HANDLERS)
        handlerIdx = 0;

    /* 3. Call collision handler (applies damage, knockback, iframes, …) */
    u32 result = gCollisionHandlers[handlerIdx](thisEntity, other, direction, settings);

    if (result == COL_RESULT_NONE)
        return 0;

    /* 4. Set knockback directions (only for RESULT_COLLISION, not _WITHOUT_SET) */
    if (result == COL_RESULT_COLLISION) {
        other->knockbackDirection = (u8)direction;
        thisEntity->knockbackDirection = (u8)(direction ^ 0x10);
    }

    return 1;
}

/* Area_HyruleTown -- defined in port_linked_stubs.c */

/* BounceUpdate -- implemented in port_linked_stubs.c */
/* ButtonUIElement_Actions -- defined in port_linked_stubs.c */
u32 CalcCollisionStaticEntity(Entity* target, Entity* origin) {
    const Hitbox* hbTarget;
    const Hitbox* hbOrigin;
    s32 dx, dy;
    s32 sumW, sumH;
    s32 overlapX, overlapY;
    u32 directionX, directionY, direction;
    s32 overlap;

    if (target == NULL || origin == NULL) {
        return 0;
    }

    hbTarget = (const Hitbox*)port_resolve_addr((uintptr_t)target->hitbox);
    if (hbTarget == NULL)
        return 0;
    hbOrigin = (const Hitbox*)port_resolve_addr((uintptr_t)origin->hitbox);
    if (hbOrigin == NULL)
        return 0;

    /* X overlap */
    dx = (s32)origin->x.HALF.HI + hbOrigin->offset_x;
    dx -= (s32)target->x.HALF.HI + hbTarget->offset_x;
    sumW = (s32)hbTarget->width + (s32)hbOrigin->width;
    if ((u32)(dx + sumW) > (u32)(sumW * 2)) {
        return 0;
    }
    if (dx >= 0) {
        directionX = 0x08;
    } else {
        directionX = 0x18;
        dx = -dx;
    }
    overlapX = sumW - dx;

    /* Y overlap */
    dy = (s32)origin->y.HALF.HI + hbOrigin->offset_y;
    dy -= (s32)target->y.HALF.HI + hbTarget->offset_y;
    sumH = (s32)hbTarget->height + (s32)hbOrigin->height;
    if ((u32)(dy + sumH) > (u32)(sumH * 2)) {
        return 0;
    }
    if (dy >= 0) {
        directionY = 0x10;
    } else {
        directionY = 0x00;
        dy = -dy;
    }
    overlapY = sumH - dy;

    overlap = overlapY;
    direction = directionY;
    if (overlapY >= overlapX) {
        overlap = overlapX;
        direction = directionX;
    }
    if (overlap == 0) {
        return 0;
    }
    if (overlap >= 5) {
        overlap = 4;
    }

    sub_080044AE(origin, (u32)(overlap << 8), direction);
    return 1;
}
/* CalcDistance -- implemented in port_math.c */
/* CalculateDirectionFromOffsets -- implemented in port_math.c */
/* CalculateDirectionTo -- implemented in port_math.c */
/* CheckBits — implemented in port_linked_stubs.c */
/* CheckOnLayerTransition -- implemented in port_linked_stubs.c */
/* CheckOnScreen -- defined in port_draw.c */
/* CheckPlayerInRegion -- implemented in port_linked_stubs.c */
/* CheckRectOnScreen -- implemented in port_linked_stubs.c */
/* CloneTile -- implemented in port_linked_stubs.c */
/* CreateDrownFX -- implemented in port_gameplay_stubs.c */
/* CreateLavaDrownFX -- implemented in port_gameplay_stubs.c */
/* CreateSwampDrownFX -- implemented in port_gameplay_stubs.c */
/* CreatePitFallFX -- implemented in port_gameplay_stubs.c */
/* CutsceneMain_Exit -- real implementation in src/cutscene.c */
/* CutsceneMain_Init -- real implementation in src/cutscene.c */
/* CutsceneMain_Update -- real implementation in src/cutscene.c */
/* Div -- implemented in port_bios.c */
/* DoItemTileInteraction -- implemented in port_gameplay_stubs.c */
/* DoTileInteraction -- implemented in port_gameplay_stubs.c */
/* DoTileInteractionHere -- implemented in port_gameplay_stubs.c */
/* DoTileInteractionOffset -- implemented in port_gameplay_stubs.c */
/* DrawEntity -- defined in port_draw.c */
/* EEPROM functions -- defined in port_save.c */
/* Enemies_LakeHylia_Main -- defined in port_linked_stubs.c */
/* EnemyFunctionHandler -- implemented in src/enemyUpdate.c */
/* EnemyUpdate -- implemented in src/enemyUpdate.c */
/* EnqueueSFX -- implemented in port_gameplay_stubs.c */
/* Entities_HouseInteriors1_Mayor_080D6210 -- defined in port_linked_stubs.c */
/* Entities_MinishPaths_MayorsCabin_gUnk_080D6138 -- defined in port_linked_stubs.c */
/* EntityInRectRadius -- implemented in port_linked_stubs.c */
/* EzloNagUIElement_Actions -- defined in port_linked_stubs.c */
/* FindValueForKey -- implemented in port_gameplay_stubs.c */
/* GenericConfused -- implemented in src/enemyUpdate.c */
/* GenericKnockback -- implemented in src/enemyUpdate.c */
/* GenericKnockback2 -- implemented in src/enemyUpdate.c */
/* GetActTileAtEntity -- implemented in port_linked_stubs.c */
/* GetActTileAtRoomCoords -- implemented in port_linked_stubs.c */
/* GetActTileAtTilePos -- implemented in port_linked_stubs.c */
/* GetActTileAtWorldCoords -- implemented in port_linked_stubs.c */
/* GetActTileForTileType -- implemented in port_linked_stubs.c */
/* GetActTileRelativeToEntity -- implemented in port_linked_stubs.c */
/* GetCollisionDataAtEntity -- implemented in port_linked_stubs.c */
/* GetCollisionDataAtTilePos -- implemented in port_linked_stubs.c */
/* GetCollisionDataAtWorldCoords -- implemented in port_linked_stubs.c */
/* GetCollisionDataRelativeTo -- implemented in port_linked_stubs.c */
/* GetFacingDirection -- implemented in port_linked_stubs.c */
static u64 GetFuserData(Entity* entity) {
    if (entity == NULL) return 0;
    return Port_GetEntityFuserData(entity->kind, entity->id, entity->type, entity->type2);
}

u32 GetFuserId(Entity* entity) {
    return (u32)GetFuserData(entity);
}

u64 Port_GetFuserIdAndTextId(Entity* entity) {
    return GetFuserData(entity);
}
/* GetNextFrame — implemented in port_animation.c */
/* GetNextFunction — implemented in port_linked_stubs.c */
/* GetNextScriptCommandHalfword — implemented in port_stubs.c */
/* GetNextScriptCommandHalfwordAfterCommandMetadata — implemented in port_stubs.c */
/* GetNextScriptCommandWord — implemented in port_stubs.c */
/* GetNextScriptCommandWordAfterCommandMetadata — implemented in port_stubs.c */
/* GetRandomByWeight -- implemented in port_linked_stubs.c */
/* GetTileHazardType -- implemented in port_linked_stubs.c */
/* GetTileIndex -- implemented in port_linked_stubs.c */
/* GetTileTypeAtEntity -- implemented in port_linked_stubs.c */
/* GetTileTypeAtRoomCoords -- implemented in port_linked_stubs.c */
/* GetTileTypeAtTilePos -- implemented in port_linked_stubs.c */
/* GetTileTypeAtWorldCoords -- implemented in port_linked_stubs.c */
/* GetTileTypeRelativeToEntity -- implemented in port_linked_stubs.c */
/* GravityUpdate -- implemented in port_linked_stubs.c */
/* HoleManager_Actions -- defined in port_linked_stubs.c */
/* InitAnimationForceUpdate — implemented in port_animation.c */
/* InitializeAnimation — implemented in port_animation.c */
/* LinearMoveDirectionOLD — implemented in port_linked_stubs.c */
void LoadResourceAsync(const void* src, void* dest, u32 size) {
    /*
     * PC port: perform the copy immediately instead of queuing for VBlank.
     * On GBA this queues into gUnk_03000C30 for later processing by LoadResources(),
     * but on PC we have no VBlank timing constraint, and queuing 64-bit native
     * pointers into the 12-byte/32-bit buffer format would truncate them.
     */
    void* resolvedDest = port_resolve_addr((uintptr_t)dest);
    if (resolvedDest && src && size > 0) {
        memcpy(resolvedDest, src, size);
    }
}
/* Mod — implemented in port_linked_stubs.c */
/* PlayerCheckNEastTile -- implemented in port_gameplay_stubs.c */

/* ProjectileUpdate -- implemented in src/projectileUpdate.c */
/* RAMFUNCS_END -- defined in port_linked_stubs.c */
/* Random — implemented in port_linked_stubs.c */
void ResetCollisionLayer(Entity* entity) {
    if (entity == NULL) {
        return;
    }
    entity->collisionLayer = 1;
    UpdateSpriteForCollisionLayer(entity);
}
/* ResolveCollisionLayer -- implemented in port_linked_stubs.c */
/* RupeeKeyDigits -- defined in port_linked_stubs.c */
/* SetActTileAtTilePos -- implemented in port_linked_stubs.c */
/* SetCollisionData -- implemented in port_linked_stubs.c */
/* SetTile -- implemented in port_linked_stubs.c */
/* SnapToTile -- implemented in port_gameplay_stubs.c */
/* SoundReqClipped -- implemented in port_gameplay_stubs.c */
/* Subtask_FastTravel_Functions -- defined in port_linked_stubs.c */
/* Subtask_MapHint_Functions -- defined in port_linked_stubs.c */
/* SumDropProbabilities — implemented in port_linked_stubs.c */
/* SumDropProbabilities2 — implemented in port_linked_stubs.c */
/* UnpackTextNibbles — implemented in port_text_render.c */
/* UpdateAnimationSingleFrame — implemented in port_animation.c */
/* UpdateAnimationVariableFrames — implemented in port_animation.c */
/* UpdateCollision -- implemented in port_gameplay_stubs.c */
/* UpdateCollisionLayer -- implemented in port_linked_stubs.c */
/* UpdateIcePlayerVelocity -- implemented in port_gameplay_stubs.c */
/* UpdateScrollVram — implemented in port_linked_stubs.c */
/* UpdateSpriteForCollisionLayer — implemented in port_linked_stubs.c */
/* UpperInn_Din -- defined in port_linked_stubs.c */
/* UpperInn_Farore -- defined in port_linked_stubs.c */
/* UpperInn_Nayru -- defined in port_linked_stubs.c */
/* UpperInn_NoDin -- defined in port_linked_stubs.c */
/* UpperInn_NoFarore -- defined in port_linked_stubs.c */
/* UpperInn_NoNayru -- defined in port_linked_stubs.c */
/* UpperInn_Oracles -- defined in port_linked_stubs.c */
/* bgmBeanstalk -- defined in port_linked_stubs.c */
/* bgmBeatVaati -- defined in port_linked_stubs.c */
/* bgmBossTheme -- defined in port_linked_stubs.c */
/* bgmCastleCollapse -- defined in port_linked_stubs.c */
/* bgmCastleMotif -- defined in port_linked_stubs.c */
/* bgmCastleTournament -- defined in port_linked_stubs.c */
/* bgmCastorWilds -- defined in port_linked_stubs.c */
/* bgmCaveOfFlames -- defined in port_linked_stubs.c */
/* bgmCloudTops -- defined in port_linked_stubs.c */
/* bgmCredits -- defined in port_linked_stubs.c */
/* bgmCrenelStorm -- defined in port_linked_stubs.c */
/* bgmCuccoMinigame -- defined in port_linked_stubs.c */
/* bgmDarkHyruleCastle -- defined in port_linked_stubs.c */
/* bgmDeepwoodShrine -- defined in port_linked_stubs.c */
/* bgmDiggingCave -- defined in port_linked_stubs.c */
/* bgmDungeon -- defined in port_linked_stubs.c */
/* bgmElementGet -- defined in port_linked_stubs.c */
/* bgmElementTheme -- defined in port_linked_stubs.c */
/* bgmElementalSanctuary -- defined in port_linked_stubs.c */
/* bgmEzloGet -- defined in port_linked_stubs.c */
/* bgmEzloStory -- defined in port_linked_stubs.c */
/* bgmEzloTheme -- defined in port_linked_stubs.c */
/* bgmFairyFountain -- defined in port_linked_stubs.c */
/* bgmFairyFountain2 -- defined in port_linked_stubs.c */
/* bgmFestivalApproach -- defined in port_linked_stubs.c */
/* bgmFightTheme -- defined in port_linked_stubs.c */
/* bgmFightTheme2 -- defined in port_linked_stubs.c */
/* bgmFileSelect -- defined in port_linked_stubs.c */
/* bgmFortressOfWinds -- defined in port_linked_stubs.c */
/* bgmGameover -- defined in port_linked_stubs.c */
/* bgmHouse -- defined in port_linked_stubs.c */
/* bgmHyruleCastle -- defined in port_linked_stubs.c */
/* bgmHyruleCastleNointro -- defined in port_linked_stubs.c */
/* bgmHyruleField -- defined in port_linked_stubs.c */
/* bgmHyruleTown -- defined in port_linked_stubs.c */
/* bgmIntroCutscene -- defined in port_linked_stubs.c */
/* bgmLearnScroll -- defined in port_linked_stubs.c */
/* bgmLostWoods -- defined in port_linked_stubs.c */
/* bgmLttpTitle -- defined in port_linked_stubs.c */
/* bgmMinishCap -- defined in port_linked_stubs.c */
/* bgmMinishVillage -- defined in port_linked_stubs.c */
/* bgmMinishWoods -- defined in port_linked_stubs.c */
/* bgmMtCrenel -- defined in port_linked_stubs.c */
/* bgmPalaceOfWinds -- defined in port_linked_stubs.c */
/* bgmPicoriFestival -- defined in port_linked_stubs.c */
/* bgmRoyalCrypt -- defined in port_linked_stubs.c */
/* bgmRoyalValley -- defined in port_linked_stubs.c */
/* bgmSavingZelda -- defined in port_linked_stubs.c */
/* bgmSecretCastleEntrance -- defined in port_linked_stubs.c */
/* bgmStory -- defined in port_linked_stubs.c */
/* bgmSwiftbladeDojo -- defined in port_linked_stubs.c */
/* bgmSyrupTheme -- defined in port_linked_stubs.c */
/* bgmTempleOfDroplets -- defined in port_linked_stubs.c */
/* bgmTitleScreen -- defined in port_linked_stubs.c */
/* bgmUnused -- defined in port_linked_stubs.c */
/* bgmVaatiMotif -- defined in port_linked_stubs.c */
/* bgmVaatiReborn -- defined in port_linked_stubs.c */
/* bgmVaatiTheme -- defined in port_linked_stubs.c */
/* bgmVaatiTransfigured -- defined in port_linked_stubs.c */
/* bgmVaatiWrath -- defined in port_linked_stubs.c */
/* bgmWindRuins -- defined in port_linked_stubs.c */
/* gAreaMetadata -- defined in port_linked_stubs.c */
/* gAreaRoomHeaders -- defined in port_linked_stubs.c */
/* gAreaRoomMaps -- defined in port_linked_stubs.c */
/* gAreaTable -- defined in port_linked_stubs.c */
/* gAreaTileSets -- defined in port_linked_stubs.c */
/* gAreaTiles -- defined in port_linked_stubs.c */

/* gCaveBorderMapData -- defined in port_linked_stubs.c */
/* gChooseFileState — defined in port_linked_stubs.c */
/* gCollidableCount — defined in port_linked_stubs.c */
/* gCollisionMtx — defined in port_linked_stubs.c */
/* gCopyToEndOfEwram_End -- defined in port_linked_stubs.c */
/* gCopyToEndOfEwram_Start -- defined in port_linked_stubs.c */

/* gDiggingCaveEntranceTransition -- defined in port_linked_stubs.c */
/* gDungeonMap -- defined in port_linked_stubs.c */
/* gDungeonNames -- defined in port_linked_stubs.c */
/* gEndOfEwram -- defined in port_linked_stubs.c */

/* gExitList_RoyalValley_ForestMaze -- defined in port_linked_stubs.c */
/* gExitLists -- defined in port_linked_stubs.c */
/* gExtraFrameOffsets -- defined in port_linked_stubs.c */
/* gFigurines -- defined in port_figurines.c */
/* gFixedTypeGfxData -- defined in port_linked_stubs.c */

/* gFuseInfo -- defined in port_linked_stubs.c */
/* gHitbox_0 -- defined in port_linked_stubs.c */
/* gHitbox_1 -- defined in port_linked_stubs.c */
/* gHitbox_10 -- defined in port_linked_stubs.c */
/* gHitbox_11 -- defined in port_linked_stubs.c */
/* gHitbox_12 -- defined in port_linked_stubs.c */
/* gHitbox_13 -- defined in port_linked_stubs.c */
/* gHitbox_14 -- defined in port_linked_stubs.c */
/* gHitbox_15 -- defined in port_linked_stubs.c */
/* gHitbox_16 -- defined in port_linked_stubs.c */
/* gHitbox_17 -- defined in port_linked_stubs.c */
/* gHitbox_18 -- defined in port_linked_stubs.c */
/* gHitbox_19 -- defined in port_linked_stubs.c */
/* gHitbox_2 -- defined in port_linked_stubs.c */
/* gHitbox_20 -- defined in port_linked_stubs.c */
/* gHitbox_21 -- defined in port_linked_stubs.c */
/* gHitbox_22 -- defined in port_linked_stubs.c */
/* gHitbox_23 -- defined in port_linked_stubs.c */
/* gHitbox_24 -- defined in port_linked_stubs.c */
/* gHitbox_25 -- defined in port_linked_stubs.c */
/* gHitbox_26 -- defined in port_linked_stubs.c */
/* gHitbox_27 -- defined in port_linked_stubs.c */
/* gHitbox_28 -- defined in port_linked_stubs.c */
/* gHitbox_29 -- defined in port_linked_stubs.c */
/* gHitbox_3 -- defined in port_linked_stubs.c */
/* gHitbox_30 -- defined in port_linked_stubs.c */
/* gHitbox_31 -- defined in port_linked_stubs.c */
/* gHitbox_32 -- defined in port_linked_stubs.c */
/* gHitbox_4 -- defined in port_linked_stubs.c */
/* gHitbox_5 -- defined in port_linked_stubs.c */
/* gHitbox_6 -- defined in port_linked_stubs.c */
/* gHitbox_7 -- defined in port_linked_stubs.c */
/* gHitbox_8 -- defined in port_linked_stubs.c */
/* gHitbox_9 -- defined in port_linked_stubs.c */

/* gLilypadRails -- defined in port_linked_stubs.c */
/* gMPlayInfos -- defined in port_linked_stubs.c */
/* gMPlayInfos2 -- defined in port_linked_stubs.c */
/* gMPlayTracks -- defined in port_linked_stubs.c */

/* gManagerCount — defined in port_linked_stubs.c */
/* gMapActTileToSurfaceType -- defined in port_linked_stubs.c */
/* gMapBottom — defined in port_linked_stubs.c */
/* gMapData — defined in port_linked_stubs.c */
/* gMapDataBottomSpecial -- defined in port_linked_stubs.c */
/* gMapDataTopSpecial -- defined in port_linked_stubs.c */
/* gMapTop — defined in port_linked_stubs.c */
/* gMenu — defined in port_linked_stubs.c */
/* gMessageChoices -- defined in port_linked_stubs.c */
/* gMoreSpritePtrs -- defined in port_linked_stubs.c */
/* gNPCData -- defined in port_linked_stubs.c */
/* gOverworldLocations -- defined in port_linked_stubs.c */
/* gPaletteBufferBackup — defined in port_linked_stubs.c */
/* gPaletteList -- defined in port_linked_stubs.c */
/* gPalette_549 -- defined in port_linked_stubs.c */
/* gPauseMenuOptions -- defined in port_linked_stubs.c */
/* gPlayerClones — defined in port_linked_stubs.c */
/* gPlayerEntity — defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers0 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers1 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers2 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers3 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers4 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers5 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers6 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers7 -- defined in port_linked_stubs.c */
/* gPlayerScriptExecutionContext — defined in port_linked_stubs.c */
/* gPlayerState — defined in port_linked_stubs.c */
/* gPossibleInteraction — defined in port_linked_stubs.c */
/* gPriorityHandler — defined in port_linked_stubs.c */
/* gRoomControls — defined in port_linked_stubs.c */
/* gRoomMemory — defined in port_linked_stubs.c */
/* gRoomTransition — defined in port_linked_stubs.c */
/* gRoomVars — defined in port_linked_stubs.c */
/* gSave — defined in port_linked_stubs.c */
/* gScriptExecutionContextArray — defined in port_linked_stubs.c */
/* gShakeOffsets -- defined in port_linked_stubs.c */
/* gSmallChests -- defined in port_linked_stubs.c */
/* gSpriteAnimations_322 -- defined in port_linked_stubs.c */
/* gSpriteAnimations_GhostBrothers -- defined in port_linked_stubs.c */
/* gSpritePtrs -- defined in port_linked_stubs.c */
/* gSubtasks -- defined in port_linked_stubs.c */
/* gTextGfxBuffer — defined in port_linked_stubs.c */
/* gTilesForSpecialTiles -- defined in port_linked_stubs.c */
/* gTranslations -- defined in port_linked_stubs.c */
/* gUI — defined in port_linked_stubs.c */
/* gUIElementDefinitions -- defined in port_linked_stubs.c */
/* gUnk_03000420 -- defined in port_linked_stubs.c */
/* gUnk_03000C30 -- defined in port_linked_stubs.c */
/* gUnk_03001020 -- defined in port_linked_stubs.c */
/* gUnk_03003C70 -- defined in port_linked_stubs.c */
u8 gUnk_03003DE0;
u8 gUnk_03003DE4[0xC];
/* gUnk_additional_8_DeepwoodShrine_StairsToB1 -- defined in port_linked_stubs.c */
/* gUnk_additional_8_HouseInteriors1_Library1F -- defined in port_linked_stubs.c */
/* gUnk_additional_8_HouseInteriors3_BorlovEntrance -- defined in port_linked_stubs.c */
/* gUnk_additional_8_HyruleCastle_3 -- defined in port_linked_stubs.c */
/* gUnk_additional_8_MelarisMine_Main -- defined in port_linked_stubs.c */
/* gUnk_additional_8_PalaceOfWinds_GyorgTornado -- defined in port_linked_stubs.c */
/* gUnk_additional_9_HouseInteriors1_Library1F -- defined in port_linked_stubs.c */
/* gUnk_additional_9_HouseInteriors2_Percy -- defined in port_linked_stubs.c */
/* gUnk_additional_9_HouseInteriors3_BorlovEntrance -- defined in port_linked_stubs.c */
/* gUnk_additional_9_MelarisMine_Main -- defined in port_linked_stubs.c */
/* gUnk_additional_9_PalaceOfWinds_GyorgTornado -- defined in port_linked_stubs.c */
/* gUnk_additional_a_CaveOfFlamesBoss_Main -- defined in port_linked_stubs.c */
/* gUnk_additional_a_DeepwoodShrineBoss_Main -- defined in port_linked_stubs.c */
/* gUnk_additional_a_HouseInteriors2_Percy -- defined in port_linked_stubs.c */
/* gUnk_additional_a_HouseInteriors3_BorlovEntrance -- defined in port_linked_stubs.c */
/* gUnk_additional_a_TempleOfDroplets_BigOcto -- defined in port_linked_stubs.c */
/* gUnk_additional_c_HouseInteriors2_Romio -- defined in port_linked_stubs.c */
/* gUpdateContext — defined in port_linked_stubs.c */
/* gUpdateVisibleTiles — defined in port_linked_stubs.c */
/* gVBlankDMA — defined in port_linked_stubs.c */
/* gWallMasterScreenTransitions -- defined in port_linked_stubs.c */
/* gZeldaFollowerText -- defined in port_linked_stubs.c */
/* gzHeap -- defined in port_linked_stubs.c */
/* m4aMPlayAllStop -- implemented in port_m4a_stubs.c */
/* m4aMPlayImmInit -- implemented in port_m4a_stubs.c */
/* m4aMPlayTempoControl -- implemented in port_m4a_stubs.c */
/* m4aMPlayVolumeControl -- implemented in port_m4a_stubs.c */
/* m4aSongNumStart -- implemented in port_m4a_stubs.c */
/* m4aSongNumStartOrContinue -- implemented in port_m4a_stubs.c */
/* m4aSongNumStop -- implemented in port_m4a_stubs.c */
/* m4aSoundInit -- implemented in port_m4a_stubs.c */
/* m4aSoundMain -- implemented in port_m4a_stubs.c */
/* m4aSoundVSync -- implemented in port_m4a_stubs.c */
/* m4aSoundVSyncOff -- implemented in port_m4a_stubs.c */
/* m4aSoundVSyncOn -- implemented in port_m4a_stubs.c */
/* ram_ClearAndUpdateEntities -- defined in port_draw.c */
u32 ram_CollideAll(void) {
    s32 i;
    s32 j;

    /*
     * GBA arm_CollideAll outer loop iterates gUnk_02018EA0, a registered
     * hitbox list that contains ONLY: the player entity, player items
     * (sword, bow, shield, boomerang, etc.), and a few special objects
     * (minecart, player clone, smoke particle) — all registered via
     * sub_0801766C which sets spritePriority.b2 = 1.
     *
     * The original PC port incorrectly iterated gCollidableList for the
     * outer loop, letting ALL collidable entities (including enemy
     * projectiles) set contactFlags on ALL other entities. This caused
     * e.g. the business scrub's deku seed to self-collide with the scrub,
     * falsely triggering its hit reaction.
     *
     * Fix: filter the outer loop to only process entities that would be
     * in the GBA's registered hitbox list.
     */
    for (i = 0; i < (s32)gCollidableCount; i++) {
        Entity* thisEntity = gCollidableList[i];
        u32 collideMask;
        s8 thisIFrames;
        u8 thisCollisionFlags;

        if (thisEntity == NULL) {
            continue;
        }
        if ((thisEntity->flags & 0x80) == 0) {
            continue;
        }

        /* Match GBA: only registered hitbox entities act as "attackers".
         * Player and player items are always eligible; other entities
         * (objects) must have been registered via sub_0801766C. */
        {
            u8 kind = thisEntity->kind;
            if (kind != PLAYER && kind != PLAYER_ITEM) {
                if (!thisEntity->spritePriority.b2) {
                    continue;
                }
            }
        }

        thisCollisionFlags = thisEntity->collisionFlags;
        collideMask = 1u << (thisCollisionFlags & 7);
        thisIFrames = thisEntity->iframes;

        for (j = (s32)gCollidableCount - 1; j >= 0; j--) {
            Entity* other = gCollidableList[j];

            if (other == NULL || other == thisEntity) {
                continue;
            }
            if ((other->collisionMask & collideMask) == 0) {
                continue;
            }
            if ((other->flags & 0x80) == 0) {
                continue;
            }
            if ((thisEntity->collisionLayer & other->collisionLayer) == 0) {
                continue;
            }

            /* GBA checks bit 6 (0x40) of combined collisionFlags to skip
             * the iframes check.  If neither side has this flag, skip
             * collision while either entity has iframes. */
            if (((other->collisionFlags | thisCollisionFlags) & 0x40) == 0) {
                if ((other->iframes | thisIFrames) != 0) {
                    continue;
                }
            }

            if (!IsColliding(thisEntity, other)) {
                continue;
            }

            /* Call collision resolution (matrix lookup + handler).
             * On the GBA, arm_CalcCollision does this:
             *  1. Compute collision direction
             *  2. Look up collision handler from gCollisionMtx
             *  3. Call handler (applies damage, knockback, iframes)
             *  4. Set knockbackDirection on both entities
             * If the handler returns NO_COLLISION, skip contactFlags. */
            if (!PortCalcCollision(thisEntity, other)) {
                continue;
            }

            if ((other->contactFlags & 0x80) == 0) {
                other->contactedEntity = thisEntity;
                other->contactFlags = thisEntity->hurtType | 0x80;
            }
            if ((thisEntity->contactFlags & 0x80) == 0) {
                thisEntity->contactedEntity = other;
                thisEntity->contactFlags = other->hurtType | 0x80;
            }
        }
    }

    return 0;
}
/* ram_DrawDirect -- defined in port_draw.c */
/* ram_DrawEntities -- defined in port_draw.c */
u32 ram_IntrMain(void) {
    return 0;
}
/* ram_MakeFadeBuff256 -- defined in port_linked_stubs.c */
/* ram_UpdateEntities -- defined in port_draw.c */
/* ram_sub_080ADA04 -- defined in port_draw.c */
/* ram_sub_080B197C -- defined in port_linked_stubs.c */
/* script_08012C48 -- defined in port_linked_stubs.c */
/* script_08015B14 -- defined in port_linked_stubs.c */
/* script_BedAtSimons -- defined in port_linked_stubs.c */
/* script_BedInLinksRoom -- defined in port_linked_stubs.c */
/* script_BombMinish -- defined in port_linked_stubs.c */
/* script_BombMinishKinstone -- defined in port_linked_stubs.c */
/* script_BusinessScrubIntro -- defined in port_linked_stubs.c */
/* script_CutsceneMiscObjectSwordInChest -- defined in port_linked_stubs.c */
/* script_CutsceneMiscObjectTheLittleHat -- defined in port_linked_stubs.c */
/* script_EzloTalkOcarina -- defined in port_linked_stubs.c */
/* script_ForestMinish1 -- defined in port_linked_stubs.c */
/* script_ForestMinish10 -- defined in port_linked_stubs.c */
/* script_ForestMinish11 -- defined in port_linked_stubs.c */
/* script_ForestMinish12 -- defined in port_linked_stubs.c */
/* script_ForestMinish13 -- defined in port_linked_stubs.c */
/* script_ForestMinish14 -- defined in port_linked_stubs.c */
/* script_ForestMinish15 -- defined in port_linked_stubs.c */
/* script_ForestMinish16 -- defined in port_linked_stubs.c */
/* script_ForestMinish17 -- defined in port_linked_stubs.c */
/* script_ForestMinish18 -- defined in port_linked_stubs.c */
/* script_ForestMinish19 -- defined in port_linked_stubs.c */
/* script_ForestMinish2 -- defined in port_linked_stubs.c */
/* script_ForestMinish20 -- defined in port_linked_stubs.c */
/* script_ForestMinish21 -- defined in port_linked_stubs.c */
/* script_ForestMinish3 -- defined in port_linked_stubs.c */
/* script_ForestMinish4 -- defined in port_linked_stubs.c */
/* script_ForestMinish5 -- defined in port_linked_stubs.c */
/* script_ForestMinish6 -- defined in port_linked_stubs.c */
/* script_ForestMinish7 -- defined in port_linked_stubs.c */
/* script_ForestMinish8 -- defined in port_linked_stubs.c */
/* script_ForestMinish9 -- defined in port_linked_stubs.c */
/* script_MazaalBossObjectMazaal -- defined in port_linked_stubs.c */
/* script_MazaalMacroDefeated -- defined in port_linked_stubs.c */
/* script_MinishVillageObjectLeftStoneOpening -- defined in port_linked_stubs.c */
/* script_MinishVillageObjectRightStoneOpening -- defined in port_linked_stubs.c */
/* script_PlayerAtDarkNut1 -- defined in port_linked_stubs.c */
/* script_PlayerAtDarkNut2 -- defined in port_linked_stubs.c */
/* script_PlayerAtDarkNut3 -- defined in port_linked_stubs.c */
/* script_PlayerAtMadderpillar -- defined in port_linked_stubs.c */
/* script_PlayerGetElement -- defined in port_linked_stubs.c */
/* script_PlayerIntro -- defined in port_linked_stubs.c */
/* script_PlayerSleepingInn -- defined in port_linked_stubs.c */
/* script_PlayerWakeAfterRest -- defined in port_linked_stubs.c */
/* script_PlayerWakingUpAtSimons -- defined in port_linked_stubs.c */
/* script_PlayerWakingUpInHyruleCastle -- defined in port_linked_stubs.c */
/* script_Rem -- defined in port_linked_stubs.c */
/* script_Stockwell -- defined in port_linked_stubs.c */
/* script_StockwellBuy -- defined in port_linked_stubs.c */
/* script_StockwellDogFood -- defined in port_linked_stubs.c */
/* script_TalonGotKey -- defined in port_linked_stubs.c */
/* script_WindTribespeople6 -- defined in port_linked_stubs.c */
/* script_ZeldaMagic -- defined in port_linked_stubs.c */
/* sub_08000E44 -- implemented in port_gameplay_stubs.c */
/* sub_08000E62 -- implemented in port_gameplay_stubs.c */
/* sub_08001290 -- implemented in src/enemyUpdate.c */
/* sub_080012DC -- implemented in src/enemyUpdate.c */
/* sub_08001318 -- implemented in src/enemyUpdate.c */
/* sub_0800132C -- implemented in src/enemyUpdate.c */
/* sub_080026C4 — implemented in port_text_render.c */
/* sub_080026F2 — implemented in port_text_render.c */
/* sub_080028E0 -- implemented in port_linked_stubs.c */
/* sub_08003FDE -- implemented in port_gameplay_stubs.c */
/* sub_080040A2 -- implemented in port_gameplay_stubs.c */
/* sub_080040D8 -- implemented in port_gameplay_stubs.c */
/* sub_080040E2 -- implemented in port_gameplay_stubs.c */
/* sub_0800417E -- implemented in port_gameplay_stubs.c */
/* sub_0800419C -- implemented in port_gameplay_stubs.c */
/* sub_080041DC -- implemented in port_gameplay_stubs.c */
/* sub_080041E8 -- implemented in port_gameplay_stubs.c */
/* sub_08004202 -- implemented in port_gameplay_stubs.c */
/* sub_080042BA — implemented in port_animation.c */
/* sub_080042D0 — implemented in port_animation.c */
u32 sub_0800442E(Entity* entity) {
    u32 hazard = GetTileHazardType(entity);
    if (hazard == 0) {
        return 0;
    }
    switch (hazard) {
        case 1:
            CreatePitFallFX(entity);
            break;
        case 2:
            CreateDrownFX(entity);
            break;
        case 3:
            CreateLavaDrownFX(entity);
            break;
        case 4:
            CreateSwampDrownFX(entity);
            break;
        default:
            break;
    }
    return 1;
}
u32 sub_0800445C(Entity* entity) {
    if (!PlayerCanBeMoved()) {
        return 0;
    }
    if (!CalcCollisionStaticEntity(entity, &gPlayerEntity.base)) {
        return 0;
    }
    if (gPlayerEntity.base.action == 2) {
        gPlayerEntity.base.subAction = 3;
    }
    return 1;
}
void sub_080044AE(Entity* entity, u32 speed, u32 direction) {
    if (entity != &gPlayerEntity.base) {
        CalculateEntityTileCollisions(entity, direction, 2);
        ProcessMovementInternal(entity, (s32)speed, (s32)direction, 2);
    } else {
        sub_08079E58(speed, direction);
    }
}
void sub_0800451C(Entity* entity) {
    u32 actTile = GetActTileAtEntity(entity);
    switch (actTile) {
        case 0x0b:
        case 0x0c:
            sub_08004542(entity);
            break;
        case 0x09:
        case 0x0a:
            ResetCollisionLayer(entity);
            break;
        case 0x26:
        case 0x27:
            entity->collisionLayer = 3;
            UpdateSpriteForCollisionLayer(entity);
            break;
        default:
            break;
    }
}
void sub_08004542(Entity* entity) {
    if (entity == NULL) {
        return;
    }
    entity->collisionLayer = 2;
    UpdateSpriteForCollisionLayer(entity);
}
void sub_08004596(Entity* entity, u32 targetDirection) {
    u32 direction = entity->direction;
    if (direction < 0x20) {
        s32 delta = ((s32)targetDirection - (s32)direction) & 0x1f;
        if (delta != 0) {
            if (delta < 0x10) {
                direction = (direction + 1) & 0x1f;
            } else {
                direction = (direction - 1) & 0x1f;
            }
        }
    } else {
        direction = targetDirection & 0x1f;
    }
    entity->direction = (u8)direction;
}
/* sub_080045B4 — implemented in port_linked_stubs.c */
/* sub_0800857C — implemented in port_linked_stubs.c */
/* sub_080085B0 — implemented in port_linked_stubs.c */
/* sub_080086B4 -- implemented in port_linked_stubs.c */
/* sub_08008926 -- implemented in port_gameplay_stubs.c */
/* sub_08008AA0 — implemented in port_linked_stubs.c */
/* sub_08008AC6 — implemented in port_linked_stubs.c */
/* sub_080B197C -- defined in port_linked_stubs.c */
/* sub_080B1B84 -- implemented in port_linked_stubs.c */
/* sub_080B1BA4 -- implemented in port_linked_stubs.c */
