#!/usr/bin/env python3
"""Generate port/generated_sounds_embed.cpp from assets/sounds.json.

The audio backend (port_m4a_backend.cpp) probes a few on-disk locations
for sounds.json so the dev tree and release tarball both work; if none
of those hit, it falls back to the byte array produced here so a bare
`tmc_pc + baserom.gba` install still has audio.

The script is deterministic: byte-for-byte identical inputs produce
byte-for-byte identical output, so it's safe to run on every build
without busting xmake's incremental cache.

Usage:
    python tools/generate_sounds_embed.py <input> <output>
        <input>   path to assets/sounds.json
        <output>  path to port/generated_sounds_embed.cpp

If the input is missing, the generator emits an empty array (size 0)
so the build doesn't break — the audio backend treats a zero-length
embedded blob as "no embedded fallback" and falls through to its
existing "songs will be silent" warning.
"""
from __future__ import annotations

import sys
from pathlib import Path

BYTES_PER_LINE = 16


def render_text(data: bytes) -> str:
    """Render `data` as a static byte array referenced by the
    PortSoundsEmbed::kData / kSize symbols declared in
    port/port_sounds_embed.hpp.

    A zero-length C++ array is ill-formed, so an empty input emits a
    one-byte sentinel with kSize=0; the audio backend keys off kSize
    and treats 0 as "no embedded fallback available"."""

    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by tools/generate_sounds_embed.py")
    lines.append(" * DO NOT EDIT BY HAND. Edit assets/sounds.json instead and rebuild.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "port_sounds_embed.hpp"')
    lines.append("")
    lines.append("namespace PortSoundsEmbed {")
    lines.append("")
    if not data:
        lines.append("const unsigned char kData[1] = { 0x00 };")
        lines.append("const std::size_t kSize = 0;")
    else:
        lines.append(f"const unsigned char kData[{len(data)}] = {{")
        for offset in range(0, len(data), BYTES_PER_LINE):
            chunk = data[offset:offset + BYTES_PER_LINE]
            hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
            lines.append(f"    {hex_bytes},")
        lines.append("};")
        lines.append(f"const std::size_t kSize = {len(data)};")
    lines.append("")
    lines.append("}  // namespace PortSoundsEmbed")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        sys.stderr.write(
            "usage: generate_sounds_embed.py <assets/sounds.json> <port/generated_sounds_embed.cpp>\n"
        )
        return 2

    input_path = Path(argv[1])
    output_path = Path(argv[2])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if input_path.exists():
        data = input_path.read_bytes()
    else:
        sys.stderr.write(
            f"[generate_sounds_embed] {input_path} missing — embedding empty fallback\n"
        )
        data = b""

    # Skip the write when the on-disk file already matches what we'd
    # produce, so xmake doesn't see a fresh mtime and rebuild every TU
    # that includes the header.
    new_text = render_text(data)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == new_text:
        return 0

    output_path.write_text(new_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
