#!/bin/bash
# Compile the SDL_GPU shader sources to SPIR-V.
#
# Run this from the repo root or from port/shaders/ — either works.
# Output lands in port/shaders/build/ and is committed (the binaries
# are small, ~1 KB each, and committing them avoids forcing every
# build host to install a Vulkan SDK).
#
# Re-run whenever a .vert or .frag file changes. CI will not re-run
# this; the .spv files in port/shaders/build/ are the source of truth
# at build time.
#
# Dependencies:
#   - glslangValidator (Vulkan SDK; or `apt install glslang-tools`,
#     `brew install glslang`, `pacman -S glslang`)

set -euo pipefail

cd "$(dirname "$0")"
out=build
mkdir -p "$out"

for vert in *.vert; do
    [ -f "$vert" ] || continue
    name="${vert%.vert}"
    echo "  vert  $vert"
    glslangValidator -V -S vert -o "$out/$name.vert.spv" "$vert"
done

for frag in *.frag; do
    [ -f "$frag" ] || continue
    name="${frag%.frag}"
    echo "  frag  $frag"
    glslangValidator -V -S frag -o "$out/$name.frag.spv" "$frag"
done

echo "done — emitted SPIR-V to $out/"

# ---------------------------------------------------------------------------
# Metal Shading Language for the GPU PPU rasterizer (Apple backends).
#
# The stock presentation filters keep hand-written MSL in
# port_gpu_msl_shaders.inl, but the PPU rasterizer shader is far too large to
# hand-translate, so its MSL is generated from the SPIR-V by spirv-cross and
# committed as port/shaders/build/ppu_raster_msl.inl. This step runs only when
# spirv-cross is installed; Vulkan platforms never need it. SDL_GPU's MSL
# convention wants the entry point named `main0`.
#
#   Regenerate whenever ppu_raster.frag / .vert change AND you can run
#   spirv-cross (macOS dev box or CI with the Vulkan SDK). Commit the .inl.
# ---------------------------------------------------------------------------
if command -v spirv-cross >/dev/null 2>&1; then
    inl="$out/ppu_raster_msl.inl"
    echo "  msl   ppu_raster.{vert,frag} -> $inl (spirv-cross)"
    {
        echo "/* Auto-generated by port/shaders/build.sh via spirv-cross. DO NOT EDIT. */"
        echo "/* MSL for the GPU PPU rasterizer (SDL_GPU Metal backend). */"
        printf 'static const char kPpuRasterVertMsl[] = R"msl(\n'
        spirv-cross --msl --msl-version 20000 --rename-entry-point main main0 vert "$out/ppu_raster.vert.spv"
        printf ')msl";\n'
        printf 'static const char kPpuRasterFragMsl[] = R"msl(\n'
        spirv-cross --msl --msl-version 20000 --rename-entry-point main main0 frag "$out/ppu_raster.frag.spv"
        printf ')msl";\n'
    } > "$inl"
    echo "done — emitted MSL to $inl"
else
    echo "spirv-cross not found — skipping MSL generation (Apple GPU raster falls"
    echo "back to the CPU rasterizer until port/shaders/build/ppu_raster_msl.inl"
    echo "is committed; Vulkan platforms are unaffected)."
fi
